### ISSUE TITLE
resolver = "2" doesn't apply dev-dependencies when building in debug

### ISSUE THREAD

**Issue by nappa85** [rust-lang/cargo#10010]
### Problem

With resolver 1 dev-dependencies where applied also on debug builds, with resolver 2 (so with edition 2021) this doesn't happens.
This isn't a showstopper, but it was a quite common thing to enable additional features during development (e.g. print in stdout database queries) and automatically not having it in release build.

### Steps

Create a new project like this:
Cargo toml
```toml
[package]
name = "debug-test"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = { version = "0.8.4", default-features = false }

[dev-dependencies]
env_logger = { version = "0.8.4", features = ["termcolor", "atty", "humantime", "regex"] }
```
src/main.rs
```rust
fn main() {
  env_logger::init();
  log::error!("Hello, world!");
}
```

with a simple `cargo run` you'll see something like`[2021-10-25T12:56:17Z ERROR debug_test] Hello, world!` (with ERROR colored in red).
Simply adding `resolver = "2"` to Cargo.toml and re-running, you'll obtain something like `[ERROR debug_test] Hello, world!` because additional features written in `dev-dependencies` aren't applied.

### Possible Solution(s)

Can we get back to previous behavior?

### Notes

I was aware of changes due to defaulting  to resolver 2 with 2021 edition, but this one was unexpected and took me a while to realize it wasn't a bug in my code.

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```
