### ISSUE TITLE
Optional dependencies with `links` cause failure even when not used

### ISSUE THREAD

**Issue by korken89** [rust-lang/cargo#10066]
### Problem

As a dependency I want 2 versions of a crate, but the crate uses the `links` attribute as only one is allowed.
If I rename the 2 versions of a crate and use the `package` and set `optional = true` the `links` check still fails, even though none of the optional dependencies are enabled.

I'd expect this to work with only one of the 2 enabled, but fail with a `links` error if both were enabled.
And it seems from here that this should be allowed: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml
With the line `Depend on multiple versions of a crate.`

### Steps

Use the following `Cargo.toml` in an empty project and run `cargo build` to show the issue:

```toml
[package]
name = "dual-defmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.defmt02]
package = "defmt"
version = "0.2"
optional = true

[dependencies.defmt03]
package = "defmt"
version = "0.3"
optional = true
```

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```
