### ISSUE TITLE
`cargo help <alias>` should show what `<alias>` stands for

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/cargo#10138]
### Problem

Currently, if I have a `.cargo/config` like this:

```toml
[alias]
bw = "build --target x86_64-pc-windows-msvc --release"
bl = "build --target x86_64-unknown-linux-musl --release"
```

And I do `cargo help bw`

I get the help for `cargo build`

### Proposed Solution

Instead of the current behavior, I would like something like `git`:

```sh
$ git help c
'c' is aliased to 'commit'

$ git help cam
'cam' is aliased to 'commit --amend -m'
```

If I want the infos for `build`, `cargo bw --help` would still work, just like `git cam --help` show the full help for `commit` in the example above.

### Notes

One thing I have not seen `git` do is tell from where the alias comes. If possible, indicating the file (and even the precise location) would be very nice.

The same could be done for subcommands like `cargo add` from `cargo-edit`, with something like this:

```sh
$ cargo help add
`cargo add` comes from `$CARGo_HOME/bin/cargo-add`
```

But this could be a separate feature request, I don't know how much the two are linked internally.
