### ISSUE TITLE
Support features based on the target

### ISSUE THREAD

**Issue by jdrouet** [rust-lang/cargo#10146]
### Problem

I'm building a crate where the default features depends on the target architecture.
I've features `A`, `B` and `C`. On `x86_64`, the features `A` and `B` shoud be enabled by default, on `ARM`, `B` and `C` should be enabled by default, etc.

### Proposed Solution

The same way cargo [handles dependencies depending on the target](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) we could imagine a solution like
```toml
[target.'cfg(target_arch = "x86")'.features]
default = ["A", "B"]

[target.'cfg(target_arch = "ARM")'.features]
default = ["B", "C"]
```

### Notes

This is related to [this project](https://github.com/jdrouet/docker-activity), where [powercap](https://github.com/jdrouet/powercap) is being handled only by `x86_64` processors, but `docker-activity` should still keep working on `ARM` but _just_ have the feature disabled.
