### ISSUE TITLE
Duplicate use of std core when using `-Z build-std`

### ISSUE THREAD

**Issue by mensch272** [rust-lang/cargo#10200]
### Problem

I am building a program for `wasm32-unknown-unknown`, as it is dependent on [parking_lot](https://github.com/Amanieu/parking_lot), I'm building on nightly channel and recompiling std using [`-Zbuild-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) flag.

The program fails with the below error.

```
error: duplicate lang item in crate `core`: `bool`.
  |
  = note: the lang item is first defined in crate `core` (which `std` depends on)
  = note: first definition in `core` loaded from \\?\C:\Users\User\Documents\Projects\Rust\chapturn-sources-wasm\target\wasm32-unknown-unknown\debug\deps\libcore-6fe30f0fbc5b5f52.rlib, \\?\C:\Users\User\Documents\Projects\Rust\chapturn-sources-wasm\target\wasm32-unknown-unknown\debug\deps\libcore-6fe30f0fbc5b5f52.rmeta
  = note: second definition in `core` loaded from \\?\C:\Users\User\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\wasm32-unknown-unknown\lib\libcore-3365b6c50e94718e.rlib
```

This is a continuation from [parking_lot#304](https://github.com/Amanieu/parking_lot/issues/308).

### Command

```
cargo build --lib --target wasm32-unknown-unknown -Z build-std
```

### Config

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "chapturn-sources-wasm"
version = "0.1.0"
authors = ["Mensch272 <47662901+mensch272@users.noreply.github.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
chapturn-sources = { path = "../chapturn-sources" }
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }
serde = "1.0.130"

parking_lot = { version = "0.11", features = ["nightly"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.dev]
opt-level = 2
incremental = true

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
```
</details>

<details>
<summary>.cargo/config.toml</summary>

```toml
[build]
rustflags = ["-Ctarget-feature=+atomics,+mutable-globals,+bulk-memory"]
```
</details>

[output.txt](https://github.com/Amanieu/parking_lot/files/7721364/output.txt)

### Version

```text
cargo 1.58.0-nightly (40dc28175 2021-12-06)
release: 1.58.0
commit-hash: 40dc281755137ee804bc9b3b08e782773b726e44
commit-date: 2021-12-06
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.19043 (Windows 10 Home Single Language) [64-bit]
```
