### ISSUE TITLE
The build script for optional dependencies will be executed, even if the dependency is removed through the feature

### ISSUE THREAD

**Issue by Easonzero** [rust-lang/cargo#10229]
### Problem

A crate has a optional dependency which contains a build.rs, like this:
```toml
[[dependencies]]
foo = { version="...", optional=true } # crate foo has a build.rs
```
the foo's build.rs will always run, even if there are no feature `foo` when building.

### Version

```text
1.56.0
```
