### ISSUE TITLE
`cargo new` should allow the project name be different from the path

### ISSUE THREAD

**Issue by erickt** [rust-lang/cargo#1030]
Right now running `cargo new foo` produces a directory named `foo` and a `Cargo.toml` with:

```toml
[package]

name = "foo"
version = "0.0.1"
authors = ["..."]
```

Instead, we should allow a user to specify the crate name independently from the path we create. For example, we could allow `cargo new foo bar` to make the directory `bar` that contains the previous toml file.
