### ISSUE TITLE
Failure to resolve features transitively when said features are used in `#[cfg(feature = xxxx)]` in code generated by a macro

### ISSUE THREAD

**Issue by ripdajacker** [rust-lang/cargo#10331]
### Problem

I am working on a project that uses macros to generate some code containing #[cfg(feature = "...")]. 

This seems to be a corner-case of a bug that results in code guarded by a feature not being compiled when it, according to my understanding, should be.

### Steps

To illustrate I've constructed an example consisting of three crates. A main crate and two dependencies `dependency_a` and `dependency_b`. Both dependencies have a feature, one enables the other.

## Main application that fails to compile

Cargo.toml:
```toml
[package]
name = "fail_to_resolve"
version = "0.1.0"
edition = "2021"

[features]
# This should work (according to my understanding):
foo = ["dependency_a/foo"]

# This works
#foo = ["dependency_a/foo", "dependency_b/foo"]

[dependencies]
dependency_a = { path = "dependencies/dependency-a" }
dependency_b = { path = "dependencies/dependency-b" }
```

src/main.rs:
```rust
use dependency_a::my_macro;

#[my_macro]
fn test() {}

pub fn main() {
    created_function();
}
```

## Dependency A
dependencies/dependency-a/Cargo.toml:
```toml
[package]
name = "dependency_a"
version = "0.1.0"
edition = "2021"

[features]
foo = ["dependency_b/foo"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

dependency_b = { path = "../dependency-b" }
```

src/lib.rs:
```rust
#![recursion_limit = "128"]
extern crate proc_macro;
extern crate proc_macro2;

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;

#[macro_use]
extern crate quote;

#[proc_macro_attribute]
pub fn my_macro(_attrs: TokenStream, _input: TokenStream) -> TokenStream {
    let  result: TokenStream2 = quote! {
        #[cfg(feature = "foo")]
        pub fn created_function() {
            dependency_b::run_this_b();
        }
    };

    result.into()
}
```

## Dependency B

dependencies/dependency-b/Cargo.toml:
```toml
[package]
name = "dependency_b"
version = "0.1.0"
edition = "2021"

[features]
foo = []

[lib]

[dependencies]
```

dependencies/dependency-b/src/lib.rs:

```rust
#[cfg(feature = "foo")]
pub fn run_this_b() {}
```

## Reproducing

1. Download zip with example: [cargo-feature-resolving-fail.zip](https://github.com/rust-lang/cargo/files/7941361/cargo-feature-resolving-fail.zip)
2. Run `cargo test --features foo`

The error message I get is:
```text
error[E0425]: cannot find function `run_this_b` in crate `dependency_b`
 --> src/main.rs:3:1
  |
3 | #[my_macro]
  | ^^^^^^^^^^^ not found in `dependency_b`
  |
  = note: this error originates in the attribute macro `my_macro` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Possible Solution(s)

I can work around it for now by adding `foo = ["dependency_a/foo", "dependency_b/foo"]` to the features list.

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```
