### ISSUE TITLE
Cargo patch ignores gitlab ssh urls 

### ISSUE THREAD

**Issue by natekc** [rust-lang/cargo#10467]
### Problem

Cargo ignores gitlab patch URLs (Ex. `ssh://git@gitlab.xyz.com:2222/project/repo.git`) in the cargo home config. 

### Steps

1. In the project Cargo.toml, add a dependency with a git repo source, such as 
```toml
mydep = { git = "ssh://git@gitlab.xyz.com:2222/project/repo.git"  }
```
2. In $CARGO_HOME/config, add the following patch section
```toml
[patch."ssh://git@gitlab.xyz.com:2222/project/repo.git"]
mydep = { path = "mydep" }
```
3. Run any cargo command
```bash
cargo update
```
4. Cargo uses git URL instead of patch path.

### Possible Solution(s)

If extra slashes are added to the gitlab URL (Ex. `ssh://git@gitlab.xyz.com:2222/project///repo.git`), the patch URL is recognized and cargo patches the original source as expected.

### Version

```text
1.58.1
```
