### ISSUE TITLE
The same crate with different features

### ISSUE THREAD

**Issue by uuhan** [rust-lang/cargo#10489]
### Problem

```toml
[package]
name = "test-features"
version = "0.1.0"
edition = "2021"

[dependencies]
casbin = "2.0.9"
rhai = "1.5.0"
```

casbin has `rhai` as it's dependency with features:
```toml
rhai = { version = "1.5.0", features = [
  "sync",
  "only_i32",
  "no_function",
  "no_float",
  "no_optimize",
  "no_module",
  "serde",
  "unchecked",
] }
```

So I can not use `rhai` **without** the feature `no_module`

### Proposed Solution

```toml
[dependencies.rhai]
version = "1.5.0"
isolated = true # maybe have this flag to use the dependency as an isolated one, so it's features does not include `no_module`

[dependencies.casbin]
version = "2.0.9" # this crate have the dependency `rhai==1.5.0` with feature `no_module` enabled.
```

**Comment by weihanglo** [comment]
I believe it's the behaviour of [feature unification], unfortunately. Cargo will use the union of features of a dependency if it appears multiple times in the dependency graph. A rule of thumb is that define features as **additive** as possible. However, `rhai` also had a hard time transiting features to additive and [here is the discussion].

The proposed solution seems straight-forward but the devil is in the details. Does `isolated` mean they are two separate dependency graph? Should cargo stop unifying their transitive dependencies as well? Personally I cannot foresee any reasonable design at the moment 🥲

As a workaround, maybe you can try to fork `rhai` and make it a different package or split the dependent into different crates, so that cargo probably won't merge them.

[feature unification]: https://doc.rust-lang.org/1.59.0/cargo/reference/features.html#feature-unification
[here is the discussion]: https://github.com/rhaiscript/rhai/issues/182

**Comment by uuhan** [comment]
> I believe it's the behaviour of [feature unification](https://doc.rust-lang.org/1.59.0/cargo/reference/features.html#feature-unification), unfortunately. Cargo will use the union of features of a dependency if it appears multiple times in the dependency graph. A rule of thumb is that define features as **additive** as possible. However, `rhai` also had a hard time transiting features to additive and [here is the discussion](https://github.com/rhaiscript/rhai/issues/182).
> 
> The proposed solution seems straight-forward but the devil is in the details. Does `isolated` mean they are two separate dependency graph? Should cargo stop unifying their transitive dependencies as well? Personally I cannot foresee any reasonable design at the moment 🥲
> 
> As a workaround, maybe you can try to fork `rhai` and make it a different package or split the dependent into different crates, so that cargo probably won't merge them.

Currently, I just fork the `rhai` package and rename it to other name. It works, but, emmm, very unconfortable.

I wonder if the `package` feature maybe extended to satisify this need, like this:

```toml
[dependency.my-rhai]
package = "rhai"
version = "1.5.0"
features = ["sync"]
```

If all the package info of `rhai` is bound to the new package name `my-rhai`, and can not be affected by `casbin`'s dependency. But it seems currently the usage of `package = "rhai"` just alias the crate name, not keeps the `features` isolated.
