### ISSUE TITLE
Faster build upto 5x using defaults in Cargo.toml

### ISSUE THREAD

**Issue by rrjanbiah** [rust-lang/cargo#10601]
### Problem

When https://github.com/dimensionhq/fleet claimed to be [5x faster than Cargo](https://news.ycombinator.com/item?id=31132659), [vladvasiliu](https://news.ycombinator.com/item?id=31135259) in HN mentioned some defaults that can be added in the `Cargo.toml` for the same performance improvement:

```toml
[build]
rustc-wrapper = "/usr/bin/sccache"
 
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
```

### Proposed Solution

If that's true, please add above defaults in `Cargo.toml`
