### ISSUE TITLE
Invalid `vendor` path example

### ISSUE THREAD

**Issue by Zymlex** [rust-lang/cargo#10652]
### Problem

On Windows, when specifying a path with a backslash:
```bat
cargo vendor "deps\.third_party" --versioned-dirs
```
the `vendor` also suggest a path with a backslash:
```toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = 'deps\.third_party'
```
but this is not valid path for cargo.

### Version

```text
cargo 1.62.0-nightly (a44758ac8 2022-05-04)
release: 1.62.0-nightly
commit-hash: a44758ac805600edbb6ba51e7e6fb81a6077c0cd
commit-date: 2022-05-04
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.17763 (Windows Server 2019) [64-bit]
```
