### ISSUE TITLE
Crate version missing based on compiler version

### ISSUE THREAD

**Issue by xNxExOx** [rust-lang/cargo#10688]
### Problem

```error
error: failed to select a version for the requirement `egui = "^0.18"`
candidate versions found which didn't match: 0.17.0, 0.16.1, 0.16.0, ...
```
```toml
egui = { version = "0.18", optional = true }
egui_glium = { version = "0.18", optional = true }
glium = { version = "0.31", optional = true }
egui_demo_lib = { version = "0.18", optional = true, features = ["serde"] }
clipboard-win = { version = "4", optional = true }
```
but versions 0.18.0 and 0.18.1 existed at the time

### Steps

1. use rustc 1.60
2. create crate with feature that depends on the crates listed above. (egui  is probably enough, but I did not test it)
3. try to build it and it will (hopefully) fail with same error I did get

### Possible Solution(s)

I solved it by updating with rustup 
`nightly-i686-pc-windows-msvc updated - rustc 1.63.0-nightly (e6a4afc3a 2022-05-20) (from rustc 1.60.0-nightly (ee5d8d37b 2022-01-17))`

### Notes

I am not 100% sure if this is an cargo issue, because updating compiler did help, but I think that crate resolution trough `Cargo.toml` is part of cargo, and did not find any about missing crate version in either issues.

I have no easy way to test it (deleting rust and downloading another version for 30 minutes is not a good option).

To be clear failing is not an issue, but the error message is. If the message would say that newer rustc version is required, instead of crate version not found it would be clear what is going on.

I found out about the upgrade by trying version 0.17 which by the error message exist, and have the change I wanted, and then compilation failed saying one of crates needs at least rustc 1.61, without that I would not even think about updating, because I did not see any interesting feature in the release notes. And after updating I tried if the version 0.18 did exist, and it did.

Please let me know if it is rustc bug, and I should report it there.

### Version

```text
cargo 1.60.0-nightly (06b9d3174 2022-01-11)
release: 1.60.0-nightly
commit-hash: 06b9d31743210b788b130c8a484c2838afa6fc27
commit-date: 2022-01-11
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
```
