### ISSUE TITLE
cargo run/cargo build not obeying cargo/config.toml or rust-toolchain.toml build target

### ISSUE THREAD

**Issue by brandonros** [rust-lang/cargo#10743]
### Problem

I set

```toml
[build]
target = "i686-pc-windows-msvc"
```

in `cargo/config` (also tried `cargo/config.toml`)

I run `cargo run`

It spits out a `bin` made with the `x86_64-pc-windows-msvc` triple instead

Cargo.toml

```toml
[package]
name = "foo"
version = "0.0.1"
edition = "2018"

[dependencies]
minidl = "0.1"
winapi = { version = "0.3.9", features = ["libloaderapi", "unknwnbase", "wbemcli", "oaidl"] }
detour = "0.8.1"
smbios-lib = "0.9.0"

[[bin]]
name = "foo"
path = "main.rs"
```

I even tried `rust-toolchain.toml` in conjunction with both `cargo/confg` and `cargo/config.toml`

```toml
[toolchain]
channel = "nightly"
targets = ["i686-pc-windows-msvc"]
```

`target/debug/foo.exe` still ends up being a 64-bit .exe

I have to manually specify `cargo run --target i686-pc-windows-msvc` every time

I believe `cargo build` is also building a `x86_64-pc-windows-msvc` binary in `target\debug` instead of an `i686` binary like requested

### Notes

> rustup toolchain list
stable-i686-pc-windows-gnu
stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
nightly-i686-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (override)

### Version

```text
C:\Users\Brandon\Desktop\foo>cargo version --verbose
cargo 1.63.0-nightly (85e457e15 2022-06-07)
release: 1.63.0-nightly
commit-hash: 85e457e158db216a2938d51bc3b617a5a7fe6015
commit-date: 2022-06-07
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
```
