### ISSUE TITLE
Syntax highlighting for more languages

### ISSUE THREAD

**Issue by s0lst1ce** [rust-lang/cargo#10759]
### Problem

As of today only rust code block have syntax highlighting in doc-comments.

### Proposed Solution

I think it would be great if there was support for syntax highlighting for other languages.

### Notes

I'm asking this after I've provided an example settings toml file in crate-level doc so that users of the crate could know how to format it directly. However not having syntax highlighting sorts of reduces the benefits as you can see below.
Without: 
```
[lbc]
annonces = 5000
annonce = 10000

[filters]
refresh_rate = 1
deps = [34]
kind = 'particulier'
category = 'vente'
```
With:
```toml
[lbc]
annonces = 5000
annonce = 10000

[filters]
refresh_rate = 1
deps = [34]
kind = 'particulier'
category = 'vente'
```
