### ISSUE TITLE
Let the user set a default VCS ignore file with cargo init/new

### ISSUE THREAD

**Issue by ValentinColin** [rust-lang/cargo#10795]
### Problem

I like the idea of having a git file in my new projects, however the one currently produced by cargo is severely lacking in customization.

### Proposed Solution

# Solution 1
I propose to add these options in the config.toml of cargo:
```toml
[cargo-new]
vcs-ignore-file = "path/to/default/.<vcs>ignore" # default: "" to let cargo write it himself (as it's now)
```
And cargo have only to copy/paste the file

# Solution 2
To go further!
Having one default directory create by the user himself 
```toml
[cargo-new]
template-folder = "path/to/template/folder/" # default: "" to let cargo write it by himself (as it's now)
```

# Solution 3
To go even further!
We could create a set of default directories that we could choose with an option.
With a `.cargo/templates/` folder for example:
```
.cargo/templates/
 ├─ default/
 │   ├─ src/main.rs
 │   ├─ .gitignore
 │   └─ Cargo.toml
 ├─ github/
 │   ├─ .github/workflows/fmt.yml
 │   ├─ src/main.rs
 │   ├─ .gitignore
 │   └─ Cargo.toml
 └─ ...
```
```zsh
cargo new <project-name> --template "path/to/template/folder/"
# or
cargo new <project-name> --template github # Cargo could automatically search the folder 'github' in .cargo/templates/
```

Or something like that :smiley:
