### ISSUE TITLE
Building for host architecture and then another target invalidates cache

### ISSUE THREAD

**Issue by skittles1412** [rust-lang/cargo#10839]
### Problem

1. Run `cargo build` and wait for the build to finish
2. Run `cargo build --target <target triple>` for a few seconds
3. Run `cargo build` again, the build restarts from scratch

I would expect step 3 to not rebuild from scratch and instead use the cached artifacts produced in step 1.

### Version

```text
cargo 1.62.0 (a748cf5a3 2022-06-08)
release: 1.62.0
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report!  Can you please provide a complete reproduction? That shouldn't happen, and I'm unable to reproduce it with a typical project.

**Comment by skittles1412** [comment]
In my .cargo/config.toml I have:
```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang" 
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
```
Without the above cargo works as expected. A simpler version of the config.toml would be something like:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-O"]
```

Also I should mention that `cargo build --target x86_64-unknown-linux-gnu` (my host) instead of `cargo build` caches with other targets.
