### ISSUE TITLE
Cross-compiling with `clang` and `mold` failed with unrecognized option '-dynamic'

### ISSUE THREAD

**Issue by inflation** [rust-lang/cargo#10863]
### Problem

Issues first filed here: https://github.com/rui314/mold/issues/564

I'd like to cross-compile a rust project from `aarch64-apple-darwin` to `x86_64-unknown-linux-gnu` with these settings:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-Clink-arg=-fuse-ld=/opt/homebrew/bin/ld.mold",
  "-Clink-arg=--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"]
```

But if failed with unrecognized option:
```bash
unrecognized option '-dynamic'
```
However, the linker command emitted doesn't show `-dynamic` but `-Wl,-Bdynamic`:
```bash
 "cc" "-m64"
 ...
"-Wl,--as-needed" 
"-L" "/private/tmp/testing/target/x86_64-unknown-linux-gnu/debug/deps"
"-L" "/private/tmp/testing/target/debug/deps" 
"-L" "/Users/inflation/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
"-Wl,--start-group" "-Wl,-Bstatic" 
...
"-Wl,--end-group" 
"/Users/inflation/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-377835cfab8dae0d.rlib" 
"-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" 
"-L" "/Users/inflation/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
"-o" "/private/tmp/testing/target/x86_64-unknown-linux-gnu/debug/deps/testing-c379b9730434cd22" 
"-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" 
"-fuse-ld=/opt/homebrew/bin/ld.mold" "--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"
```

Further investigation shows that it's not only affecting mold, but also `ld.lld` from `llvm` and `x86_64-unknown-linux-gnu-ld` from the cross-compilation toolchain.

### Steps

0. Download a cross-compiling toolchain or use `crosstool-ng`
1. `cargo new testing`
2. `cd testing && mkdir .cargo`
3. For `mold`: 
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-Clink-arg=-fuse-ld=/opt/homebrew/bin/ld.mold",
  "-Clink-arg=--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"]
```
For `x86_64-unknown-linux-gnu-ld`:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-Clink-arg=-fuse-ld=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld",
  "-Clink-arg=--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"]
```
For `ld.lld`:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld.lld",
  "-Clink-arg=--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"]
```
4. `cargo build --target=x86_64-unknown-linux-gnu` and fail

### Possible Solution(s)

So, I guess if the linker is `clang` on macOS, regardless of what target it is, it always passes linker options in `ld64` forms somehow.

### Notes

Setting `x86_64-unknown-linux-gnu-gcc` as the linker and using `mold` or `lld` is fine:
```bash
ln -s /opt/homebrew/bin/ld.mold /Volumes/CSP/x-tools/aarch64-linux-gnu/aarch64-linux-gnu/bin/ld
```
```toml
[target.aarch64-unknown-linux-gnu]
linker = "/Volumes/CSP/x-tools/aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc"
```

### Version

```text
cargo 1.62.0 (a748cf5a3 2022-06-08)
release: 1.62.0
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.4.0 [64-bit]
```
