### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by P1start** [rust-lang/cargo#1091]
It would be nice if it were possible to set up aliases in `.cargo/config`; e.g.,

```toml
[alias]
b = "build"
t = "test"
rr = "run --release"
# etc.
```
