### ISSUE TITLE
`Authorization` Header is missing on `cargo build` for private registries

### ISSUE THREAD

**Issue by sassman** [rust-lang/cargo#10920]
## Given
- I have a private package registry (in my case it is a artifactory from jfrog)
- And I have configured it via `<project_root>/.cargo/config` like this:
  ```toml
  [registries.my-crates]
  index = "https://myorg.jfrog.io/artifactory/git/my-crates.git"
  
  [net]
  git-fetch-with-cli = true
  ```
- Assuming I have already published `my-crate` at version `0.1.1` (because this works already well)
- And I got a package dependency specified in my `Cargo.toml` with a `registry` property like:
  ```toml
  [dependencies]
  my-crate = { version = "0.1.1", registry = "my-crates" }
  ```
- And I got a token in my `~/.cargo/credentials.toml` for exactly this registry like:
  ```toml
  [registries.my-crates]
  token = "Bearer XXXX"
  ```

## Then
- I would expect that `cargo build` downloads `my-crate` with using the `token` specified in the `credentials.toml`

### Steps

1. create a private repository
2. create the project config as above
3. create an auth token as above
4. configure the auth token via `cargo login` or as said above
5. specify a dependency in a new project with explicitly stating the `registry` property (see above)
6. call `cargo build`

### Possible Solution(s)

IMO it would be most consitent that cargo under the given circumstances uses an `Authorization` header for `build` and download. 
As it is doing it already correctly for the `publish` sub-command

Alternatively in the project `.cargo/config` one option might activate the desired behavior, maybe on the `[net]` config section.

### Version

```text
`cargo 1.63.0-nightly (38472bc19 2022-05-31)`
```
