### ISSUE TITLE
Improve error message displayed when a string is used instead of an array for 'authors' in the manifest

### ISSUE THREAD

**Issue by ptdecker** [rust-lang/cargo#10942]
### Problem

Currently, if one uses a string instead of an array of strings as the value for the `authors` field an error message is displayed which is not helpful for a new Rust developer to identify the cause of the problem.

Example of an incorrect `Cargo.toml`:

```toml
[package]
name = "alenandbarb"
version = "0.1.0"
edition = "2021"
authors = "Todd Decker"
description = "A toy application for crustatian exploration along network and applications seafloor"

[features]
desktop = ["dioxus/desktop"]
web = ["dioxus/web"]

[dependencies]
dioxus = "0.2.4"
```

The error message displayed is:

```
Execution failed (exit code 101).
/Users/ptdecker/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features
stdout : error: failed to parse manifest at `/Users/ptdecker/CLionProjects/alenandbarb/Cargo.toml`

Caused by:
  data did not match any variant of untagged enum MaybeWorkspace for key `package.authors`

stderr : 
```

### Proposed Solution

An error message along the lines of the below would be more informative:

```
Execution failed (exit code 101).
/Users/ptdecker/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features
stdout : error: failed to parse manifest at `/Users/ptdecker/CLionProjects/alenandbarb/Cargo.toml`

Caused by:
  value of `package.authors` is a string, while an array was expected

stderr : 
```

### Notes

I also submitted the PR below to update the Cargo documentation to better explain the requirements of the field:

[https://github.com/rust-lang/cargo/pull/10938](https://github.com/rust-lang/cargo/pull/10938)

@epage saw my post on the forum about my problem ([link](https://users.rust-lang.org/t/compile-error-when-adding-authors-to-cargo-toml/79383/6)) and suggested that I also submit an issue to improve the error message itself.

Thank you

P. Todd Decker

**Comment by hi-rustin** [comment]
For now, I think it's challenging to improve it because the internal error will ignore by MaybeWorkspace.
Also, `publish: Option<MaybeWorkspace<VecStringOrBool>>` affect by it, you can not get the VecStringOrBool inner error.

```toml
[package]
name = "cargo"
version = "0.65.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "https://docs.rs/cargo"
readme = "README.md"
description = """
Cargo, a package manager for Rust.
"""
publish = "a"

```
```log
➜  cargo git:(master) ✗ ./target/debug/cargo test
error: failed to parse manifest at `/Users/rustin/ClionProjects/cargo/Cargo.toml`

Caused by:
  data did not match any variant of untagged enum MaybeWorkspace for key `package.publish`
```

It should be `invalid type: string "a", expected a boolean or vector of strings`.

See more: https://github.com/serde-rs/serde/pull/1544.

@epage Do you have any thoughts about how to work around it?
