### ISSUE TITLE
A top-level root profile for overriding dev and release profiles simultaneously

### ISSUE THREAD

**Issue by bstrie** [rust-lang/cargo#10953]
### Problem

Currently, if you have some profile that needs to always apply regardless of whether the crate is being built in release mode or not, you're required to specify the options twice, once for dev mode and once for release mode:

```toml
# rustflags specified via the unstable profile-rustflags option
[profile.dev.package.aes]
# use software implementation
rustflags = ["--cfg", "aes_force_soft"]

[profile.release.package.aes]
# use software implementation
rustflags = ["--cfg", "aes_force_soft"]
```

### Proposed Solution

Since profile inheritance is already a concept, it would be nice if the `dev` and `release` profiles inherited from a `root` profile so that both `dev` and `release` could be overridden together:

```toml
# rustflags specified via the unstable profile-rustflags option
[profile.root.package.aes]
# use software implementation
rustflags = ["--cfg", "aes_force_soft"]
```

### Notes

According to the Zulip thread here: https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/profile.20wildcards/near/281732406 , the name "root" is already reserved for this purpose.
