### ISSUE TITLE
Error message unclear for fields with wrong toml type where workspace inheritance is supported

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#10997]
# Problem

Manifest
```toml
[package]
name = "alenandbarb"
version = 1
edition = "2021"
description = "A toy application for crustatian exploration along network and applications seafloor"

[features]
desktop = ["dioxus/desktop"]
web = ["dioxus/web"]

[dependencies]
dioxus = "0.2.4"
```

Error
```
Execution failed (exit code 101).
/Users/ptdecker/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features
stdout : error: failed to parse manifest at `/Users/ptdecker/CLionProjects/alenandbarb/Cargo.toml`

Caused by:
  data did not match any variant of untagged enum MaybeWorkspace for key `package.version`

stderr : 
```

Note: This is a broader issue of #10942 which was resolved with #10944
