### ISSUE TITLE
`inherits` cannot be used in root profiles `dev` and `release`

### ISSUE THREAD

**Issue by Zymlex** [rust-lang/cargo#11016]
### Problem

`inherits` cannot be used in root profiles:

```
`inherits` is required for all profiles except `dev` or `release`
`inherits` must not be specified in root profile `dev`
`inherits` must not be specified in root profile `release`
```

```toml
[profile.dev]
inherits = "all"

[profile.release]
inherits = "all"

[profile.all]
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
# parameters
```

### Possible Solution(s)

Allow inheritance for root profiles.

### Version

```text
cargo 1.65.0-nightly (9809f8ff3 2022-08-16)
release: 1.65.0-nightly
commit-hash: 9809f8ff33c2b998919fd0432c626f0f7323697a
commit-date: 2022-08-16
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.17763 (Windows Server 2019) [64-bit]
```
