### ISSUE TITLE
Add a configuration to Cargo.toml to specify which git submodules have to be fetched

### ISSUE THREAD

**Issue by sdroege** [rust-lang/cargo#11048]
### Problem

In [gtk-rs](https://github.com/gtk-rs/gtk-rs-core) we have various git submodules that are only necessary for running the code generator. That is, they're not necessary for compiling the crates inside the repository.

If a crate currently depends on a git version of gtk-rs then cargo will download all those (not very small) git submodules too, unnecessarily.

That it downloads all git submodules currently as a default seems like reasonable behaviour as they might be required for building the crates, but it's not optimal in all cases.

### Proposed Solution

Something like the following in `Cargo.toml` for the repository example above

```toml
[package.metadata.git.submodules.gir]
fetch = false

[package.metadata.git.submodules.gir-files]
fetch = false
```

For backwards compatibility reasons this would obviously default to `fetch = true`.
