### ISSUE TITLE
Declaring a build-dependeny and a dependency on the same crate cause a crate not found exception in build.rs

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang/cargo#1132]
```toml
[package]
# stuff
build = "build.rs"

[build-dependencies.xyz]
git = "https://github.com/xyz/xyz.git"

[dependencies.xyz]
git = "https://github.com/xyz/xyz.git"
```

Caused ```extern crate 'xyz'``` not found in build.rs.

If I remove the `[dependencies.xyz]` declaration, both build.rs and the crate build correctly.  According to the docs, for a build dependency to be included in the crate build it had to be declared explicitly.
