### ISSUE TITLE
Conditional compilation of workspace members via features

### ISSUE THREAD

**Issue by IsaccBarker** [rust-lang/cargo#11526]
### Problem

I'm writing a kernel and I want to split out `x86` and `x86_64` specific code, so I can publish it to crates.io and possible use it in another project. Best way I can think to do this is through workspaces. However, when compiling my kernel, I don't want to compile the `x86` crate, when, for example, building for aarch64 or RISC-V. I'm currently doing something like the below:

```rust
// src/lib.rs

#![no_std]
#[cfg(target_arch = "x86")]
mod x86;
#[cfg(target_arch = "x86")]
pub use x86::*;
````

This obviously isn't optimal. Similar to #5220?

### Proposed Solution

I would propose something like below:

```toml
[workspace]
members = [
    "<kernel_name>",
]

[workspace.'cfg(feature = "x86")']
members = [
    "<x86 crate>"
]
```

or

```toml
[workspace]
members = [
    "<kernel_name>",
    "feature.x86:<x86 crate>"
]
```

or something to that affect.

### Notes

_No response (yet, haha!)_

**Comment by weihanglo** [comment]
Thank you for proposing this feature! Personally, I've got questions on this proposal: 

- `cfg(feature = "…")` are never a thing even in a non-workspace `Cargo.toml` manifest. Will it confuse people that `workspace` supports `cfg(feature = …)` whereas others are not? Or does it imply we need find a way to support them all (which is unlikely in the near feature)?
- Where are those "workspace features" defined? What does that mean when comparing to package features? Will package's default features affect workspace features?
- Having "workspace features" means a developer need to specify in via command line, probably as `cargo build --workspace --features x86`. It feels a bit lengthy. [`libc`](https://github.com/rust-lang/libc/blob/72fba0ecc76bf385d8f7b687fa8e46a1f6c0ae43/src/lib.rs) depends on target `cfg`, which is auto-detected by rustc without any user interaction. What's the technical problem on this solution to you?

I am not entirely understand your use case. Looks like #5220 can cover it. Could you share more on that?

**Comment by IsaccBarker** [comment]
Thanks for your response, sorry this isn't so timely.

I must have not been thinking very clearly when I wrote that example! Maybe something like this could avoid "workspace features".

```toml
# /Cargo.toml
[workspace]
members = [
    "foo"
]

# /foo/Cargo.toml
# ...
[dependencies]
bar = {version = "0.1.0", path = "../bar", optional = true}

[features]
bar = ["dep:bar", "workspace_member:bar"]
# ...

# /bar/Cargo.toml
# ...
```

Which achieves bar only being compiled and linked in if foo has the "bar" feature specified. It's inline with how you might have a feature depend on a dependency like `bar = ["dep:bar"]`.

Sorry it wasn't initially clear :)
