### ISSUE TITLE
regression with multiple registries error

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#11524]
### Problem

@dasbard [reported](https://github.com/rust-lang/cargo/pull/10592/files/9827412fee4f5a88ac85e013edd954b2b63f399b#r1059159731) that they were using an alias for a registry where two registry definitions had the same index. Starting with #10592, this is now not allowed. I don't think we anticipated users having such a configuration, so we should consider if we can avoid this regression. This results in the error:

```
error: multiple registries are configured with the same index url 'registry+https://…': bar, foo
```

### Steps

Set up a configuration with two registries with the same value:

```toml
[registries.foo]
index = "https://github.com/rust-lang/crates.io-index.git"

[registries.bar]
index = "https://github.com/rust-lang/crates.io-index.git"
```

### Possible Solution(s)

@arlosi Do you have any ideas if we can avoid an error in this situation?

### Version

```text
cargo 1.68.0-nightly (70898e522 2022-12-05)
release: 1.68.0-nightly
commit-hash: 70898e522116f6c23971e2a554b2dc85fd4c84cd
commit-date: 2022-12-05
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.79.1 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```
