### ISSUE TITLE
Global `cargo-features`

### ISSUE THREAD

**Issue by Flippette** [rust-lang/cargo#11552]
### Problem

Currently it's not possible as far as I'm aware of to use `cargo-features` in `$CARGO_HOME/config.toml`, even when using a nightly build. Am I missing something?

**Comment by weihanglo** [comment]
AFAIK, that is intentional. `cargo-features` is for enabling `Cargo.toml` extensions for a certain `Cargo.toml`, whereas a `config.toml` is more like an environment setting. This is documented in ["Unstable Features"](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html) chapter in The Cargo Book.

I'd like to know which feature you want to use but is blocked. Having a more specific example may help. Thank you.

**Comment by Flippette** [comment]
I wanted to do something similar to this:

```toml
cargo-features = ["profile-rustflags", "codegen-backend"]

[profile.dev]
codegen-backend = "cranelift"

[profile.rel_local]
inherits = "release"
rustflags = ["-Ctarget-cpu=native"]
```
