### ISSUE TITLE
Patching git dependencies with path does not work for workspace libs

### ISSUE THREAD

**Issue by CPerezz** [rust-lang/cargo#11587]
I would appreciate some help to verify that this isn't my fault or indeed what I try to do is not possible.

I have my LibA(which is a workspace), which has LibB as dependency. LibB is also a workspace, and has several members, all of which are imported in several LibA packages as:
```toml
LibBPkg0 = { git = "LibBGitURL", tag = "v2022_09_09" }
LibBPkg1 =       { git = "LibBGitURL", tag = "v2022_09_09" }
LibBPkg2 =  { git = "LibBGitURL", tag = "v2022_09_09" }
LibBPkg3 =   { git = "LibBGitURL", tag = "v2022_09_09" }
```
Then, I want to override this tag and work with my local version of LibB in LibA.

To do so, I go to the Virtual Manifest of LibA and place:
```toml
[patch."LibBGitURL.git"]
LibB = { path = "../LibB" }
```

This throws the error:
```
error: failed to load source for dependency `LibB`

Caused by:
  Unable to update path/to/LibB

Caused by:
  found a virtual manifest at `path/to/LibB/Cargo.toml` instead of a package manifest
```

If I try to point directly to a LibB Package so that we point to a package manifest, I need to do it for all LibB members, so it looks like:
```toml
[patch."LibBGitURL".git"]
LibBPkg1 = { path = "../LibB/Pkg1" }
[patch."LibBGitURL".git"]
LibBPkg2 = { path = "../LibB/Pkg2" }
[patch."LibBGitURL".git"]
LibBPkg3 = { path = "../LibB/Pkg3" }
[patch."LibBGitURL".git"]
LibBPkg4 = { path = "../LibB/Pkg4" }
```

But then it errors due to duplicate keys. See:
```
error: failed to parse manifest at `/path/to/LibA/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  TOML parse error at line 25, column 1
     |
  25 | [patch."LibBGitURL".git"]
     | ^
  Duplicate key `"LibBGitURL"` in table `patch`

  While parsing a Table Header

```

Is it possible that there's no way to do what I'm trying to?

**Comment by ehuss** [comment]
I think each package should be listed in just a single table:

```toml
[patch."LibBGitURL".git"]
LibBPkg1 = { path = "../LibB/Pkg1" }
LibBPkg2 = { path = "../LibB/Pkg2" }
LibBPkg3 = { path = "../LibB/Pkg3" }
LibBPkg4 = { path = "../LibB/Pkg4" }
```
