### ISSUE TITLE
Cargo cannot resolve version of crate when including a different crate

### ISSUE THREAD

**Issue by shelbyd** [rust-lang/cargo#11607]
### Problem

The following `Cargo.toml` cannot resolve a version of a dependency:

```toml
[package]
name = "dependency-resolution"
version = "0.1.0"
edition = "2021"

[dependencies]
# Builds with this commented out.
fastcrypto = "0.1.2"

solana-client = "1.14.5"
solana-sdk = "1.14.5"

[patch.crates-io]
curve25519-dalek = { git = "https://github.com/shelbyd/curve25519-dalek", branch = "zeroize-patch" }
```

Removing the `fastcrypto` dependency compiles successfully. Cargo gives no indication how I might resolve this issue.

### Steps

`cargo build` a minimal project with the provided `Cargo.toml`.

### Version

```text
cargo 1.65.0 (4bc8f24d3 2022-10-20)
release: 1.65.0
commit-hash: 4bc8f24d3e899462e43621aab981f6383a370365
commit-date: 2022-10-20
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Pop!_OS 22.04 (jammy) [64-bit]
```
