### ISSUE TITLE
Cargo publish times out without failure

### ISSUE THREAD

**Issue by tbrezot** [rust-lang/cargo#11616]
### Problem

When trying to publish a crate, we recently experienced an issue reported [here](https://github.com/rust-lang/crates.io/issues/5979). The command `cargo publish` timed out without returning an error.

### Steps

This may be not repeatable without hacking the `cargo publish` network communication. Our guess is that the `crates.io` server is currently experiencing some issue.

There is the GitHub CI recepee that failed (problem occurs on the `cargo publish --token $CRATES_IO` part):
```
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debug
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v1

      - name: Publishing - dry run
        if: inputs.publish == false
        run: |
          cargo publish --dry-run
      - name: Publishing
        if: inputs.publish == true
        run: |
          echo "[registry]" > ~/.cargo/credentials
          echo "token = \"$CRATES_IO\"" >> ~/.cargo/credentials
          cargo publish --token $CRATES_IO
        env:
          CRATES_IO: ${{ secrets.CRATES_IO }}

      - name: Release
        if: inputs.publish == true
        uses: softprops/action-gh-release@v1
```

Below is the screenshot of a local attempt to run `cargo publish --allow-dirty`.

![image](https://user-images.githubusercontent.com/87476144/214032419-f8d7b9f3-43e5-4473-904b-42bdc8692ea5.png)

### Possible Solution(s)

Return with an error upon time out.

### Version

```text
cargo 1.68.0-nightly (985d561f0 2023-01-20)
release: 1.68.0-nightly
commit-hash: 985d561f0bb9b76ec043a2b12511790ec7a2b954
commit-date: 2023-01-20
host: x86_64-unknown-linux-gnu
libgit2: 1.5.1 (sys:0.16.1 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.10 (kinetic) [64-bit]
```
```
