### ISSUE TITLE
Everything is always rebuilding on CI (fingerprinting)

### ISSUE THREAD

**Issue by FredrikNoren** [rust-lang/cargo#11706]
I've been trying to debug why our CI builds are so slow, and I noticed that all crates in a workspace were always rebuilt on our CI, even though we do caching of the target directory.

I found this issue and tried running a test CI project with `CARGO_LOG=cargo::core::compiler::fingerprint=info`, and it seems like it  always thinks the files are newer than when created, which makes sense since they were just cloned in.

So my question/request is; can I somehow fingerprint based on the _contents_ of the files instead of their timestamp?

**Comment by Eh2406** [comment]
Closing as a duplicate of #6529

**Comment by FredrikNoren** [comment]
@Eh2406 So that seems like it could be one solution, but until that lands, perhaps it would be good to come up with some solution for CI's with what's currently available? The problem in general is that it seems like a "basic" setup on CI just rebuilds all code in the repo each time.

I've been playing around with `git-restore-mtime`, which I was hoping would fix this but for some reason it doesn't seem to quite enough. Not sure if it's because the cache restoration doesn't write the right timestamps or what is going on exactly. I was hoping perhaps someone else has tried this before?

Here's a simple github actions ci that I was hoping would work but doesn't seem to;
```yml
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Leafwing-Studios/cargo-cache@v1
      - run: CARGO_LOG=cargo::core::compiler::fingerprint=info cargo test --workspace --release
```
