### ISSUE TITLE
Needed: Environment variable to detect target build type BUILD_TARGET

### ISSUE THREAD

**Issue by PRTGC** [rust-lang/cargo#11714]
### Problem

When there is a build script for a project(crate) it will get compiled and executed.

In my case I have several project that has dual targets [lib] and [[bin]].
```toml
...
[lib]
crate-type = ["cdylib"]
name = "xyzlib"
path = "src/lib.rs"

[lib]
crate-type = ["rlib"]
name = "rlibxyz"
path = "src/lib.rs"

[[bin]]
name = "xyz"
path = "src/main.rs"
...
```
When the exe/dll is compiled for windows, I need to add in resources (Text/ Icons / etc) 

When it is compiled as a lib, the resource file is still included which causes problems with linking.
Since it introduces duplicate resource name/ID's

Since there is no easy way(that I have found) to figure out what kind of build it is.
I had to revert to writing a scrip that creates and removes the build.rs file

### Proposed Solution

The goal is to be able to detect build target type at compile-time.
Specifically in the Build script (build.rs).

In order to determine if I need to build resources for the target,
I need to be able to detect if it is building the bin/lib/rlib/etc..

```rust
#[cfg(windows)]
pub fn build_resource () {


    #[cfg(crate-type = "bin",crate-type = "cdylib")]
    if Ok("release".to_owned()) == std::env::var("PROFILE")  {
        // Build resources only when the target is an Windows DLL or EXE
        let mut res = winres::WindowsResource::new();
        res.set_icon("../libs/myicon.ico")
            ;
        if let Err(e) = res.compile() {
            eprintln!("{}", e);
            std::process::exit(1);
        } 
    }
   #[cfg(cdylib)]
   {  // build other things for a library
   }
   #[cfg(rlib)]
   {  // build other things for a rlib
   }
}
```
Alternatively, a 'CARGO_CFG_TARGET_CRATE_TYPE' env var would work..
containing whatever is contained in the 'crate-type' [bin, lib, rlib, dylib, cdylib, staticlib, and proc-macro]

According to the [Rust Language Reference](https://doc.rust-lang.org/reference/linkage.html), it is available at some point...
    --crate-type=XXX, #![crate_type = "XXX"]
But it is not during the build script(build.rs)

```rust
#[cfg(windows)]
pub fn build_resource () {

    eprintln!("What are building ???");
    #[cfg(crate_type = "bin")]
    { eprintln!("We're building a bin #[cfg]");    }
    if cfg!(crate_type = "bin")
    {    eprintln!("We're building a bin cfg!");    }
    if cfg!(crate_type = "lib")
    {    eprintln!("We're building a lib");    }
}

fn main() {
    eprintln!("And... we're building...");
    build_resource();
    eprintln!("Done building...");
 }
```
Which produces:
```
And... we're building...
What are building ???
Done building...
```

It would be awesome if these could be available during the build script as well

**Comment by ehuss** [comment]
Can you clarify what issues you are having with linking? Can you show exactly which `cargo:` instructions you are printing? There are separate `cargo:rustc-link-arg` instructions which can be used to pass link args for specific targets (binaries, libraries, examples, etc.). More information is in the [Build Scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) chapter.

Build scripts only run once for the entire package, so there is no way to pass in a particular target type.

**Comment by PRTGC** [comment]
Hi @ehuss ,
Thanks for the reply...

I'm sorry it was not clear..

My goal is to be able to detect which target(crate type) is currently being built in build.rs.

I have  several projects that include generic libraries..
- Projects
  + ProjA
  + ProjB
   + Libs
       + LibA
       + LibB
   
LibA and LibB produce both Lib and bin depending on how it is used and each have a build.rs
that include building resource files used in windows exe's and DLL's only.

```toml
[package]
name = "libX"
version = "0.2.34"
edition = "2021"
build = "build.rs"

[lib]
name = "libimplX"
path = "src/lib.rs"

[[bin]]
name = "binX"
path = "src/main.rs"
```

The build.rs produces a resource.rc and a resource.lib
Which is exactly what is wanted when it is built as a standalone executable, all works as expected.

The executable projects that include the libs, also has a build script(build.rs) that also produces
resource files(resource.rc/lib).
```toml
[package]
name = "ProjA"
version = "0.2.34"
edition = "2021"
build = "build.rs"

[[bin]]
name = "binA"
path = "src/main.rs"

[dependencies.liba]
path = "../libs/LibA"

[dependencies.libb]
path = "../libs/LibB"
```

The resulting project now has more than one resource file(resource.rc/lib) with the same entries which 
causes an error on linking, since there are duplicate resource entries.

So, the solution is to detect the build target for the  project(or crate).
You say "the build script is run once for the entire package".

Well, when the lib/crate is included as a dependency,
 the build script is run for that crate 
passing the ["crate-type = 'rlib'] for the crate is what we want...

When the lib/crate is built as a stand alone Exe/Dll from the lib directory pass in 
["crate-type = 'bin'] or ["crate-type = 'cdylib']... is what we want.

So, if that is possible, it would solve the problem nicely..
Thanks
  JR
