### ISSUE TITLE
Crate override doesn't work with lockfile generation

### ISSUE THREAD

**Issue by fxdave** [rust-lang/cargo#11833]
### Problem

I have this in my .cargo/config.toml in a monorepo project:
```toml
[patch.'ssh://git@github.com/Final-Mile/dropit-service-lib.git']
dropit-service-lib = { path = './dropit-service-lib' }
```

dropit-service-lib is a shared library in my monorepo that has also a separate git repository.

The packages uses this library the following way:
```toml
[dependencies.dropit-service-lib]
git = "ssh://git@github.com/Final-Mile/dropit-service-lib.git"
branch = "master"
```

When I run `CARGO_NET_GIT_FETCH_WITH_CLI=true cargo update --package dropit-service-lib`
Or when I delete the Cargo.lock and run `CARGO_NET_GIT_FETCH_WITH_CLI=true cargo generate-lockfile`

I get this:
```log
    Updating crates.io index
    Updating git repository `ssh://git@github.com/Final-Mile/dropit-service-lib.git`
```

And it exits without any error, but it doesn't generate the lockfile, and it doesn't update the crate.

O

### Steps

1. Create a monorepo
2. Create a lib that has a separate git repo
3. Create another rust app that uses the lib through its git URL
4. Make an override in .cargo/config.toml for that lib to use the local version
5. Test updating the version of the lib

### Possible Solution(s)

Disable the .cargo/config.toml until the update is done.

### Version

```text
cargo 1.68.0-nightly (8c460b223 2023-01-04)
release: 1.68.0-nightly
commit-hash: 8c460b2237a6359a7e3335890db8da049bdd62fc
commit-date: 2023-01-04
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```
