### ISSUE TITLE
Cargo should issue a warning when rustflags from an outer config file override rustflags from an inner config file

### ISSUE THREAD

**Issue by PoignardAzur** [rust-lang/cargo#11885]
### Problem

Let's say your have two `.cargo/config` files affecting your project:

- `$HOME/.cargo/config`
- `my_project/.cargo/config`

Let's say these config files have conflicting rustflags values:

```toml
# $HOME/.cargo/config
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "--some-flags",
]
```

```toml
# my_project/.cargo/config
[build]
rustflags = [
    "--other-flags",
]
```

In that case, the rustflags in your local file will be overwritten by the globally-set rustflags. This is coherent with [the reference](https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags), which says that `target.<triple>.rustflags` has a higher priority than `build.rustflags` and is mutually exclusive.

But it's very confusing when it happens, and it's completely different from usual cargo behavior. Usually, you expect flags you set locally to override flags in a global file.

### Proposed Solution

Ideally, the way rustflags are merged between config files should be reconsidered. In practice, it might be impossible to change it without breaking changes to people's workflow.

At the very least, a warning should be issued when such collisions do occur, so that users know that flags they've set locally are being ignored.
