### ISSUE TITLE
Confusing error message when feature depends on an optional dependency and its feature

### ISSUE THREAD

**Issue by divergentdave** [rust-lang/cargo#12111]
### Problem

I wrote a feature specification that depended on both an optional dependency, and a feature of that optional dependency, and I got a confusing error message. Deleting the `dep:...` item from the list fixed the issue, and got things working the way I wanted, but this fix wasn't apparent from the error message. Here's a minimal reproducing `Cargo.toml` file, and the resulting error message.

```toml
[package]
name = "cargo-feature-error-message"
version = "0.1.0"
edition = "2021"

[dependencies]
keccak = { version = "0.1.4", optional = true }

[features]
my_feature = ["dep:keccak", "keccak/asm"]
```

```
error: Package `cargo-feature-error-message v0.1.0 (/home/david/scratch/cargo-feature-error-message)` does not have feature `keccak`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
```

Does `keccak/asm` implicitly enable a `keccak` feature, and is that why I'm getting this message, or is this just an error handling edge case?

### Version

```text
cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```
```
