### ISSUE TITLE
Inconsistent dependency resolution between cargo run -p/run --bin on the same binary

### ISSUE THREAD

**Issue by havasd** [rust-lang/cargo#12152]
### Problem

We discovered a weird bug with cargo's dependency resolution when building a binary with a dependency A which has different features flags in different crates within the same project.

The culprit is that the following set of commands produces different binaries and are using different dependencies:
* `cargo run -p crate_a --bin crate_a` or `cargo run -p crate_a`
* `cargo run --bin crate_a`

As result it increases compile/link time of the crate.

I am expecting that the 2 commands will produce the same binary and it would use the same set of dependencies. Also in my opinion it shouldn't pull in a dependencies which are not required to build this crate and the `Cargo.toml` doesn't specify it either.

### Steps

In order to reproduce the bug please find a minimum set of cargo project below in order to reproduce this:

I will use `rust_decimal` dependency to demonstrate the behavior described above.

`/Cargo.toml`
```toml
[workspace]
resolver = "2"
members = [
    "crate_a",
    "crate_b"
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
rust_decimal = "1.29.1"
```
`/crate_a/src/main.rs`
```rust
use rust_decimal::prelude::ToPrimitive;
use rust_decimal::Decimal;

fn main() {
}
```
`/crate_a/Cargo.toml`
```toml
[package]
name = "crate_a"
version.workspace = true
edition.workspace = true

[dependencies]
rust_decimal.workspace = true
```
`/crate_b/src/main.rs`
```rust
use rust_decimal::prelude::ToPrimitive;
use rust_decimal::Decimal;

fn main() {
}
```
`/crate_b/Cargo.toml`
```toml
[package]
name = "crate_b"
version.workspace = true
edition.workspace = true

[dependencies]
rust_decimal = { workspace = true, features = ["db-diesel2-postgres"] }
```

**Note:** The `db-diesel2-postgres` feature flag will introduce a dependency on `libpq-dev` package therefore the compilation will fail. For demonstration purposes we expect the compilation to fail.

After setting up the project run:

0. Remove `libpq-dev` package in order to demonstrate the bug clearly
1. Run `cargo run -p crate_a`, we expect that the binary will be run and the compilation succeeds.
2. Run `cargo run --bin crate_a`, we expect some recompilation of additional packages because a different feature flag was selected for the `rust_decimal` dependency which is in an another crate.
3. The compilation will fail because of missing `/usr/bin/ld: cannot find -lpq: No such file or directory`

### Version

```text
cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```
