### ISSUE TITLE
rust workspace version reference generates a problem in vs code, I presume this comes from the language server

### ISSUE THREAD

**Issue by softstream-link** [rust-lang/cargo#12186]
### Problem

originally raised [here](https://github.com/toml-lang/toml/issues/976)

root toml
```toml
[workspace]
members = [byteserde]

[workspace.package]
version="0.1.1"
.....
```

byteserde toml
```toml
[package]
name = "byteserde"
version.workspace = true
```
results in this error in the Problems panel of vs code, I assume this is not a [Better Toml plugin](https://marketplace.visualstudio.com/items?itemName=bungcip.better-toml) but a language server provided error, but I am guessing here 
Expected "=", [ \t] or [A-Za-z0-9_-] but "." found.
