### ISSUE TITLE
`cargo rm` unexpectedly removes patches

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#12419]
### Problem

When I run `cargo rm dependency`, I expect Cargo to remove the crate `dependency` from the current crate's \[dependencies\], and other related necessary changes, like removing `dependency` from the right-hand side of features that previously enabled an optional dependency on "dependency" or one of its features "dependency/&hellip;".

Cargo does these things, but it also wipes out my `patch.crates-io` section from the workspace's manifest. I could not figure out how this seems related in any way to removing a single dependency, so I think this is a bug.

### Steps

```toml
# Cargo.toml

[workspace]
members = ["serde", "serde_derive"]

[patch.crates-io]
serde = { path = "serde" }
```

```toml
# serde/Cargo.toml

[package]
name = "serde"
version = "1.0.0"

[dependencies]
serde_derive = { path = "../serde_derive" }
```

```toml
# serde_derive/Cargo.toml

[package]
name = "serde_derive"
version = "1.0.0"
```

+`serde/src/lib.rs` and `serde_derive/src/lib.rs` which can be empty files.

In the `serde` directory, run:

```console
$ cargo check  # sanity check--the manifests are valid

$ cargo rm serde_derive
```

Expected diff:

```diff
diff --git a/serde/Cargo.toml b/serde/Cargo.toml
index 759de5d..10027d7 100644
--- a/serde/Cargo.toml
+++ b/serde/Cargo.toml
@@ -3,6 +3,3 @@
 [package]
 name = "serde"
 version = "1.0.0"
-
-[dependencies]
-serde_derive = { path = "../serde_derive" }
```

Actual diff produced by Cargo:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 583dd2f..60ffc4f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -2,6 +2,3 @@
 
 [workspace]
 members = ["serde", "serde_derive"]
-
-[patch.crates-io]
-serde = { path = "serde" }
diff --git a/serde/Cargo.toml b/serde/Cargo.toml
index 759de5d..10027d7 100644
--- a/serde/Cargo.toml
+++ b/serde/Cargo.toml
@@ -3,6 +3,3 @@
 [package]
 name = "serde"
 version = "1.0.0"
-
-[dependencies]
-serde_derive = { path = "../serde_derive" }
```

### Version

```text
cargo 1.73.0-nightly (7ac9416d8 2023-07-24)
release: 1.73.0-nightly
commit-hash: 7ac9416d82cd4fc5e707c9ec3574d22dff6466e5
commit-date: 2023-07-24
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by epage** [comment]
If I'm reading the reproduction steps correctly, the `serde` patch is unused.  This is from #11194.  

> Note the GC process was expanded to clean up not just references to the dependencies just removed, but also references of all dependencies. This was because there's not an easy way to determine which dependencies correspond to the given TOML keys, without either 1) figuring that out before the removal (therefore having to predict the behavior), or 2) returning that information from the remove function (somewhat unorthodox for an op).

Note that this is referencing some of the structure of cargo.  This was implemented as `remove` and `gc_workspace` functions which adds some burden for connecting the pieces (but not terribly).

This seemed ok because the chance of this seemed low and people could selecting add/revert the relevant parts.

**Comment by dtolnay** [comment]
Updated repro:

```toml
# serde/Cargo.toml

[package]
name = "serde"
version = "1.0.0"

[dependencies]
serde_derive = { path = "../serde_derive" }

[dev-dependencies]
serde_json = "=1.0.0"
```

`cargo rm serde_derive` still incorrectly removes the patch despite the patch being used.

**Before:**

```console
$ cargo tree
serde v1.0.0 (/git/repro/workspace/serde)
└── serde_derive v1.0.0 (/git/repro/workspace/serde_derive)
[dev-dependencies]
└── serde_json v1.0.0
    ├── dtoa v0.4.8
    ├── itoa v0.3.4
    ├── num-traits v0.1.43
    │   └── num-traits v0.2.16
    │       [build-dependencies]
    │       └── autocfg v1.1.0
    └── serde v1.0.0 (/git/repro/workspace/serde) (*)
```

**After:**

```console
$ cargo tree
serde v1.0.0 (/git/repro/workspace/serde)
[dev-dependencies]
└── serde_json v1.0.0
    ├── dtoa v0.4.8
    ├── itoa v0.3.4
    ├── num-traits v0.1.43
    │   └── num-traits v0.2.16
    │       [build-dependencies]
    │       └── autocfg v1.1.0
    └── serde v1.0.179
```
