### ISSUE TITLE
Cargo.toml `features` (not `[features]`) `!` syntax

### ISSUE THREAD

**Issue by gamertike** [rust-lang/cargo#12412]
### Problem

Whenever a dependency has quite a few default features and you want to only disable one of them while keeping the rest, you need to add `default-features = false` and add all the default features you still want to keep.

### Proposed Solution

To solve the above problem, `Cargo.toml` should support the `!` syntax (**only for when specifying deps, not defining `[features]`**).

Here is an example of it in action:

```toml
[package]
name = "image-processing"
version = "1.0.0"
# other fields

[features]
default = ["std", "ico", "webp"]
std = []
bmp = []
png = []
ico = ["bmp", "png"]
webp = []
```

```toml
[dependencies.image-processing]
version = "1"
# Disable `std` but keep the other default features
# current method
default-features = false
features = ["ico", "webp"]
# new method
features = ["!std"]
```

### Notes

There can also be a shortcut for `default-features = false` using `!*` or `!default`.

Here is an example:

```toml
[dependencies.image-processing]
version = "1"
# Disable all default features except `webp`
# Current method
default-features = false
features = ["webp"]
# New method
features = ["!*", "webp"] # Keep in mind that the order doesn't matter
```

Also, when disabling a feature that other features depend on, those features that depend on it should also be disabled. This rule of course does not apply for the `default` feature.

Here is an example:

```toml
[dependencies.image-processing]
version = "1"
# Disable `png` which also disables `webp` because it depends on it
features = ["!png"]
```
