### ISSUE TITLE
Manifest's conditional dependency feature flag not working

### ISSUE THREAD

**Issue by hydroper** [rust-lang/cargo#12414]
### Problem

I've three crates:

- `c1`
- `c2`
- `c3`

What they do:

- `c1::main` calls `c2::f`
- `c2::f` calls `c3::f`
- `c3::f` prints whether it has been called with a feature `c1_some_feature` or not.

I get this after running `cargo run c1 --features c1_some_feature`

```sh
# got
called c3::f() without c1_some_feature

# expected
called c3::f() with c1_some_feature
```

Inside the `features` section of the manifest, I used the `dependency/c1_some_feature` syntax:

- Inside `c1/Cargo.toml`
```toml
[dependencies]
c2 = { path = "../c2" }

[features]
c1_some_feature = ["c2/c1_some_feature"]
```
- Inside `c2/Cargo.toml`
```toml
[dependencies]
c3 = { path = "../c3" }

[features]
c1_some_feature = ["c3/c1_some_feature"]
```

### Steps

1. Clone this simple workspace demonstrating the issue and run the binary `c1`: 
```sh
git clone https://github.com/hydroper/cargo_indirect_features
cd cargo_indirect_features
cargo run c1 --features c1_some_feature
```

### Possible Solution(s)

N/A

### Notes

N/A

### Version

```text
cargo 1.73.0-nightly (1b1555676 2023-07-18)
release: 1.73.0-nightly
commit-hash: 1b15556767f4b78a64e868eedf4073c423f02b93
commit-date: 2023-07-18
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 CoreSingleLanguage) [64-bit]
```
```

**Comment by epage** [comment]
I just tried to reproduce this with both stable and the same nightly and it worked
```console
$ cargo +nightly run -p c1
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/c1`
not c1_some_feature

$ cargo +nightly run -p c1 -F c1_some_feature
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/c1`
c1_some_feature
```

`Cargo.toml`:
```toml
[workspace]
resolver = "2"
members = ["c1", "c2", "c3"]
```
`c1/Cargo.toml`:
```toml
[package]
name = "c1"
version = "0.0.0"

[dependencies]
c2 = { path = "../c2" }

[features]
c1_some_feature = ["c2/c1_some_feature"]
```
`c1/src/main.rs`
```rust
fn main() {
    c2::f();
}
```
`c2/Cargo.toml`
```toml
[package]
name = "c2"
version = "0.0.0"

[dependencies]
c3 = { path = "../c3" }

[features]
c1_some_feature = ["c3/c1_some_feature"]
```
`c2/src/lib.rs`
```rust
pub fn f() {
    c3::f()
}
```
`c3/Cargo.toml`
```rust
[package]
name = "c3"
version = "0.0.0"

[features]
c1_some_feature = []
```
`c3/src/lib.rs`
```rust
pub fn f() {
    #[cfg(feature = "c1_some_feature")]
    println!("c1_some_feature");
    #[cfg(not(feature = "c1_some_feature"))]
    println!("not c1_some_feature");
}
```

btw in cases like this, it'd help if you posted a repo that reproduces the issue so its easier for other people to verify, debug, and fix.
