### ISSUE TITLE
profile-rustflags are not propagated to `CARGO_CFG_TARGET_FEATURE` or `CARGO_ENCODED_RUSTFLAGS`

### ISSUE THREAD

**Issue by DouglasDwyer** [rust-lang/cargo#12437]
### Problem

When setting flags with the `profile-rustflags` unstable feature (tracking issue #10271), the data is not propagated to the build script environment variables `CARGO_CFG_TARGET_FEATURE` and `CARGO_ENCODED_RUSTFLAGS`.

### Steps

1. Create a new binary
2. Create a `build.rs`:
```rust
fn main() {
    println!("cargo:warning=Feats: {:?} Flags: {:?}", std::env::var("CARGO_CFG_TARGET_FEATURE"), std::env::var("CARGO_ENCODED_RUSTFLAGS"));
}
```
3. Set up `Cargo.toml`:
```toml
cargo-features = [ "profile-rustflags" ]

[package]
name = "profile_flags_script"
version = "0.1.0"
edition = "2021"

[profile.dev]
rustflags = [ "-C", "target-feature=+crt-static" ]
```
4. Call `cargo run` - observe that `crt-static` is not reported by the build script.
5. Create `.cargo/Config.toml`:
```toml
[build]
rustflags = [ "-C", "target-feature=+crt-static" ]
```
6. Call `cargo clean` and `cargo run` - observe that the build script now sees the `crt-static` flag, as it should.

### Notes

This issue seems very similar to #6858.

### Version

```text
cargo 1.70.0-nightly (145219a9f 2023-03-27)
release: 1.70.0-nightly
commit-hash: 145219a9f089f8b57c09f40525374fbade1e34ae
commit-date: 2023-03-27
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Home) [64-bit]
```

**Comment by weihanglo** [comment]
I assumed you use `proflie-rustflags` because you only want some flags for specific profiles. Given that is an unstable feature and not reflects the correct set of flags, here is another workaround before that moves forward:

* Create an extra `config.toml` file, e.g. `.cargo/dev.config.toml`
* Put these in that config file:
     ```toml
     [build]
     rustflags = ["-C", "target-feature=+crt-static"]
     ```
* Run `cargo b --config .cargo/dev.config.toml` and you're all set.
  (Alternaitvely you can run `cargo +nightly -Zunstable-options --config dev.config.toml rustc --print cfg` to verify it working.)

**Comment by andreeaflorescu** [comment]
@weihanglo `-Zallow-features` is also not passed in `CARGO_ENCODED_RUSTFLAGS`  when it specified as follows in the `.cargo/config.toml`:
```toml
[unstable]
allow-features = []
```

Is this the intended behavior? If not, I can also open a separate issue if you think it makes sense. I am running into a build problem because of it as the proc-macro2 crate enables the unstable feature `proc_macro_span` unless `-Zallow-features` is passed. As a workaround I am adding `-Zallow-features` to the build and target RUSTFLAGS, but that results in quite a lot of duplication as we have multiple target definitions.
