### ISSUE TITLE
Features requested in [target.'cfg(...)'.dependencies] are erroneously activated

### ISSUE THREAD

**Issue by fintelia** [rust-lang/cargo#12448]
### Problem

Given a Cargo.toml for crate 'b' containing:
```toml
[dependencies]
a = { path = "../a", default-features = false }

[target.'cfg(target = "BOGUS-TARGET-NAME")'.dependencies]
a = { path = "../a", features = ["fail"] }
```
Any crate that depends on 'b' will pull in 'a' with the "fail" feature activated.

### Steps

1. Clone `https://github.com/fintelia/cargo-target-bug`.
2. Observe that the root crate depends on crate 'b' which has the Cargo.toml shown above.
3. Run `cargo check` from the root and observe that compilation fails because 'a' has the "fail" feature activated.

### Version
Seems to impact all versions since 1.8.0 when the syntax was added.
