### ISSUE TITLE
Let aliases in `.cargo/config.toml` specify environment variables

### ISSUE THREAD

**Issue by not-my-profile** [rust-lang/cargo#12477]
### Problem

The [`[alias]`](https://doc.rust-lang.org/cargo/reference/config.html#alias) table in `.cargo/config.toml` lets you define command aliases but it doesn't let you specify environment variables for these commands.

### Proposed Solution

Support environment variables to be specified as follows:

```toml
[alias]
docsrs = {command="doc", env={RUSTDOCFLAGS="--cfg docsrs"}}
```
