### ISSUE TITLE
Support recursively building all examples

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#1249]
There doesn't seem to be a way to recursively test all examples in `project/examples`. If this was supported, I think the testing framework for rustbyexample could move to `cargo` from `rustc`.

You'd might need a way to exclude a specific file from being included too. I gave a possible syntax but I have no idea what is proper in a `*.toml` file:
```toml
[package]

name = "package_name"
version = "0.0.1"
authors = ["authors_name"]

[[example]]
name = "test1"
recursive_path = "examples/*/*.rs"

[[exclude example]]
name = "test2"
path = "examples/please/dont/run/*/*.rs"

```
