### ISSUE TITLE
cargo vendor copies unnecessary crates if crate has dependency that uses "?" syntax

### ISSUE THREAD

**Issue by makotokato** [rust-lang/cargo#12621]
### Problem

`cargo vendor` copies necessary crates into `vendor` directory. But when dependencies crates use "?" syntax in feature's dependencies, this commands ignores "?". It means that this command copies all unnecessary crates into vendor directory.

### `Cargo.toml`
```toml
[package]
name = "vendor-test"
version = "0.1.0"
edition = "2021"

[dependencies]
icu_capi = { git = "https://github.com/unicode-org/icu4x", rev = "548158ebd39b72f0149e98161dc7f82b227a5caf", default-features= false, features = ["any_provider", "icu_segmenter", "compiled_data"] }
```

### icu_capi's `Cargo.toml`
This crate uses "?" syntax in dependencies of features.

```toml
..
[features]
..
icu_segmenter = ["dep:icu_segmenter"]
compiled_data = [
    "icu_calendar?/compiled_data",
    "icu_casemap?/compiled_data",
    "icu_collator?/compiled_data",
    "icu_datetime?/compiled_data",
    "icu_decimal?/compiled_data",
    "icu_displaynames?/compiled_data",
    "icu_list?/compiled_data",
    "icu_locid_transform?/compiled_data",
    "icu_normalizer?/compiled_data",
    "icu_plurals?/compiled_data",
    "icu_properties?/compiled_data",
    "icu_segmenter?/compiled_data",
    "icu_timezone?/compiled_data",
]
..
[dependencies]
icu_segmenter = { workspace = true, features = ["auto"], optional = true }
```

### Steps

1. Run `cargo init` then, modify `cargo.toml`
```toml
[package]
name = "vendor-test"
version = "0.1.0"
edition = "2021"

[dependencies]
icu_capi = { git = "https://github.com/unicode-org/icu4x", rev = "548158ebd39b72f0149e98161dc7f82b227a5caf", default-features= false, features = ["any_provider", "icu_segmenter", "compiled_data"] }
```
2. Run `cargo vendor`

Some unnecessary crates such as `icu_datetime` crate are copied into vendor directory unfortunately.

### Version

```text
- cargo 1.74.0 (5a856bf98 2023-09-04)
- cargo 1.72.0 (103a7ff2e 2023-08-15)
```
