### ISSUE TITLE
Crate dependency compiled twice when using path=

### ISSUE THREAD

**Issue by hugoduncan** [rust-lang/cargo#1280]
When compiling a project that specifies a crate dependency with `path=`, and that crate is also a transitive dependency, then two versions of the crate get compiled and used.

This can be reproduced with a checkout of the log crate and a `Cargo.toml` project that uses it:

```toml
[package]
name = "dupdeps"
version = "0.0.1"

[dependencies.log]
path = "log" # path to a checkout of the log crate

[dependencies]
mime = "*"
```

Running `cargo build`:

```
   Compiling log v0.2.2 (file:///…/dupdeps)
   Compiling log v0.2.2
   Compiling mime v0.0.8
   Compiling dupdeps v0.0.1 (file:///…/dupdeps)
```

The duplicate libraries can lead to compiler errors like:

```
expected `&collections::vec::Vec<hyper::header::shared::quality_item::QualityItem<collections::string::String>>`,
found `&collections::vec::Vec<hyper::header::shared::quality_item::QualityItem<collections::string::String>>`
(expected struct `hyper::header::shared::quality_item::QualityItem`,
found a different struct `hyper::header::shared::quality_item::QualityItem`) [E0308]
```
