### ISSUE TITLE
Presence of a parent Cargo.toml breaks the resolution of the features for conditional dependencies.

### ISSUE THREAD

**Issue by makemeunsee** [rust-lang/cargo#12821]
### Problem

The resolution of the features for conditional dependencies works for a simple, flat project, e.g.

```toml
[package]
name = "member"

# ...

[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { version = "1", features = ["rt"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
```

but then fails if this project becomes the member of a parent project, e.g.:

```toml
[workspace]
members = ["member"]
```

### Steps

1. clone https://github.com/makemeunsee/cargo_bug/
2. from the repo, run `cargo build` -> all is fine
3. then run `cargo build --target wasm32-unknown-unknown` -> it fails (and it should not)
4. 
    - [option 1] remove `./Cargo.toml`, `cd` to member then `cargo build --target wasm32-unknown-unknown` -> success
    - [option 2] remove lines 11 & 12 of `member/Cargo.toml`, then `cargo build --target wasm32-unknown-unknown` -> success

### Possible Solution(s)

I've tried to work around the issue by declaring workspace dependencies but no, I couldn't get solve the problem.

### Notes

I found already opened issues with similarities, but not a single one which really corresponds, so I filed a new one...

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-unknown-linux-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by epage** [comment]
While there isn't quite enough information to be sure of the problem, a frequent root cause this matches is fixed by doing
```toml
[workspace]
members = ["member"]
resolver = "2"
```
I think its 1.74 will have a warning to tell you that you should probably do this.
