### ISSUE TITLE
Failed to link with rustc-link-arg

### ISSUE THREAD

**Issue by zzwxh** [rust-lang/cargo#12843]
### Problem

```toml
[dependencies]
libwebp2 = { version = "0.0.2", features = ["download"] }
```
cargo build failed

I can successfully build test for libwebp2, but it fails to build when it is used as a dependency for other crates.
