### ISSUE TITLE
Per-crate linking option in Cargo manifest

### ISSUE THREAD

**Issue by tae-soo-kim** [rust-lang/cargo#12848]
### Problem

One Rust package may contain a single library crate and multiple binary crates. If only one binary crate needs to link with a C native library, then it doesn't quite make sense to link that native library with the library crate, because

1. The library crate itself doesn't need it, nor do other binary crates.
2. Users of the package do not clearly see which native libraries are needed for which crate.

Currently the only way to configure per-crate linking option seems to be using [cargo:rustc-link-arg-bin=BIN=FLAG](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-arg-bin). This requires some effort in the build script, and still doesn't show native library dependencies in documented format.

### Proposed Solution

It would be much nicer if each crate lists its own linking dependencies in `Cargo.toml` like this:

```toml
[lib]
name = "foo"
links = "foodeps"

[[bin]]
name = "bar"
links = "bardeps"

[[bin]]
name = "baz"
links = "bazdeps"
```

or 

```toml
[lib]
name = "foo"
rustc-link-lib = "foodeps"

[[bin]]
name = "bar"
rustc-link-lib = "bardeps"

[[bin]]
name = "baz"
rustc-link-lib = "bazdeps"
```

Programmers won't need `#link` attribute or [cargo:rustc-link-lib=LIB](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib) build script instruction in many use cases.

### Notes 1

Currently `Cargo.toml` may contain these fields to [override build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts):

```toml
[target.x86_64-unknown-linux-gnu.foo]
rustc-link-lib = ["foo"]
rustc-link-search = ["/path/to/foo"]
```

However this applies to whole package not per crate.

### Notes 2

Currently, Cargo on `cargo:rustc-link-lib` passes `-l <lib>` to rustc when compiling the lib crate. What I'm looking for is Cargo passing `-l <lib>` to bin crates on a similar build script instruction or a bin-crate option in `Cargo.toml`.
