### ISSUE TITLE
Warn on unknown keys in lint table entries

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/cargo#12917]
### Problem

In https://github.com/rust-lang/rust-clippy/issues/11751 a user had

```toml
[lints.clippy]
doc_markdown = { level = "deny", doc_valid_idents = ["GHz", ".."] }
```

Expecting the `doc_valid_idents` to set the clippy configuration of the same name, however it is silently ignored by cargo
