### ISSUE TITLE
Cargo.lock contains unnecessary deps when using `?`

### ISSUE THREAD

**Issue by GnomedDev** [rust-lang/cargo#12937]
### Problem

When using the `dep?/feature` syntax, `dep` and it's dependencies are always included in the `Cargo.lock` even when they do not get compiled in.

### Steps

1. Create three crates, with the following `Cargo.toml`s
```toml
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
dep = { path = "../dep" }

```
 
```toml
[package]
name = "dep"
version = "0.1.0"
edition = "2021"

[dependencies]
subdep = { path = "../subdep", optional = true }

[features]
default = ["passthrough-feature"]

passthrough-feature = [
    "subdep?/example-feature"
]
```

```toml
[package]
name = "subdep"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
example-feature = []
```
2. Run `cargo update` in the `scratch` crate to generate the `Cargo.lock`
3. Observe `subdep` being included in the lock file.

### Notes

This was found for [Discord TTS Bot](https://github.com/Discord-TTS/Bot) depending on [Songbird](https;//github.com/serenity-rs/songbird/tree/next) which caused `twilight-gateway` to be included which contained a lot of outdated deps causing duplicates such as rustls.

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Arch Linux [64-bit]
```
