### ISSUE TITLE
allow setting `codegen-backend` per-target

### ISSUE THREAD

**Issue by flippette** [rust-lang/cargo#13001]
### Problem

i'm currently testing the `codegen-backend` option, but every target besides `x86_64-unknown-linux-gnu` does not work with `cranelift`. i would like to be able to select the backend for each individual target, or even better, for each `cfg()` target.

### Proposed Solution

add a `codegen-backend` field to `[target.<triple>]` and `[target.<cfg-expr>]` sections.

### Notes

p.s. would also be nice if we could somehow do something akin to

```toml
[target.x86_64-unknown-linux-gnu.profile.dev]
codegen-backend = "cranelift"
```
