### ISSUE TITLE
Allow using examples in `default-run`

### ISSUE THREAD

**Issue by jjant** [rust-lang/cargo#13014]
### Problem

I have a library crate with examples under `/examples`. I want to be able to run `cargo run` to run an example automatically.

### Proposed Solution

Allow something like

```toml
default-run = "./examples/my-example.rs"
```

in `Cargo.toml`.

### Notes

This can be emulated by adding a `[[bin]]` target with your example:

```toml
[[bin]]
name = "my-example"
path = "./examples/my-example.rs"
```

However:
- This is annoying
- It gives you the following warning:
```terminal
warning: file `~/lib-crate/./examples/my-example.rs` found to be present in multiple build targets:
  * `bin` target `my-example`
  * `example` target `my-example`
  ```

**Comment by weihanglo** [comment]
Can't that `example` be a `bin` instead?

Could you add an `[alias]` in `.cargo/config.toml` to run your default example, like:

```toml
[alias]
realrun = "run --example my-fake-example-realbin"
```

Could you share more about the workflow and scenario?
