### ISSUE TITLE
Allow renaming crates in the dependencies section

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/cargo#1311]
Something like this should work:

``` toml
[dependencies.rustc_serialize]
crate = "rustc-serialize"
```

At the moment, only `path` and `git` attributes are supported.

**Comment by tomjakubowski** [comment]
What's the intent of this?

**Comment by alexcrichton** [comment]
This is actually currently possible as:

```toml
[dependencies.foo]
version = "..."
```

Although if you mean renaming crates that's a separate issue :)
