### ISSUE TITLE
cargo init or cargo new Cargo.toml don't respect `workspace exclude`

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/cargo#13235]
### Problem

when I have a workspace, exclude `data`:

```toml
[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["data"]
```

then I create a new crate in data folder:

The Cargo.toml will be:

```toml
version.workspace = true
edition.workspace = true
```

instead of

```toml
version = "0.1.0"
edition = "2021"
```

I have to change it manually.

**Comment by hi-rustin** [comment]
Could you please provide your Cargo version?

I can not reproduce this issue. My Cargo version:
```console
❯ cargo -Vv
cargo 1.77.0-nightly (ac6bbb332 2023-12-26)
release: 1.77.0-nightly
commit-hash: ac6bbb33293d8d424c17ecdb42af3aac25fb7295
commit-date: 2023-12-26
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0 (sys:0.4.70+curl-8.5.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.2.1 [64-bit]
```

**Comment by kzhui125** [comment]
maybe nightly cargo fixed this issue?

```
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0 (sys:0.4.68+curl-8.4.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.2.1 [64-bit]
```

**Comment by kzhui125** [comment]
It seems another issue.

cargo init will add `members = ["data/a1"]` to workspace Cargo.toml

I have to remove the `members = ["data/a1"]`

```toml
[workspace]
resolver = "2"
exclude = ["data"]
members = ["data/a1"]
```
