### ISSUE TITLE
`cargo add crate-name` & `cargo add crate_name` have different results when `crate_name` is already present

### ISSUE THREAD

**Issue by GrigorenkoPV** [rust-lang/cargo#13304]
### Problem

Example manifest:

```toml
[package]
name = "add"
version = "0.0.0"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["display"]
```

### Steps

`cargo add derive_more` changes nothing.
`cargo add derive-more` resets chosen features and sets the version to latest available.

### Version

```text
cargo 1.76.0-beta.5 (ddec30889 2024-01-02)
release: 1.76.0-beta.5
commit-hash: ddec30889aff0c38118bcbeb59597d0bd85eddcd
commit-date: 2024-01-02
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.5.0-DEV (sys:0.4.70+curl-8.5.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux Rolling Release [64-bit]
```
