### ISSUE TITLE
Benches: improved user experience for adding new benchmarking files

### ISSUE THREAD

**Issue by Walther** [rust-lang/cargo#13406]
Currently, creating benchmarks for a crate looks something like this:

```shell
# Project structure
.
├── Cargo.toml
├── README.md
├── benches
│   ├── various.rs
│   ├── file.rs
│   ├── names.rs
│   └── here.rs
├── src
│   ├── various.rs
│   ├── file.rs
│   ├── names.rs
│   └── here.rs
# Mirroring the src/ file names in benches/ makes sense, for easy discoverability
...
```

```toml
# Cargo.toml

[dev-dependencies]
divan = "0.1.11"

[[bench]]
name = "various"
harness = false

[[bench]]
name = "file"
harness = false

[[bench]]
name = "names"
harness = false

[[bench]]
name = "here"
harness = false

# However, here it feels like a chore
```

This gets repetitive very quickly, and doesn't feel like the ideal developer experience.

Would it be possible to consider:
- automatically detecting the files under `benches/` so that the `[[bench]]` sections aren't required
- setting `harness = false` by default and letting people override it to `harness = true` when needed

in order to simplify the process of adding new benchmarks into just adding a new file to the `benches/` directory?

---

A related issue and comment for historical context: https://github.com/rust-lang/rust/issues/29553#issuecomment-1538662472
