### ISSUE TITLE
-Clink-args not work with env

### ISSUE THREAD

**Issue by southorange0929** [rust-lang/cargo#13458]
### Problem

I try to use `-Clink-args` to custom linker with args.

If config with `.cargo/config.toml`, it worked.

```toml
[target.aarch64-unknown-linux-ohos]
linker = "path/native/llvm/bin/clang"
rustflags = [
    "-Clink-args=-target aarch64-linux-ohos --sysroot=path/native/sysroot -D__MUSL__",
]
```

but if try it with env, it get some error

```
env::set_var("RUSTFLAGS","-Clink-args=-target aarch64-linux-ohos --sysroot=path/native/sysroot -D__MUSL__")
```

<img width="1240" alt="image" src="https://github.com/rust-lang/cargo/assets/32590310/d2232769-4fee-463d-920f-7a48bdb1947d">

Any suggestion about it? Thanks

```[tasklist]
### Tasks
```
