### ISSUE TITLE
Normal dependencies get ignored if they're mentioned after platform specific dependencies

### ISSUE THREAD

**Issue by dimpolo** [rust-lang/cargo#13582]
### Problem

See title and steps

### Steps

Cargo.toml: `paste` crate is ignored:
```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
[target.'cfg(target_arch = "riscv32")'.dependencies]
syn = "1.0.72"

paste = "1.0.14"
```

```shell
$ cargo tree --depth 1
playground v0.1.0 (<redacted>\playground)
```

working Cargo.toml:
```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.14"

[target.'cfg(target_arch = "riscv32")'.dependencies]
syn = "1.0.72"

```

```shell
$ cargo tree --depth 1
playground v0.1.0 (<redacted>\playground)
└── paste v1.0.14 (proc-macro)

```

### Version

```text
cargo 1.77.0-nightly (7bb7b5395 2024-01-20)
release: 1.77.0-nightly
commit-hash: 7bb7b539558dc88bea44cee4168b6269bf8177b0
commit-date: 2024-01-20
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.5.0-DEV (sys:0.4.70+curl-8.5.0 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Pro N) [64-bit]
```
