### ISSUE TITLE
`cargo vendor` failed for git targets when realpath of`~/.cargo/git` includes softlink

### ISSUE THREAD

**Issue by wfly1998** [rust-lang/cargo#13599]
### Problem

`cargo vendor` throws `No such file or directory (os error 2)` for git targets when realpath of `~/.cargo/git` includes softlink, e.g., `/home/foo` is softlink to `/mnt/disk/foo` or `/home/foo/.cargo/git` is softlink to `/home/bar/.cargo/git`.

### Steps

A simple method for reproduce the problem:

```bash
mv ~/.cargo/git ~/.cargo/another-git
ln -sf another-git ~/.cargo/git
```

Then run `cargo vendor` for any crate with git dependences.  My test case is the following:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { git = "https://github.com/rust-lang/futures-rs.git", tag = "0.3.30" }
```

My outputs:

```
$ cargo vendor
   Vendoring autocfg v1.1.0 (/home/foo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/autocfg-1.1.0) to vendor/autocfg
   Vendoring futures v0.3.30 (https://github.com/rust-lang/futures-rs.git?tag=0.3.30#de1a0fd6) (/home/foo/.cargo/git/checkouts/futures-rs-b0bea7d4c3745ece/de1a0fd/futures) to vendor/futures
error: failed to sync

Caused by:
  failed to write `vendor/futures/.cargo-checksum.json`

Caused by:
  No such file or directory (os error 2)
```

It throws `ENOENT` when writing `vendor/futures/.cargo-checksum.json` because the `futures` is not created.

### Possible Solution(s)

The root cause is:

https://github.com/rust-lang/cargo/blob/69726309bf12443a618643cc86125ef60dcbecfb/src/cargo/sources/path.rs#L326-L331

The `pkg_path` is original path (`/home/foo/.cargo/git`) but the `file_path` is realpath (`/home/foo/.cargo/another-git/`)

I have found the root case but I'm not familiar enough with `cargo` to fix it elegantly 😢 What I can do is submitting this issue.

### Version

```text
$ cargo version --verbose
cargo 1.79.0-nightly (2fe739fcf 2024-03-15)
release: 1.79.0-nightly
commit-hash: 2fe739fcf16c5bf8c2064ab9d357f4a0e6c8539b
commit-date: 2024-03-15
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian 10 (buster) [64-bit]
```
