### ISSUE TITLE
Multi-constraint inequality dependencies don't parse

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#1362]
The manual talks about them: http://doc.crates.io/crates-io.html#using-crates.io-based-crates, but I can't seem to get them to work:

```toml
[package]
name = "foo"
version = "0.0.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
log = ">= 0.2, < 0.4"
```

```
failed to parse manifest at `/home/sfackler/foo/Cargo.toml`

Caused by:
  the given version requirement is not implemented, yet
```
