### ISSUE TITLE
maybe a typo issue that make this doc fragment confused 

### ISSUE THREAD

**Issue by lrobot** [rust-lang/cargo#13730]
https://github.com/rust-lang/cargo/blob/bd1cf584af2c356eeb3980c3c9bb0fea190ed633/src/doc/src/reference/overriding-dependencies.md?plain=1#L218C1-L219C1

```toml
[package]
name = "my-binary"
version = "0.1.0"

[dependencies]
my-library = { git = 'https://example.com/git/my-library' }
uuid = "1.0"

[patch.crates-io]
uuid = { git = 'https://github.com/uuid-rs/uuid.git', branch = '2.0.0' }
```
===============================================
since my-binary need use uuid=1.0. it patch may reference to uuid.git@master. so:
```
>>>>uuid = { git = 'https://github.com/uuid-rs/uuid.git', branch = '2.0.0' }
should be:
<<<<uuid = { git = 'https://github.com/uuid-rs/uuid.git' }
```

I am not 100% sure about this. but this modify make me clearly.
