### ISSUE TITLE
"cargo new" should add pre-commit hooks for autoformatter and linter

### ISSUE THREAD

**Issue by worldmind** [rust-lang/cargo#13758]
### Problem

0. Usage of autoformatter and linter is a really good practice and, for not depend on IDE, good to have them in [pre-commit](https://pre-commit.com/) hooks (of course it can also be some [rust implementation (if any)](https://crates.io/search?q=pre-commit)) for block commiting changes which has issues.
1. Rust/cargo has [rustfmt](https://github.com/rust-lang/rustfmt) and [clippy](https://doc.rust-lang.org/clippy/).
2. `cargo new` even does initialization of new git repo, has all tools, but doesn't configure pre-commit hooks, but why to not add them as it clearly good practice?

### Proposed Solution

`cargo new` should depends on pre-commit or something similar and add config (`.pre-commit-config.yaml` for pre-commit).

### Notes

For rustfmt I found example [here](https://users.rust-lang.org/t/git-hooks-for-rust-cargo/73847/7):
```
repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
```
another example, plus example for clippy can be found [here](https://github.com/flavray/avro-rs/blob/main/.pre-commit-config.yaml):
```
-   repo: local
    hooks:
    -   id: rust-linting
        name: Rust linting
        description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
        entry: cargo fmt --all --
        pass_filenames: true
        types: [file, rust]
        language: system
    -   id: rust-clippy
        name: Rust clippy
        description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
        entry: cargo clippy --all-targets --all-features -- -Dclippy::all
        pass_filenames: false
        types: [file, rust]
        language: system
```
