### ISSUE TITLE
Configuration specific dependencies break `cargo tree`

### ISSUE THREAD

**Issue by abrisco** [rust-lang/cargo#13854]
### Problem

Running `cargo tree` on the following yaml now fails in Nightly releases of Cargo
```toml
[package]
name = "target_cfg_features"
version = "0.1.0"
edition = "2018"

# Required to satisfy cargo but no `lib.rs` is expected to
# exist within test data.
[lib]
path = "lib.rs"

[dependencies]
tokio = "1.25.0"

[target.'cfg(unix)'.dependencies.tokio]
features = ["fs"]
```
#### Stable
```
target_cfg_features v0.1.0 (/target_cfg_features)
└── tokio v1.25.0
    └── pin-project-lite v0.2.9
    [build-dependencies]
    └── autocfg v1.1.0
```
#### Nightly
```
error: failed to parse manifest at `/target_cfg_features/Cargo.toml`

Caused by:
  dependency (tokio) specified without providing a local path, Git repository, version, or workspace dependency to use
```

### Steps

Use `Cargo.toml` from above and run `cargo tree`

### Version

```text
cargo 1.78.0 (54d8815d0 2024-03-26)
cargo 1.80.0-nightly (6087566b3 2024-04-30)
```

**Comment by weihanglo** [comment]
It was a bug we fixed recently in <https://github.com/rust-lang/cargo/pull/13775>. The bug has been there for a long while. Now Cargo disallows dependencies without any source, to avoid confusion.

>   dependency (tokio) specified without providing a local path, Git repository, version, or workspace dependency to use

To fix this, follow the instruction and specify a version, or any other kind of dependency. Like

```toml
[target.'cfg(unix)'.dependencies.tokio]
features = ["fs"]
version = "1.25.0"
```

**Comment by abrisco** [comment]
Is there a way to refer to the same version defined in `[dependencies]` directly?

**Comment by abrisco** [comment]
And what was the behavior before? It certainly seems like the behavior was to inherit the version from `[dependencies]`. It seems like the intent of https://github.com/rust-lang/cargo/pull/13775 was to fix
```toml
[dependencies]
tokio = {}
```
not prohibit the example in the original post. I think I lack some context to comprehend everything in the original post though.
