### ISSUE TITLE
Windows `\\?\` verbatim paths break idiomatic use of OUT_DIR and `include!`

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#13919]
### Problem

When Cargo is invoked on Windows in either of the following 2 scenarios, and possibly others:

- a current directory that begins with `\\?\`
- `--manifest-path` that begins with `\\?\`

then the following widespread idiom for including build.rs-generated code does not work.

```rust
include!(concat!(env!("OUT_DIR"), "/repro.rs"));
```

Because `/` is not a directory separator in verbatim paths, this fails to compile with an error like this:

```console
error: couldn't read \\?\D:\a\repro\repro\target\debug\build\repro-59592f29f689633e\out/repro.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
 --> src\lib.rs:3:1
  |
3 | include!(concat!(env!("OUT_DIR"), "/repro.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Normally in Windows paths `/` works just as well as `\`, but from [Maximum Path Length Limitation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation): _File I/O functions in the Windows API convert "/" to "\\" as part of converting the name to an NT-style name, **except when using the "\\\\?\\" prefix** as detailed in the following sections_.

### Steps

The problem can be reproduced in GitHub Actions with the following source code.

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
```

```rust
// build.rs

fn main() {
    let out_dir = std::env::var_os("OUT_DIR").unwrap();
    let repro = std::path::Path::new(&out_dir).join("repro.rs");
    std::fs::write(repro, "").unwrap();
}
```

```rust
// src/lib.rs

include!(concat!(env!("OUT_DIR"), "/repro.rs"));
```

```yaml
# .github/workflows/ci.yml

name: CI
on: [push]
jobs:
  repro:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - run: pwd
      - run: echo ${{github.workspace}}
      - run: echo \\?\${{github.workspace}}

      - run: cargo check --verbose && cargo clean

      - run: cargo check --manifest-path \\?\${{github.workspace}}\Cargo.toml --verbose
        if: always()

      - run: cargo check --verbose
        working-directory: \\?\${{github.workspace}}
        if: always()
```

The first `cargo check` will succeed. The second two will each fail as shown above.

### Possible Solution(s)

I hope that someone can make a successful proposal for something like:

```rust
include!(concat!(env!("OUT_DIR") / "repro.rs"));
```

which would work in a cross-platform manner by using the correct path separator for rustc's host OS.

Until then, https://github.com/rust-lang/cargo/pull/13914#issuecomment-2111375012 proposes a possible way that Cargo could work around this issue some of the time.

> Internally to Cargo, we exclusively work with regular paths and not verbatim paths. It sounds like the problem is that we accept paths from users in a couple of places which may be verbatim paths.
>
> Should we instead run `dunce` on those paths so they are no longer verbatim? This would solve it for Cargo and all other cases.

(https://docs.rs/dunce/1/dunce/fn.simplified.html)

This is only a partial fix because not all verbatim paths can be converted to something without `\\?\`. If a path is longer than 260 characters, `\\?\` is the only way to refer to it.

https://github.com/rust-lang/cargo/pull/13914 shows another possible workaround, but that one amounts to boiling the ocean to replace the OUT_DIR/`include` idiom with a substantially more verbose one.

### Notes

Meta-issue: https://github.com/rust-lang/cargo/issues/9770

### Version

```text
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.4.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.4.1 [64-bit]
```
