### ISSUE TITLE
Add `--workspace` to `cargo add`

### ISSUE THREAD

**Issue by jmg-duarte** [rust-lang/cargo#13915]
### Problem

I am working on a project where we're placing all dependencies in the workspace. Whenever I add a new dependency I want to be able to add it to the workspace rather than the local `Cargo.toml` file.

### Proposed Solution

The command
```bash
cargo add tokio -F full --workspace
```
Should add `tokio` to the the current `Cargo.toml` like so:
```toml
[dependencies]
tokio = { workspace = true, features = ["full"] }
```
And to the workspace `Cargo.toml`:
```toml
[dependencies]
tokio = "1" # or whatever version it would add
```

To find the workspace file, the command would go up the directories looking for `Cargo.toml` where `members` contains the current package.

Additionally, the `--workspace` flag could take a parameter with the workspace `Cargo.toml`'s path.

### Notes

If the feature is to be implemented, I am available to do it!
