### ISSUE TITLE
Workspace unexpected-cfg lint configuration does not apply to integration test.

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/cargo#13944]
### Problem

When using the workspace lints table to set `rust.unexpected-cfg`, integration tests appear to ignore the configuration.

### Steps

Workspace Cargo.toml:
```toml
[workspace]
resolver = "2"
members = ["unexpected"]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(biscuits)'] }
```

Add a workspace crate called "unexpected" with an `unexpected/tests/test.rs` file:

```rust
#![cfg(biscuits)]
```

Running `cargo +nightly test` will warn about the unexpected cfg even though it's set.

### Version

```text
cargo 1.80.0-nightly (0de7f2ec6 2024-05-17)
release: 1.80.0-nightly
commit-hash: 0de7f2ec6c39d68022e6b97a39559d2f4dbf3930
commit-date: 2024-05-17
host: x86_64-pc-windows-msvc
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:Schannel)
os: Windows 10.0.22631 (Windows 11 Professional) [64-bit]
```
