### ISSUE TITLE
Lints table allows both `-` and `_` separators, including allowing redundant entries.

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#13943]
Today, you can do:
```toml
[lints.rust]
unexpected_cfgs = "warn"
unexpected-cfgs = "allow"
```
and the behavior is unspecified.

After #13913, you can also do
```toml
[lints.rust]
unexpected-cfgs = { level = "warn", check-cfg = ['cfg(foo, values("bar"))'] }
```
and you'll get an "unused manifest key" warning for `check-cfg`.
