### ISSUE TITLE
`debug-assertions` are implicitly disabled when running `cargo test` with `opt-level=3` set from `rustflags`

### ISSUE THREAD

**Issue by benny-n** [rust-lang/cargo#14033]
### Problem

As the title states, it looks like having `rustflags = ["-C", "opt-level=3"]` in your `config.toml` implicitly disables debug assertions, even when running `cargo test`, which should have them enabled by default.

### Some background:
I am currently working on a project where I had a `config.toml` looking something like this:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
    # ...
    "-C",
    "opt-level=3",
    # ...
]
```

My task was to create a lightweight profile without optimizations to enjoy faster compilation times. However, I had to ensure that tests were still compiled with `opt-level=3` because it heavily affected their total run time.
So the first thing I did was create a `[profile.test]` entry and move `opt-level=3` from `rustflags` to it:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
    # ...
    # "-C",
    # "opt-level=3",
    # ...
]

[profile.test]
opt-level = 3
```

Surprisingly, after moving it, I observed some tests failing on debug assertions. It took a while to figure out, but after some digging, I found out that the code was never compiled with debug assertions to begin with, even though `"-C debug-assertions=false"` was **NOT** part of the `rustflags` array.

Since debug assertions should be [enabled by default for tests](https://doc.rust-lang.org/cargo/reference/profiles.html#dev), and since passing `opt-level=3` from a profile or from `rustflags` should be pretty much the same, this behavior seemed somewhat confusing to me.

Please do let me know if I'm missing something.

### Steps

1. `cargo init` and edit `main.rs` with:
```rust
fn main() {}

#[test]
fn debug_assert_false() {
    debug_assert!(false)
}
```
2. create a `.cargo/config.toml` and edit with:
```toml
[target.x86_64-unknown-linux-gnu] # also reproduces for aarch64-apple-darwin
rustflags = ["-C", "opt-level=3"]
```
3. run `cargo test` and observe the test passing.
4. edit `.cargo/config.toml` with:
```toml
# [target.x86_64-unknown-linux-gnu] # also reproduces for aarch64-apple-darwin
# rustflags = ["-C", "opt-level=3"]

[profile.test]
opt-level = 3
```
5. run `cargo test` again and observe the test **failing**.

### Version

```text
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```
