### ISSUE TITLE
centralize lint configuration

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/cargo#14236]
### Description

It would be really great to be able to centralize lint configurations across packages. The current limitations mean that, if a team maintains 20 packages in different repos, they will need to manage each package separately.

Is this something we'd be interested in adding?

### Proposed Solution

I'd think we could have a feature where we could add something like:

```toml
[lints.src]
git = "https://github.com/team-repo/lint-config.git"
```

to `Cargo.toml`.
