### ISSUE TITLE
Activation of features of non-optional dependencies breaks manifest for 2024 edition

### ISSUE THREAD

**Issue by cassaundra** [rust-lang/cargo#14283]
## Problem

Activation of an `foo/bar` feature dependency where `foo` is not an optional dependency results causes a manifest error in edition 2024:

```toml
[dependencies]
foo = "..."
bar = { version = "...", optional = true }

[features]
bar = ["dep:bar", "foo/bar"] # -> ["dep:bar", "foo/bar", "dep:foo"]
```

...results in...

```
feature `bar` includes `dep:foo`, but `foo` is not an optional dependency
```

### Explanation

#14221 introduces implicit activation of `dep:` for non-weak dependencies when parsing/updating the manifest in edition 2024. This issue appears to be to due to a missing check for whether or not the dependency of the activated feature is marked as optional.

This issue was also brought up in [a comment](https://github.com/rust-lang/cargo/pull/14221#discussion_r1686496418) post-merge, and in [a Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Edition.202024.3A.20dep.20feature.20breakage.20with.20non-optional.20dep).

### Reproducible example

```toml
cargo-features = ["edition2024"]

[package]
name = "foobar"
edition = "2024"
version = "0.1.0"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.204", optional = true }

[features]
serde = ["dep:serde", "chrono/serde"] # -> ["dep:serde", "chrono/serde", "dep:chrono"]
```

### Version

`cargo --version`:
```
cargo 1.82.0-nightly (5f6b9a922 2024-07-19)
release: 1.82.0-nightly
commit-hash: 5f6b9a92201d78af75dc24f14662c3e2dacbbbe1
commit-date: 2024-07-19
```

**Comment by epage** [comment]
> This check happens before dependence resolution/workspace inheritance, but since optional can't be set in workspace deps, we should be able to determine its optionality from the raw InheritableDependency without needing to check the workspace manifest. 

I'd prefer not to have assumptions like this buried in the code

Speaking of assumptions, though it felt dirty, I tried to go the opposite direction and make normalizing of features dependent on normalization of dependencies.  However, normalization of dependencies is already dependent on normalization of features.

> Alternatively, we could revert the change and try and introduce it later in the process, perhaps in resolution instead?

We need to insert it in a place that knows of and can handle editions.  I also prefer it to be recorded in `cargo publish` which was one of our care abouts when we decided on this direction, see https://github.com/rust-lang/cargo/issues/14016#issuecomment-2161083450

**Comment by epage** [comment]
To re-summarize the problem

```toml
package.edition = "2021"
[features]
feature = ["dep/feature"]
[dependencies]
dep = { version = "1", optional = true }
```
will cause a `dep` implicit feature to be created

As we want to suppress implicit features in 2024, we strip all optional dependencies like that.   This led to a new problem:
```toml
package.edition = "2024"
[features]
feature = ["dep/feature"]
[dependencies]
dep = { version = "1", optional = true }
```
As `dep` is stripped, this fails because `dep/feature` can't be resolved.  The user can workaround this by adding `dep:dep` (discoverability is poor).

We solved this by implicitly adding `dep:dep` to `feature`.  However, I forgot to check `dependencies.dep.optional`, so if it isn't optional, it also fails but in a way the user can't workaround. 

Logically, checking  `dependencies.dep.optional` gets circular because
- `resolve_features` needs to know about resolved dependencies to add `dep:dep`
- `resolve_dependencies` needs to know about resolved features to know what `dep:dep` are present

We could break this cycle by making a lot of assumptions about the unresolved forms.
