### ISSUE TITLE
Use the same version of a transitive dependency

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/cargo#14316]
### Problem

Let's say that I'm using
```toml
[dependencies]
reqwest = "0.12.5"
axum = "0.7.5"
```
But I also want to add tokio as a direct dependency, and I want to match the version that axum uses.
Specifying `*` as the version could choose either.

### Proposed Solution

Something like this
```toml
[dependencies]
reqwest = "0.12.5"
axum = "0.7.5"
tokio = "auxm"
```
