### ISSUE TITLE
Issue with Workspace and Crate features

### ISSUE THREAD

**Issue by gwbres** [rust-lang/cargo#14362]
### Problem

Hello, we're running into severe troubles [in the RINEX worksace](https://github.com/georust/rinex/issues/253), which has quite a few build options and integrates inner dependencies (path = "../" within the workspace). 

My explanation is that Cargo picks up the worst case scenario, in terms of dependencies and it kills the capabilities to detect issues that exist with for example a simple `build -r` while actually running `build -r` within the workspace.

The worst case scenario (in terms of dependencies) in our case, is the top level -cli application, which requires pretty much --all-features in the local libs.

### Steps

Download the RINEX workspace commit 70242aa09551f12ea511ea36b528210ee33a022a for example.

The CI did pass, because building within the workspace does pass.

Now try this

```toml
[package]
name = "tester"

[dependencies]
rinex = { git = "https://github.com/georust/rinex", rev = "70242aa09551f12ea511ea36b528210ee33a022a" }
```

```rust
fn main() {}
```
