### ISSUE TITLE
Warn when feature is not required explicitly, but required by a transitive dependency

### ISSUE THREAD

**Issue by antoniofunnel** [rust-lang/cargo#14375]
### Problem

```rust
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct Task {
    pub created_at: DateTime<Utc>,

}
```

this compiles with a cargo.toml that looks like this:

```toml
[package]
name = "testing"
version = "0.1.0"
authors = ["antonio"]
edition = "2021"
[dependencies]
chrono = "0.4.38"
serde_json = "1.0.120"
serde = { version = "1.0.202", features = ["derive"] }
rusoto_credential = "0.44.0"
```

When removing rusoto_credential from cargo.toml I get this error:

The trait bound `DateTime<Utc>: Deserialize<'_>` is not satisfied [E0277] the trait `Deserialize<'_>` is not implemented for `DateTime<Utc>`

This is because rusoto_credential also depends on chrono with the feature serde.

So adding that feature to my import of chrono solves it.

### Proposed Solution

A warning about used features thats not explicitly imported would be nice, or something smarter that I cant think off <3
