### ISSUE TITLE
`[patch]` ignores branch or rev

### ISSUE THREAD

**Issue by fenollp** [rust-lang/cargo#14466]
### Problem

Specifying a `[patch]` for a (git) crate does not take `branch` (or `rev` (and maybe also `tag`)) into account:

```toml
[workspace.dependencies.my-crate]
git = "ssh://git@myhost.net/myslug/myrepo.git"
branch = "main"

[patch."ssh://git@myhost.net/myslug/myrepo.git".my-crate]
git = "ssh://git@myhost.net/myslug/myrepo.git"
branch = "not-main"
```

```
error: failed to resolve patches for `ssh://git@myhost.net/myslug/myrepo.git`

Caused by:
  patch for `my-crate` in `ssh://git@myhost.net/myslug/myrepo.git` points to the same source, but patches must point to different sources
```

### Steps

cargo fetch

### Possible Solution(s)

A trick that works is to append an empty fragment to the end of the git URL.

This works:
```toml
[workspace.dependencies.my-crate]
git = "ssh://git@myhost.net/myslug/myrepo.git"
branch = "main"

[patch."ssh://git@myhost.net/myslug/myrepo.git".my-crate]
git = "ssh://git@myhost.net/myslug/myrepo.git#"  # <--- here
branch = "not-main"
```

### Notes

1. IMO the patch system should take branch, rev or tag into account as that "points to different sources"
1. An empty fragment in a git URL should not be used when comparing URLs (but please don't fix that yet!)

### Version

```text
cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 24.4.0 (noble) [64-bit]
```
