### ISSUE TITLE
Cargo optional feature (those with ?) is not working as expected

### ISSUE THREAD

**Issue by sunng87** [rust-lang/cargo#14494]
### Problem

I'm using `sqlx` library which has a big usage of optional feature dependencies (I'm not sure if the name is correct, it's in a form like `sqlx-sqlite?/chrono`).

It works perfectly with exlucding optional features. However, when building the dependency graph, I found it's still including those optional one, which can cause conflict for libraries you don't really use. 

### Steps

Create a project with these dependencies and run `cargo tree`

```toml
[package]
name = "sqlx-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono"
], default-features = false }
```

`cargo tree` result looks great and no sqlite dependencies are included. However, if I have a sqlite dependency in the project, it cause conflicts

```toml
[package]
name = "sqlx-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono"
], default-features = false }
## add a sqlite dependency that is incompatible with the one from sqlx
libsqlite3-sys = "=0.25.2"
```

Now cargo refuses to build the dependency graph

```
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `sqlx-sqlite v0.8.0`
    ... which satisfies dependency `sqlx-sqlite = "=0.8.0"` of package `sqlx v0.8.0`
    ... which satisfies dependency `sqlx = "^0.8"` of package `sqlx-test v0.1.0 (/home/sunng/tmp/sqlx-test)`
versions that meet the requirements `^0.28.0` are: 0.28.0

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.25.2`
    ... which satisfies dependency `libsqlite3-sys = "=0.25.2"` of package `sqlx-test v0.1.0 (/home/sunng/tmp/sqlx-test)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "sqlite3"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `libsqlite3-sys` which could resolve this conflict

```

However, we don't really included `sqlx-sqlite` in our project. So I consider this a bug for optional feature implementation.

### Version

```text
cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux Rolling Release [64-bit]
```
