### ISSUE TITLE
regression: "Cannot document a package where a library and a binary have the same name" error when [[bin]] has "doc = false"

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#1454]
### STR

``` shell
$ tree src
src
├── bin
│   └── foo.rs
└── lib.rs
$ cat src/bin/foo.rs
fn main() {}
$ cat src/lib.rs
// empty
```

``` toml
[package]
name = "foo"
version = "0.0.1"
authors = ["japaric"]

[[bin]]
doc = false
name = "foo"
path = "src/bin/foo.rs"
```

```
$ cargo doc
Cannot document a package where a library and a binary have the same name. Consider renaming one or marking the target as `doc = false`
```

### Version

```
cargo 0.0.1-pre-nightly (0e42b4d 2015-03-25) (built 2015-03-25)
```

---

However, `cargo doc` works if I use yesterday nightly: `cargo 0.0.1-pre-nightly (e689383 2015-03-16) (built 2015-03-16)` or an older nightly.

cc @alexcrichton
