### ISSUE TITLE
Enable LTO for new packages by default for profiles `release` and `bench`

### ISSUE THREAD

**Issue by foxtran** [rust-lang/cargo#14741]
### Problem

`release` and `bench` profiles are used for producing optimized binaries which are later used in production or benchmarking where the performance is important. Currently, by default these profiles uses `opt-level=3` as it is inside of Cargo at current moment. The next step on the optimization ladder is enabling LTO. As it was discussed in #11298, enabling by default in Cargo affects all projects and potentially may leads to strange bugs which still arises with LTO.

### Proposed Solution

Instead of global updating of Cargo, new Cargo projects may start with already configured profiles with enabled LTO for optimized buids. For `--bin`, it can be:
```toml
[profile.release]
lto = true
codegen-units = 1

[profile.release.package."*"]
opt-level = 3

[profile.bench]
lto = true
codegen-units = 1

[profile.bench.package."*"]
opt-level = 3
```
And for `--lib`, 
```toml

[profile.bench]
lto = true
codegen-units = 1

[profile.bench.package."*"]
opt-level = 3
```
As it was suggested #11298. 

At the initial stage of packages, enabled LTO (especially only in Release builds) should not be a problem since compilation time will not be increased significantly (or probably even decrease since only necessary part of application and its dependencies will be compiled). Later, when project grows up, developers may think about switching to thin LTO or disabling it if they consider it appropriate. So, users get a bit more optimized binaries from scratch without looking for this flag in cargo-book. One more benefit from doing this is that it will increase popularity of LTO and therefore this optimization gets more attention and higher priority will be with LTO-related bugs. 

### Notes

I've already created a PR #14738 that implements this thing but at current moment it requires to update table for more optimizations.
