### ISSUE TITLE
Circular dev-dependency enables features in release mode with resolver 2

### ISSUE THREAD

**Issue by sokki** [rust-lang/cargo#14807]
### Problem

In a workspace with 2 packages:

**main**
```toml
[dev-dependencies]
sub = { path = "../sub" }
[features]
testing = []
```

**sub**
```toml
[dependencies]
main = { path = "../main", features = ["testing"] }
```

The feature `testing` is enabled when running `main` in release mode.

Repro: https://github.com/sokki/resolve-circular-dev-dependencies-features

### Version

```text

```
