### ISSUE TITLE
`package` attribute is not respected when inheriting dependency from workspace

### ISSUE THREAD

**Issue by momvart** [rust-lang/cargo#14851]
### Problem

Regarding [Renaming dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml), it looks like that it's not respected when inheriting the dependency from the workspace.

### Steps

1. Add a dependency to your workspace.
2. Reference it in one of the members.
3. Rename it something else in the member and use the `package` attribute.

#### Example
Workspace:
```toml
# ...
[workspace.dependencies]
derive_more = { version = "1.0.0" }
```
Member:
```toml
[dependencies]
dm = { workspace = true, package = "derive_more" }
```

### Notes

Error:

```
error: failed to load manifest for workspace member `...`
referenced by workspace at `...`

Caused by:
  failed to parse manifest at `...`

Caused by:
  error inheriting `dm` from workspace root manifest's `workspace.dependencies.dm`

Caused by:
  `dependency.dm` was not found in `workspace.dependencies`
```

### Version

```text
cargo 1.84.0-nightly (69e595908 2024-11-16)
release: 1.84.0-nightly
commit-hash: 69e595908e2c420e7f0d1be34e6c5b984c8cfb84
commit-date: 2024-11-16
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.4.0 (jammy) [64-bit]
```
