### ISSUE TITLE
2024 edition migration of `default_features` doesn't work for virtual workspace inherited dependencies

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#14886]
### Problem

A virtual workspace with a workspace dependency that uses an underscore for `default_features` doesn't get migrated to 2024. After updating to 2024, this results in an error.

It does print a warning, though. However, I believe it is intended that the auto-fix should apply to this case to (it supports [workspaces](https://github.com/rust-lang/cargo/blob/ef5edffb89b8c3212ae1061619e5c2309cd8da98/src/cargo/ops/fix.rs#L282-L289), just not a virtual one).

### Steps

Root workspace:

```toml
[workspace]
members = ["a"]

[workspace.dependencies]
empty-library = {version="*", default_features=false}
```

and member "a":

```toml
[package]
name = "a"
version = "0.1.0"
edition = "2021"

[dependencies]
empty-library.workspace = true
```

and run `cargo fix --edition`.

### Possible Solution(s)

I think `cargo fix --edition` should also update these dependencies.

### Version

```text
cargo 1.85.0-nightly (4c39aaff6 2024-11-25)
release: 1.85.0-nightly
commit-hash: 4c39aaff66862cc0da52fe529aa1990bb8bb9a22
commit-date: 2024-11-25
host: aarch64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian 12.0.0 [64-bit]
```
