### ISSUE TITLE
usability: publish fails with `api errors: not a valid url: ` if `homepage=""`

### ISSUE THREAD

**Issue by Byron** [rust-lang/cargo#1490]
When publishing [google-apis-rs](https://github.com/Byron/google-apis-rs), I found a bug in the generator which would produce *Cargo.toml* files like this:

```toml
[package]

name = "google-dataflow1_b4"
version = "0.1.3+20150401"
authors = ["Sebastian Thiel <byronimo@gmail>"]
description = "A complete library to interact with dataflow (protocol v1b4)"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/dataflow1_b4"
homepage = ""
documentation = "http://byron.github.io/google-apis-rs/google-dataflow1_b4"
license = "MIT"
keywords = ["dataflow", "google", "protocol", "web", "api"]

[dependencies]
hyper = "*"
mime = "*"
yup-oauth2 = "*"
url = "*"
serde = "*"
serde_macros = "*"
```
Note the empty `homepage` string, which sneaked in there as the source material also contains an empty string field which wasn't explicitly excluded by me.

When publishing the file above one will see a relatively non-descript error like this:
```bash
cd gen/dataflow1_b4 && cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Uploading google-dataflow1_b4 v0.1.3+20150401 (file:///Users/byron/Documents/dev/rust/google-apis-rs/gen/dataflow1_b4)
api errors: not a valid url:
```

I think it would help if it would be explicit and say which field is empty, or ignore empty fields altogether.

### Meta

```bash
➜  google-apis-rs git:(master) ✗ cargo --version --verbose
cargo 0.0.1-pre-nightly (3499c8e 2015-04-05) (built 2015-04-05)
```
