### ISSUE TITLE
Target-gated dependencies not included in a workspace are "discovered" anyways

### ISSUE THREAD

**Issue by Radbuglet** [rust-lang/cargo#15023]
### Problem and Steps

As a minimum reproducible project, I have a workspace...

```toml
[workspace]
resolver = "2"
members = ["crates/entry"]
```

...and two crates `crates/entry` and `crates/dep`.

`crates/dep/src/lib.rs` contains the code:

```rust
compile_error!("`dep` included");
```

...in other words, I do not expect `dep` to be compiled.

Meanwhile, `crates/entry/Cargo.toml` contains...

```toml
[package]
name = "entry"
version = "0.1.0"
edition = "2021"

[target.'cfg(any())'.dependencies]
dep = { path = "../dep" }
```

Since the `cfg` is disabled, I'd expect `dep` not to be compiled but it seems to get compiled anyways...

```
% cargo check
    Checking dep v0.1.0 (crates/dep)
error: `dep` included
 --> crates/dep/src/lib.rs:1:1
  |
1 | compile_error!("`dep` included");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `dep` (lib) due to 1 previous error
```

If I comment out the `[target.'cfg(any())'.dependencies]` table entirely, the code does compile so `dep` is only being discovered as part of the dependency list for a target which is inactive.

The current workaround seems to be to mention `dep` explicitly in the `workspace.exclude` section of the workspace's `Cargo.toml`:

```toml
[workspace]
resolver = "2"
members = ["crates/entry"]
exclude = ["crates/dep"]
```

Is this a bug? It was certainly a little bit surprising to me.

### Version

```text
cargo 1.83.0 (5ffbef321 2024-10-29)
release: 1.83.0
commit-hash: 5ffbef3211a8c378857905775a15c5b32a174d3b
commit-date: 2024-10-29
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.1.0 [64-bit]
```
