### ISSUE TITLE
Building without unwinding support

### ISSUE THREAD

**Issue by yshui** [rust-lang/cargo#15146]
### Problem

So I am trying to make sure the code I build never unwinds. I am doing:

```toml
# Cargo.toml
[profile.release]
panic = "abort"

# .cargo/config.toml
[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
```

Yet cargo still builds and links `panic_unwind`, which in turn links `unwind`, and as a consequence links `libgcc_s.so`. Related to rust-lang/rust#82521, which is trying to solve the missing `libgcc_s` problem. Here we don't want to link any unwind library at all.

### Notes

Did a quick code search here, so this may be wrong. 

https://github.com/rust-lang/cargo/blob/f6514977efe8405f1433978d2e798a4428cdedac/src/cargo/core/compiler/standard_lib.rs#L26-L30

But it looks like cargo blindly adds `panic_unwind` to the list of libraries, whether it's needed or not.

### Version

```text

```
