### ISSUE TITLE
Support patch based on target

### ISSUE THREAD

**Issue by ahqsoftwares** [rust-lang/cargo#15153]
### Problem

For example, in the below manifest

```toml
[package]
name = "ahqstore-new"
version = "0.1.0"
description = "The Open Sourced App Store"
authors = ["AHQ Softwares"]
edition = "2021"

[lib]
name = "ahqstore_new_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tauri-plugin-ahqstore = { path = "../src-plugin" }
tauri-plugin-deep-link = "2"
tauri-plugin-os = "2"

[target.'cfg(windows)'.dependencies]
windows = { version = "=0.59", features = ["Win32_Graphics_Dwm"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"

[target.'cfg(mobile)'.patch.crates-io]
wry = { git = "https://github.com/ahqsoftwares/wry.git", branch = "patch-2" }
```

If the wry patch is used on any target except mobile, it won't compile due to different dependencies

### Proposed Solution

Support `target.*.patch.*`

**Comment by imlk0** [comment]
@ahqsoftwares 

I have got the same problem and I would like to share my workaround here, for those who come here.

I need to work with two crate, one is the original version(we call it `foo`) and another is a modified version for wasm (call it `foo-wasm`). So I crate a shim crate names `foo` in my cargo workspace, with the following dependencies

```toml
[target.'cfg(not(all(target_arch = "wasm32", target_vendor = "unknown", target_os = "unknown")))'.dependencies]
# The original version
foo = {git = "https://github.com/xxx/foo.git", tag = "v0.1.7", default-features = false}

[target.'cfg(all(target_arch = "wasm32", target_vendor = "unknown", target_os = "unknown"))'.dependencies]
# The wasm patched version
foo-wasm = {git = "https://github.com/yyyy/foo-wasm.git", tag = "v0.1.7", default-features = false}
```

and put the following code in the lib.rs
```rust
#[cfg(all(
    target_arch = "wasm32",
    target_vendor = "unknown",
    target_os = "unknown"
))]
pub use foo_wasm::*;

#[cfg(not(all(
    target_arch = "wasm32",
    target_vendor = "unknown",
    target_os = "unknown"
)))]
pub use foo::*;
```

Add following cargo.toml code in the package which requires `foo`
```toml
[patch.crates-io]
foo = {path = "../foo"}
```
