### ISSUE TITLE
Automatically register workspace members in `workspace.dependencies` in `cargo new`

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15180]
### Problem

In using a workspace, I'd like it to be easy to setup workspace members to be used with `workspace = true` which includes reducing the number of places I need to update paths as I move packages in the workspace.

### Proposed Solution

If you have the following workspace
```toml
[workspace]
```

and you run
```console
$ cargo new foo
```

You should get
```toml
[workspace]
members = ["foo"]

[workspace.dependencies]
foo = { path = "foo", version = "0.1.0" }
```

### Notes

[RFC 2906](https://rust-lang.github.io/rfcs/2906-cargo-workspace-deduplicate.html#no-longer-need-both-version-and-path-to-publish-to-cratesio) requested we implicitly add `version` when we see `path` which was rejected during stabilization.

#13453 requests we implicitly make workspace members available for `workspace = true` but this comes at many costs.
