### ISSUE TITLE
[feat] easy `LLVM_PROFILE_FILE` config for `cargo test`

### ISSUE THREAD

**Issue by loynoir** [rust-lang/cargo#15186]
### Problem

Below workspace config leads to `/path/to/project/crates/hello/target/xxx` under each member cargo toml dir, but not `/path/to/project/target/xxx` under top cargo toml dir.

`/path/to/project/.cargo/config.toml`

```toml
[env]
LLVM_PROFILE_FILE = "target/xxx"
```

Below workspace config leads to `target/xxx` under top cargo toml dir, but it is a hard coded config.

`/path/to/project/.cargo/config.toml`

```toml
[env]
LLVM_PROFILE_FILE = "/path/to/project/target/xxx"
```

### Proposed Solution

`/path/to/project/.cargo/config.toml`

```toml
[env]
LLVM_PROFILE_FILE = "${CARGO_CONFIG_PROJECT_CWD}/target/xxx"
```

Or maybe just add a new field ONLY for `cargo test`, as `LLVM_PROFILE_FILE` is not used in `cargo build`

```toml
[unstable]
profile-env-llvm-profile-file = true

[profile.test]
LLVM_PROFILE_FILE = "${CARGO_CONFIG_PROJECT_CWD}/target/xxx"
```

### Notes

related env design

https://code.visualstudio.com/remote/advancedcontainers/environment-variables
