### ISSUE TITLE
proc-macros used as build-depedencies and normal depedencies have features unified

### ISSUE THREAD

**Issue by Baptistemontan** [rust-lang/cargo#15251]
### Problem

If a package depends on a crate both as a dev-depedency and a normal depedency, and that crate pass feature flags to a macro, the features flags for the macro will be unified.

```toml
# workspace Cargo.toml
[workspace]
resolver = "2"
members = ["app", "common", "macros"]

[workspace.dependencies]
macros = { path = "./macros" }
common = { path = "./common" }
```

```toml
# app package Cargo.toml
[package]
name = "app"
version = "0.1.0"

[dependencies]
common = { workspace = true }

[build-dependencies]
common = { workspace = true, features = ["foo"] }
```

```toml
# common package Cargo.toml
[package]
name = "common"
version = "0.1.0"

[dependencies]
macros = { workspace = true }

[features]
default = []
foo = ["macros/foo"]
```

```toml
# macros package Cargo.toml
[package]
name = "macros"
version = "0.1.0"

[lib]
proc-macro = true

[features]
default = []
foo = ["macros/foo"]
```

When compiling the `app` package, the `common` package will have the "foo" feature enabled in the build.rs script (as expected), but will not during the normal build (as expected), BUT the `macros` package will have the "foo" feature enabled at both.

This create an issue when the `macros` package expect the `common` package to also have the feature enabled (to use some exported items for exemple).

### Version

```text
cargo 1.86.0-nightly (2928e3273 2025-02-07)
release: 1.86.0-nightly
commit-hash: 2928e32734b04925ee51e1ae88bea9a83d2fd451
commit-date: 2025-02-07
host: x86_64-pc-windows-msvc
libgit2: 1.9.0 (sys:0.20.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:Schannel)
os: Windows 10.0.26100 (Windows 11 Professional) [64-bit]
```
