### ISSUE TITLE
Cargo Error: Duplicate Dependencies with Different Names and Versions Using Wildcard Version Selector

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/cargo#15261]
## Issue Description

In my `Cargo.toml`, I declared two dependencies for the same crate (`shadow-rs`) under different names, with one using a wildcard version selector (`*`). The configuration is as follows:

```toml
[package]
name = "rust-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
shadow-rs = "0.38.0"
shaodw-rs1 = { package = "shadow-rs", version = "*" }
```

When running `cargo build`, I encountered the following error:

```
error: the crate `rust-demo v0.1.0 (/Users/baoyachi/RustroverProjects/rust-demo)` depends on crate `shadow-rs v0.38.1` multiple times with different names
```

The latest version of `shadow-rs` is actually `1.0.1`, not `0.38.1`.

## Expected Behavior

I expected `shaodw-rs1` to use the wildcard version selector (`*`) to fetch the latest version (e.g., `1.0.1`) without causing conflicts with `shadow-rs`.

## Actual Behavior

Cargo throws an error indicating that the same crate is being included multiple times with different names and versions.

## Steps to Reproduce

1. Create a new Rust project:
   ```bash
   cargo new rust-demo
   cd rust-demo
   ```

2. Add the following dependencies to `Cargo.toml`:
   ```toml
   [dependencies]
   shadow-rs = "0.38.0"
   shaodw-rs1 = { package = "shadow-rs", version = "*" }
   ```

3. Run `cargo build`:
   ```bash
   cargo build
   ```

You will see the error message mentioned above.

## Additional Information

- If I specify the same version for both dependencies, the issue does not occur. For example:
  ```toml
  [dependencies]
  shadow-rs = "0.38.0"
  shaodw-rs1 = { package = "shadow-rs", version = "1.0.1" }
  ```
  
- If I remove one of the dependencies, the issue also does not occur.

## Environment

- **Operating System**: macOS (but likely reproducible on other platforms)
- **Rust Version**: stable-x86_64-apple-darwin (default installation)
- **Cargo Version**: cargo 1.85.0 (d73d2caf9 2024-12-31)

## Questions

1. Is this behavior expected when using wildcard version selectors with duplicate dependencies?
2. Is there a recommended way to handle scenarios where different names are needed for the same crate but with specific version requirements?

Thank you for your attention to this matter. Any insights or suggestions would be greatly appreciated.
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text

```

**Comment by weihanglo** [comment]
Thanks for the issue report!

> Is this behavior expected when using wildcard version selectors with duplicate dependencies?

The dependency resolver in [Cargo has some heuristics](https://doc.rust-lang.org/nightly/cargo/reference/resolver.html), including

* Pick up the latest possible version.
* Reuse the existing version in dependency graph, if compatible.

If I understand correctly, you expected the first one to work, but the latter heuristic won. This is IMO an expected behavior since Cargo tries really hard backtracking and unifying verisons. Wildcard requirement means "any versions", so in your case `shaodw-rs1` was coerced to a "0.38.0" compatible version.

> Is there a recommended way to handle scenarios where different names are needed for the same crate but with specific version requirements?

If they are SemVer-incompatible, for example 0.38.0 and 1.0.1, then they can co-exist with renames. Within a SemVer-compatible range, package versions will always be unified to one version, otherwise it is a bug and cargo will refuse to compile.

**Comment by weihanglo** [comment]
> * If I specify the same version for both dependencies, the issue does not occur. For example:
>       [dependencies]
>       shadow-rs = "1.0.1"
>       shaodw-rs1 = { package = "shadow-rs", version = "1.0.1" }

BTW, this fails as well.

```
error: the crate `foo v0.1.0 (/projects/foo)` depends on crate `shadow-rs v1.0.1` multiple times with different names
```

**Comment by weihanglo** [comment]
If you still have questions, feel free to ask.

**Comment by baoyachi** [comment]
@weihanglo 
What I expected was this way use `*` to pull up to the latest version 1.0.1, but currently it seems that Cargo has not done so.
```toml
[dependencies]
shadow-rs = "0.38.0"
shaodw-rs1 = { package = "shadow-rs", version = "*" }
```
