### ISSUE TITLE
[feat] cargo config preference option for `-- --nocapture`

### ISSUE THREAD

**Issue by loynoir** [rust-lang/cargo#15430]
### Problem

Current `cargo test ... -- --nocapture` cannot written in cargo config alias.

Would be nice to add cargo config preference option for `-- --nocapture`.

### Proposed Solution

```toml
[test]
default_nocapture = true
```

**Comment by epage** [comment]
> Current cargo test ... -- --nocapture cannot written in cargo config alias.

It can't?  What happens when you try?

> Would be nice to add cargo config preference option for -- --nocapture.

There is the question of how we should respond to custom test harnesses.  They may or may not support this flag.  I wonder if this should wait until we better integrate `cargo test` and `libtest` and allow users to tell cargo the level of integration their custom test harness has, so we know if `--nocapture` is supported or not.

Could you explain why you would want it in config?  `--nocapture` can be quite noisy and even be hard to read with concurrent test output.  It seems like having it in a persistent config would be less than ideal.

**Comment by loynoir** [comment]
Both not working, would be nice to be vvverbose.

```toml
[test]
nocapture = true

[alias]
tv = "test $@ -- --nocapture --color always"
```
