### ISSUE TITLE
Hang while updating git repository `https://gitlab.com/jD91mZM2/no-std-compat`

### ISSUE THREAD

**Issue by HactarCE** [rust-lang/cargo#15481]
### Problem

While fetching from <https://gitlab.com/jD91mZM2/no-std-compat>, cargo hangs and is unable to fetch the dependency.

### Steps

1. `git clone https://github.com/HactarCE/rhaideptest`, which contains the following `Cargo.toml`:

```toml
[package]
name = "rhaideptest"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
no-std-compat = { git = "https://gitlab.com/jD91mZM2/no-std-compat" }
```

2. Run `cargo check`
3. Observe that the build hangs on "updating git repository `https://gitlab.com/jD91mZM2/no-std-compat`"

### Possible Solution(s)

I have no idea why this happens or how to fix it.

### Notes

Cloning the repository via command line `git` works fine. Using the crate via crates.io works fine.

I tried to work around this bug by adding this patch to fetch from crates.io instead of GitLab:

```toml
[patch."https://gitlab.com/jD91mZM2/no-std-compat"]
no-std-compat = { version = "0.4.1", registry = "crates-io" }
```

### Version

```text
cargo 1.86.0 (adf9b6ad1 2025-02-28)
release: 1.86.0
commit-hash: adf9b6ad14cfa10ff680d5806741a144f7163698
commit-date: 2025-02-28
host: aarch64-apple-darwin
libgit2: 1.9.0 (sys:0.20.0 vendored)
libcurl: 8.7.1 (sys:0.4.79+curl-8.12.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.4.1 [64-bit]
```

**Comment by epage** [comment]
The reproduction case can be simplified down to:
```toml
[package]
name = "rhaideptest"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
no-std-compat = { git = "https://gitlab.com/jD91mZM2/no-std-compat" }
```

When cloning that repo, I noticed that it gave me a redirect message.

If I change to actual repo, the problem is no longer reproducible
```toml
[package]
name = "rhaideptest"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
no-std-compat = { git = "https://gitlab.com/jD91mZM2/no-std-compat.git" }
```

Whats interesting is if you then switch the URL back to the original, it now works.  We must be normalizing these URLs to treat the checkouts the same.

Unsure why the original reproduction case has a patch for `https://gitlab.com/jD91mZM2/no-std-compat`.  If I remove the patch, I'm able to clone things.  I looked at this in case somewhere in the deps, the pre-redirected URL is being used out of curiosity for it somehow working.
