### ISSUE TITLE
Feature enabled, but dependent crate not added

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/cargo#15490]
### Problem

Feature enabled, but dependent crate not added

Using build-dependencies, dev-dependencies, and dependencies in the dependency graph

### Steps

1. Run this sh
   ```sh
   #!/usr/bin/bash
   set -ex

   until rm -rf rustc-test; do :; done

   cargo new rustc-test && cd "$_"
   echo > src/lib.rs
   echo '[workspace]' >> Cargo.toml


   cargo new --lib subcrate && pushd "$_"
   cargo add quote --build --optional
   echo 'default = ["quote"]' >> Cargo.toml
   echo > src/lib.rs
   echo '#[cfg(feature = "quote")] extern crate quote as _;' >> build.rs
   echo 'fn main() {}' >> build.rs
   popd


   cargo new --lib mid && pushd "$_"
   cargo add --path ../subcrate --dev --no-default-features
   echo '[features]' >> Cargo.toml
   echo 'default = ["subcrate/quote"]' >> Cargo.toml
   echo > src/lib.rs
   popd


   cargo add --path subcrate --no-default-features
   cargo add --path mid
   echo > src/lib.rs
   echo '[features]' >> Cargo.toml
   echo 'default = ["subcrate/quote"]' >> Cargo.toml

   cargo test --workspace --tests
   cargo test --workspace --no-default-features --tests # failed
   ```

   Output:

   ```
   $ bash rustc-test.sh
   + rm -rf rustc-test
   + cargo new rustc-test
       Creating binary (application) `rustc-test` package
   note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
   + cd rustc-test
   + echo
   + echo '[workspace]'
   + cargo new --lib subcrate
       Creating library `subcrate` package
         Adding `subcrate` as member of workspace at `/home/lrne/Project/Rust/rustc-test`
   note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
   + pushd subcrate
   ~/Project/Rust/rustc-test/subcrate ~/Project/Rust/rustc-test
   + cargo add quote --build --optional
       Updating `rsproxy-sparse` index
         Adding quote v1.0.40 to optional build-dependencies
                Features:
                + proc-macro
         Adding feature `quote`
       Updating `rsproxy-sparse` index
        Locking 3 packages to latest Rust 1.86.0 compatible versions
   + echo 'default = ["quote"]'
   + echo
   + echo '#[cfg(feature = "quote")] extern crate quote as _;'
   + echo 'fn main() {}'
   + popd
   ~/Project/Rust/rustc-test
   + cargo new --lib mid
       Creating library `mid` package
         Adding `mid` as member of workspace at `/home/lrne/Project/Rust/rustc-test`
   note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
   + pushd mid
   ~/Project/Rust/rustc-test/mid ~/Project/Rust/rustc-test
   + cargo add --path ../subcrate --dev --no-default-features
         Adding subcrate (local) to dev-dependencies
                Features as of v0.1.0:
                - quote
   + echo '[features]'
   + echo 'default = ["subcrate/quote"]'
   + echo
   + popd
   ~/Project/Rust/rustc-test
   + cargo add --path subcrate --no-default-features
         Adding subcrate (local) to dependencies
                Features:
                - quote
   + cargo add --path mid
         Adding mid (local) to dependencies
   + echo
   + echo '[features]'
   + echo 'default = ["subcrate/quote"]'
   + cargo test --workspace --tests
      Compiling proc-macro2 v1.0.95
      Compiling unicode-ident v1.0.18
      Compiling mid v0.1.0 (/home/lrne/Project/Rust/rustc-test/mid)
      Compiling quote v1.0.40
      Compiling subcrate v0.1.0 (/home/lrne/Project/Rust/rustc-test/subcrate)
      Compiling rustc-test v0.1.0 (/home/lrne/Project/Rust/rustc-test)
       Finished `test` profile [unoptimized + debuginfo] target(s) in 3.96s
        Running unittests src/lib.rs (target/debug/deps/mid-96e1286cb7a7970e)

   running 0 tests

   test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

        Running unittests src/lib.rs (target/debug/deps/rustc_test-a1becec4804655f8)

   running 0 tests

   test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

        Running unittests src/main.rs (target/debug/deps/rustc_test-1a1fa43b8d3282e2)

   running 0 tests

   test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

        Running unittests src/lib.rs (target/debug/deps/subcrate-94541aa21b80c44f)

   running 0 tests

   test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   + cargo test --workspace --no-default-features --tests
      Compiling subcrate v0.1.0 (/home/lrne/Project/Rust/rustc-test/subcrate)
   error[E0463]: can't find crate for `quote`
    --> subcrate/build.rs:1:27
     |
   1 | #[cfg(feature = "quote")] extern crate quote as _;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

   For more information about this error, try `rustc --explain E0463`.
   error: could not compile `subcrate` (build script) due to 1 previous error
   ```

### Version

```text
cargo 1.86.0 (adf9b6ad1 2025-02-28)
release: 1.86.0
commit-hash: adf9b6ad14cfa10ff680d5806741a144f7163698
commit-date: 2025-02-28
host: aarch64-unknown-linux-gnu
libgit2: 1.9.0 (sys:0.20.0 vendored)
libcurl: 8.12.0-DEV (sys:0.4.79+curl-8.12.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux [64-bit]
```

**Comment by epage** [comment]
Features referencing dev-dependencies is something that has had mixed results
- #9060
- #1596

**Comment by epage** [comment]
My current reproduction steps
```console
$ cargo init --lib
$ cargo new mid --lib
$ cargo new subcrate --lib
```
`Cargo.toml`:
```toml
[workspace]
resolver = "2"
members = [ "mid","subcrate"]

[package]
name = "rustc-test"
version = "0.1.0"
edition = "2024"

[dependencies]
mid = { version = "0.1.0", path = "mid", features = ["quote"] }
subcrate = { version = "0.1.0", path = "subcrate", default-features = false }

[features]
quote = ["subcrate/quote"]
```
`mid/Cargo.toml`:
```toml
[package]
name = "mid"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
subcrate = { path = "../subcrate", default-features = false }

[features]
quote = ["subcrate/quote"]

```
`subcrate/Cargo.toml`:
```toml
[package]
name = "subcrate"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = { version = "1.0.40", optional = true }
```
