### ISSUE TITLE
Suggest workspace shorthands for boolean dependencie

### ISSUE THREAD

**Issue by 0xsot** [rust-lang/cargo#15505]
Error complains about a boolean but only mentions version strings or tables with version = "x.y.z" when you accidentally write:

```toml
[dependencies]
crc32fast = true
```
Cargo reports:
```log
invalid type: boolean `true`, expected a version string like "0.9.8"
or a detailed dependency like { version = "0.9.8" }
in `dependencies.crc32fast`
```
It would be more helpful if the error message also suggested the workspace shorthand. Both of these are valid ways to pull from your workspace
```toml
crc32fast = { workspace = true }
crc32fast.workspace = true
```

### Proposed behavior:

When a boolean is found, append a note pointing out the two valid workspace forms
```log
invalid type: boolean `true`, expected a version string like "0.9.8"
or a detailed dependency like { version = "0.9.8" }
in `dependencies.crc32fast`.

if you meant to use a workspace member, you can write
  crc32fast = { workspace = true }
or
  crc32fast.workspace = true
```
