### ISSUE TITLE
Cargo workspace member dep version ranges

### ISSUE THREAD

**Issue by TroyKomodo** [rust-lang/cargo#15526]
### Problem

In cargo workspace

crates `{a, b, c}`

`a requires: b >= 1.0`

`c requires: b >= 1.1`

`b is at 1.2.0`

how can I specify these versioning conditions when publishing to crates io while using `workspace = true`.
Currently workspace deps override the `version` config value.

### Proposed Solution

Have a new config `member = true` which allows you to reference workspace members directly without using a workspace dep and then allow that member to have version ranges and if not provided use the current version of the member.

I don't like the idea of paths because it makes it increasingly messy. I think its silly we need to declare workspace members as part the workspace-deps list.

**Comment by epage** [comment]
> Allow for a new template in the path syntax to resolve to the root of the workspace b = { path = "{root}/crates/b" }

That is supported through the unstable `path-bases` feature, see #14355  and https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#path-bases

> Lift the restriction of workspace version inheritance and instead allow workspace deps to override the version.

This would allow you to reuse the path but reduce have a custom version range, right?

**Comment by TroyKomodo** [comment]
Yes that's correct.

**Comment by epage** [comment]
Variants of `member = true` include:
- Auto-insert the version into path dependencies, see https://github.com/rust-lang/cargo/issues/8415#issuecomment-1097412783
- Don't require a `workspace.dependencies` entry for workspace members, see #13453

Those don't handle the problem of when you want to intentionally have your version requirements diverge.

One part of #13453 that has particular relevance for `member = true` is that both can only fully process dependencies after the workspace is fully loaded which is not the case today.  To support this, we'd need to add extra phases of parsing manifests and this was a major reason #13453 was rejected.

As an alternative to #13453, we proposed #15180 but that still has the problem of centralizing the version requirements.

**Comment by epage** [comment]
To avoid making assumptions, what is your use case for having version requirements diverge?  Do you have any strategy to ensure your version requirements are not too low / stale?

**Comment by TroyKomodo** [comment]
> To avoid making assumptions, what is your use case for having version requirements diverge? Do you have any strategy to ensure your version requirements are not too low / stale?

In our workspace if we make a change to a member because we need it in another member we then bump that version in place. We also have a publish time check to detect if any version is too low since we build with the version minimums.

**Comment by epage** [comment]
> We also have a publish time check to detect if any version is too low since we build with the version minimums.

Could you provide more details on this check?

**Comment by TroyKomodo** [comment]
> > We also have a publish time check to detect if any version is too low since we build with the version minimums.
> 
> Could you provide more details on this check?

It's a wrapper around `-Z direct-minimal-versions` https://crates.io/crates/cargo-minimal-versions

**Comment by epage** [comment]
Ah, I was not aware that had `--detach-path-deps` which is what I assume you are using for this.

**Comment by TroyKomodo** [comment]
i have since written a custom script to help pin these versions.

Since direct-minimal-versions has some issues namely it is too eager to select a minimal version if a sub dependency bumps up a version. This is the ideal solution but its too annoying to fix these issues.

So what we have done instead is a hybrid of `direct-minimal-versions` except instead of every dependency we only do it with workspace members. 

The following:

`Cargo.toml`:

```toml
[workspace]
members = ["crates/*"]
```
`crates/a/Cargo.toml`

```toml
[package]
name = "a"

[dependencies]
b = { version = "1.0", path = "../b" }
```
`crates/c/Cargo.toml`

```toml
[package]
name = "c"

[dependencies]
version = { version = "1.2.0", path = "../b" }
```

`crates/b/Cargo.toml`

```toml
[package]
name = "b"
version = "1.2.0"
```

Gets transformed into:

Assume that `b` is published for `[1.0.0, 1.1.0]`

`Cargo.toml`:

```toml
[workspace]
members = ["crates/*"]
```

`crates/a/Cargo.toml`

```toml
[package]
name = "a"

[dependencies]
b = { version = "=1.0.0" }
```

`crates/c/Cargo.toml`

```toml
[package]
name = "c"

[dependencies]
b = { version = "=1.2.0", path = "../b" }
```

`crates/b/Cargo.toml`

```toml
[package]
name = "b"
version = "1.2.0"
```

Then to test this I run.

* test for a 
```bash
RUSTC_BOOTSTRAP=1 cargo -Zunstable-options -Zpackage-workspace publish --dry-run --allow-dirty --lockfile-path /tmp/Cargo.lock --locked -p a
```

* test for b

```shell
RUSTC_BOOTSTRAP=1 cargo -Zunstable-options -Zpackage-workspace publish --dry-run --allow-dirty --lockfile-path /tmp/Cargo.lock --locked -p b
```

* test for c

```shell
RUSTC_BOOTSTRAP=1 cargo -Zunstable-options -Zpackage-workspace publish --dry-run --allow-dirty --lockfile-path /tmp/Cargo.lock --locked -p c -p b
```
