### ISSUE TITLE
Make Optional Dependencies More Ergonomic

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/cargo#1555]
Cargo should be able to express the idea of: "I want to depend on this package iff whoever depends on me is already depending on that package." This is especially useful because rust doesn't have orphan instances.

Specifically, I want to add a quickcheck `Arbitrary` instance to `Iobuf`. However, I don't want to add the dependency on Quickcheck for people not using it (non-test executables, for most people). It would be nice if it "just worked", perhaps in a new section:

```
[optional-dependencies]
quickcheck = "*"
```

And then anyone that depends on iobuf can have the quickcheck instances built for tests by including quickcheck in their dev-dependencies.

**Comment by alexcrichton** [comment]
Are you familiar with inline table syntax for TOML? I think this is much more ergonomic than a new section:

```toml
[dependencies]
quickcheck = { optional = true }
```

**Comment by cgaebel** [comment]
I didn't know about that syntax, but it sounds good to me. I care much more about the "magic, just-works" behavior than the syntax. :)

**Comment by alexcrichton** [comment]
Ok, in that case I'm going to close this as the inline table syntax should be much more ergonomic than a whole new section.

**Comment by cgaebel** [comment]
Wait, this feature exists already? How do I express "I want to depend on this package iff whoever depends on me is already depending on that package." ?

**Comment by alexcrichton** [comment]
Ah I believe I have misread.

**Comment by erickt** [comment]
While this doesn't happen automatically, I believe this can currently be expressed with:

crate foo:

```toml
[dependencies]
quickcheck = { version = "*", optional = true }
```

crate bar:

```
[features]
with-quickcheck = ["quickcheck", "foo/quickcheck"]

[dependencies]
foo = "*"
quickcheck { version = "*", optional = true }
```

Then for the downstream, if they're using quickcheck, they can opt into `bar` using quickcheck via:

```toml
[features]
with-quickcheck = ["quickcheck", "bar/with-quickcheck"]

[dependencies]
bar = "*"
quickcheck = { version = "*", optional = true }
```

**Comment by Storyyeller** [comment]
I think this would be very useful. When writing a library with new types, it often makes sense to impl traits from other popular libraries for interoperability. But I don't want to pull in all those extra dependencies if the user isn't using them.

**Comment by mehcode** [comment]
This would be awesome. :100: 

```toml
[dependencies]
diesel = { version = "0.10.0", features = ["postgres", "uuid"] }
diesel_codegen = { version = "0.10.0", features = ["postgres", "dotenv"] }
uuid = { version = "0.4.0", features = ["serde"] }
serde = "0.9"
dotenv = "*"
```

Wouldn't it be simply beautiful if the above could instead be: 

```rust
[dependencies]
diesel = { version = "0.10.0", features = ["postgres"] }
diesel_codegen = { version = "0.10.0", features = ["postgres"] }
uuid = "0.4.0"
serde = "0.9"
dotenv = "*"
```

Automatic use of features (the optional crate kind) that I have as explicit dependencies would be a very ergonomic addition.
