### ISSUE TITLE
Unable to use workspace dependency in patch

### ISSUE THREAD

**Issue by tigerros** [rust-lang/cargo#15568]
I tried this code:

```toml
# empty project
[workspace.dependencies]
shakmaty = { git = "https://github.com/niklasf/shakmaty", branch = "master", default-features = false }

[patch.crates-io]
shakmaty = { workspace = true }
```

I expected to see this happen: dependencies that use shakmaty from crates.io get replaced by the git version.

Instead, this happened:

```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  dependency (shakmaty) specified without providing a local path, Git repository, version, or workspace dependency to use
```

The error says I can use a workspace dependency.

### Meta

`rustc --version --verbose`:
```
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-pc-windows-msvc
release: 1.86.0
LLVM version: 19.1.7
```

</p>
</details>

**Comment by epage** [comment]
We should fix that error message to not mention workspace dependencies.

Could you help me understand your motivation for wanting to use a workspace dependency in a patch?

**Comment by epage** [comment]
Ok, so you are patching a transitive dependency.  You mentioned you want the version/source to be in `workspace.dependencies`.  What value do you expect to gain from that?

Is this patch considered to be temporary or will you be maintaining it long term?

**Comment by epage** [comment]
`[patch]` is only read in the root of the workspace, so there shouldn't be a need for duplicating a patches source.

We've had a lot of back and forth.  If there is more, it might be good to provide a complete but minimal reproduction case which might help clarify some of the points of what you are doing.

**Comment by weihanglo** [comment]
There is one nasty difficulty of supporting this: `[patch]` can also be in Cargo configuration (`.cargo/config.toml`), and configuration has no knowledge of what workspace is. That said, it can be interpreted as "whichever workspace cargo is building."

On the other hand, while what you're doing is not disallowed, I would suggest using crates.io dependencies in `workspace.dependencies`, and git repo `patch` in patch section instead. Benefit of this pattern:

* Your package can still be able to publish to crates.io.
* It is easier to spot whether you're using the same version of `shakmaty` across the entire dependency graph. Git dependencies are treated as completely different, and you might have chance getting duplicate versions of `shakmaty`.

**Comment by weihanglo** [comment]
> > Your package can still be able to publish to crates.io.
> 
> How can that be? I thought crates.io crates can't have git dependencies. I rely on features present only in the git repo.

To clarify, I meant something like

```toml
[workspace.dependencies]
shakmaty = "0.27.3"


[patch.crates-io]
shakmaty = { git = "https://github.com/niklasf/shakmaty", branch = "master", default-features = false }
```

So your package will be ready to publish after shakmaty release a new version and you bump it. You don't need to modify the dependency declaration again.
