### ISSUE TITLE
Lint if workspace dependency inheritance isn't used

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15578]
### What it does

If a package has a dependencies entry that specifies a source besides `workspace = true`, it fires

See also rust-lang/rust-clippy#10306

### Advantage

For projects that want to be consistent on their dependencies across a workspace

### Drawbacks

- #12162
- Packages cannot have different version requirements (#15526)

### Example

```toml
[dependencies]
serde = "1"
```

Could be written as:

```toml
[workspace.dependencies]
serde = "1"

[dependencies]
serde.workspace = true
```
