### ISSUE TITLE
Lint if workspace lints are available but not inherited

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15579]
### What it does

See also rust-lang/rust-clippy#11933

### Advantage

- Avoid accidents in forgetting to inherit

### Drawbacks

- There may be cases where avoiding inheritance is intentional

### Example

```toml
[workspace]

[workspace.lints]

[package]
```

Could be written as:

```toml
[workspace]

[workspace.lints]

[package]

[lints]
workspace = true
```
