### ISSUE TITLE
Lint that package names only use `_` / only use `-`

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15585]
### What it does

Mutually exclusive (`restriction`) lints to ensure `package.name` have consistent names

I'm suggesting we add both as we are not currently opinionated on this

### Advantage

Help ensure consistency throughout a project

### Example

```toml
[package]
name = "foo-bar"
```

Could be written as:

```toml
[package]
name = "foo_bar"
```
