### ISSUE TITLE
Lint for redundant feature names

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15580]
### What it does

Checks for feature names with prefix `use-`, `with-` or suffix `-support`

See also https://rust-lang.github.io/rust-clippy/master/index.html?groups=cargo#/redundant_feature_names?groups=cargo

### Advantage

These prefixes and suffixes have no significant meaning.

### Example

```toml
[features]
default = ["use-abc", "with-def", "ghi-support"]
use-abc = []  // redundant
with-def = []   // redundant
ghi-support = []   // redundant
```

Could be written as:

```toml
[features]
default = ["abc", "def", "ghi"]
abc = []
def = []
ghi = []
```
