### ISSUE TITLE
Lint that binary names are kebab case

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15586]
### What it does

Lints that the `[[bin]]` `name` (explicit or inferred) is kebab case

See also #14439.

### Advantage

This matches common platform conventions

### Drawbacks

There may be existing conventions people are trying to match

### Example

```toml
[[bin]]
name = "foo_bar"
```
or `src/bin/foo_bar/main.rs`

Could be written as:

```toml
[[bin]]
name = "foo-bar"
```
or `src/bin/foo-bar/main.rs`
