### ISSUE TITLE
Lint that a version requirement is lower than what is currently in `Cargo.lock`

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15583]
### What it does

Lint when a dependency version requirement is lower than the resolved dependencies version.

### Advantage

- Low effort way of ensuring version requirements are not too low

### Drawbacks

- Someone can verify their version requirements a different way
- Even if someone is using this for helping with version requiirements, there are times where they want to raise the version requirements (e.g. testing latest)

### Example

```toml
[dependencies]
serde = "1.0.0"
```

Could be written as:

```toml
[dependencies]
serde = "1.0.216"
```
