### ISSUE TITLE
Lint that feature names only use `_` / only use `-`

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15584]
### What it does

Mutually exclusive (`restriction`) lints to ensure all `[features]` tables have consistent lint names

I'm suggesting we add both as we are not currently opinionated on this

### Advantage

Help ensure consistency throughout a project

### Drawbacks

docs.rs has special handling for `_` prefixed lints

### Example

```toml
[features]
foo-bar = []
```

Could be written as:

```toml
[features]
foo_bar = []
```
