### ISSUE TITLE
Lint for negative feature names

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15581]
### What it does

Checks for negative feature names with prefix `no-` or `not-`

See also https://rust-lang.github.io/rust-clippy/master/index.html?groups=cargo#negative_feature_names

### Advantage

Features are supposed to be additive, and negatively-named features violate it.

### Example

```toml
[features]
default = []
no-abc = []
not-def = []

```

Could be written as:

```toml
[features]
default = ["abc", "def"]
abc = []
def = []
```
