### ISSUE TITLE
Lint on unused workspace dependencies

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#15582]
### What it does

A [[workspace.dependencies]](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) was declared, but not actually used anywhere in the workspace.

See also https://embarkstudios.github.io/cargo-deny/checks/bans/diags.html#unused-workspace-dependency

### Advantage

- Avoid distraction / noise in the workspace

### Example

```toml
[workspace.dependencies]
serde = "1"

[dependencies]
```

Could be written as:

```toml
[workspace.dependencies]

[dependencies]
```
