### ISSUE TITLE
Allow path dependencies to point to "virtual manifests"

### ISSUE THREAD

**Issue by jrose-signal** [rust-lang/cargo#15606]
### Problem

It's not too uncommon to download out a library dependency locally, make a change to the local copy, and test it using your client package. Cargo supports this by either rewriting the dependency to use `path = "path/to/local-copy/"`, or using a `[patch]` section to override the source with a similar `path` key.

However, if the client packages uses *several* libraries from the same owner, developed in a common workspace, this process becomes extra manual, because every dependency needs a bespoke path into the checkout. If there have been semver changes, there's not even an option to only override the libraries you need and continue getting the rest from the usual source (probably crates.io); you have to list any you use.

```toml
# Can't write
[patch.crates-io]
boring = { path = "../boring" }
tokio-boring = { path = "../boring" }

# Instead you have to write
[patch.crates-io]
boring = { path = "../boring/boring" }
tokio-boring = { path = "../boring/tokio-boring" }

# Even though you can write
[patch.crates-io]
boring = { git = "https://github.com/signalapp/boring" }
tokio-boring = { git = "https://github.com/signalapp/boring" }
```

### Proposed Solution

Like `git` dependencies, allow `path` dependencies to refer to virtual manifests. This would allow overriding a slew of path dependencies using find/replace / multi-cursor editing and would avoid having to learn about the internal structure of a dependency's workspace.

### Notes

It's clear that Cargo already supports at least some of this, because if a dependency crate depended on as `path = "../local-copy/dep"` has `indirect-dep.workspace = true` in its *own* Cargo.toml, that's correctly found in `../local-copy/Cargo.toml`, not `./Cargo.toml`.

#11587 is close to this, but not quite the same; they didn't realize there was a syntax to accomplish what they wanted, while I'm suggesting that syntax can be improved. (And *not* suggesting that a single entry in the `[patch]` table should affect multiple dependency packages; that's a separable discussion.)
