### ISSUE TITLE
[config feature] revert source.<name>.replace-with in a project directory

### ISSUE THREAD

**Issue by Etavioxy** [rust-lang/cargo#15618]
### Problem

config `"source.<name>.replace-with"` can't be revert.

I use this in global scope (~/.cargo/config.toml)

```toml
[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
```

I tried to revert this source change in a specific project for using the official 'crates-io' source. So I use this

```toml
# ~/project/.cargo/config.toml
[source.crates-io]
replace-with = ""
```

It goes wrong

```
Caused by:
could not find a configured source with the name `` when attempting to lookup `crates-io` 
```
