### ISSUE TITLE
"invalid character `'.'` in crate name" when doing cargo run

### ISSUE THREAD

**Issue by Mutoxicated** [rust-lang/cargo#15665]
I'm trying to create a web page with github pages and rust, so i created the repository "mutoxicated.github.io". Cargo won't let me compile my code though.

This is my Cargo.toml 

```toml
[package]
name = "tenet"
edition = "2024"

[dependencies]
actix-web = "4.11.0"

[[bin]]
name = "mutoxicated.github.io"
path = "src/main.rs"
```

I created a blank issue but I'm not sure if this is a bug or meant to be like that. If it's the former I'm willing to help to fix it, otherwise I would like to know if there is a workaround to this.

**Comment by weihanglo** [comment]
```toml
[[bin]]
name = "mutoxicated.github.io"
path = "src/main.rs"
```

Did you plan to create a binary executable named `mutoxicated.github.io`? Note that `cargo init` infers the binary from the directory name, so I guess that was why it was set like that.

This is intended. Simply change the name of the bin could fix that. Otherwise check out the [Different binary name](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#different-binary-name) unstable feature.
