### ISSUE TITLE
dep/dev-dep cycle causes doc tests to fail

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1686]
```
.
├── Cargo.toml
├── src
│   └── lib.rs
└── sub1
    ├── Cargo.toml
    └── src
        └── lib.rs

3 directories, 4 files
```

## Cargo.toml
```toml
[package]
name = "recursive"
version = "0.1.0"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]

[dev-dependencies]
sub1 = { path = "sub1" }
```

## src/lib.rs
```rust
//! ```rust
//! extern crate sub1;
//! ```

#[cfg(test)]extern crate sub1;
```

## sub1/Cargo.toml

```toml
[package]
name = "sub1"
version = "0.1.0"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]

[dependencies]
"recursive" = { path = ".." }
```

## sub1/src/lib.rs
```rust
extern crate recursive;
```

---

Running `cargo test` inside `sub1` gives:

```
   Compiling recursive v0.1.0 (file:///home/huon/projects/test-rust/recursive)
   Compiling sub1 v0.1.0 (file:///home/huon/projects/test-rust/recursive)
     Running target/debug/recursive-bdc6bf679eadc42f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests recursive

running 1 test
test _0 ... FAILED

failures:

---- _0 stdout ----
	<anon>:2:5: 2:23 error: can't find crate for `recursive` which `sub1` depends on
<anon>:2     extern crate sub1;
             ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
thread '_0' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:211



failures:
    _0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

That is, only the doc test is failing.
