### ISSUE TITLE
Dependencies are pulled in even if behind a feature

### ISSUE THREAD

**Issue by twittner** [rust-lang/cargo#1805]
If an optional, feature-activated dependency is also listed under `dev-dependencies` it will be pulled in by `cargo build` even without the feature being requested:

```toml
[package]
name    = "test"
version = "0.1.0"
authors = ["user@nowhere.net"]

[features]
foo = ["quickcheck"]

[dependencies.quickcheck]
optional = true

[dev-dependencies]
quickcheck = "*"
```

```
$ cargo build
   Compiling libc v0.1.8
   Compiling rand v0.3.8
   Compiling log v0.3.1
   Compiling quickcheck v0.2.20
   Compiling test v0.1.0 (file:///tmp/test)
```

Removing the `dev-dependencies` section builds the package as expected:

```
$ cargo clean
$ cargo build
   Compiling test v0.1.0 (file:///tmp/test)
```

**Edit**: cargo is at version 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-12)
