### ISSUE TITLE
One invalid crate-type value causes cargo to ignore all crate-type settings

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1900]
```toml
[package]
name = "testlib"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]

[lib]
crate-type = ["dylib", "asdf"]
```

With the above `Cargo.toml`, cargo doesn't emit any warnings/errors, and just builds into `libtestlib.rlib`. I would expect cargo to instead build all valid crate types, and either ignore or emit a warning for any invalid crate-type values.
