### ISSUE TITLE
Optional dependencies cannot enable features

### ISSUE THREAD

**Issue by nox** [rust-lang/cargo#1925]
In crate X, with an optional dependency A and a mandatory dependency B of X, the feature A associated to the former cannot enable a feature with the same name in B. This means an additional feature bearing a different name must be introduced, making things messy.

**Comment by nox** [comment]
Use case:

I am adding SIMD optimisations to rust-encoding. I want the feature to be named "simd" and to enable the same feature in the internal crate encoding-types.

```toml
[features]
simd = ["encoding-types/enable-simd"]

[dependencies.simd]
git = "https://github.com/nox/simd"
rev = "438780ca236b1ed2caf032edebda9c9362eaabc6"
optional = true
```

This won't work because you can't have an optional dependency and a feature bear the same name.
