### ISSUE TITLE
Support custom profiles

### ISSUE THREAD

**Issue by Aatch** [rust-lang/cargo#2007]
There are 5 profiles used for various purposes, and while each is configurable, you can't make your own profile. This would be useful for defining special profiles for a specific project. I personally would find a `profiling` profile useful to be able to enable both debugging and optimisations.

I propose supporting custom profiles, selected using `--profile`. The current profiles would just be predefined ones and I don't see why they couldn't be selected as well. A set of default values for the profile options will also need to be decided upon.

**Comment by alexcrichton** [comment]
I do think that this was one of the original intentions of profiles (cc @wycats, @carllerche), but there's also certainly a case to be made that if there are sets of options frequently used that Cargo should bake in those profiles! (and a profiling profile does seem like something that may commonly arise).

**Comment by carllerche** [comment]
Yep :+1:

**Comment by shepmaster** [comment]
I'd definitely love to have a `profile` profile, and having custom profiles seems like a nice pluggable way to do it.

**Comment by whitequark** [comment]
I would really like to have a relwithdebinfo profile, like CMake does:
```
[profile.relwithdebinfo]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
```
... which is really a superset of profiling, but also useful for shipping -dbg packages, etc.

**Comment by luser** [comment]
We're in [a situation with Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1386371) where we'd like to ship our release binaries with LTO, but we want to disable it by default for local developer builds to save on build time. Unfortunately there's no straightforward way to do that. Being able to define a custom profile would be really useful here.

**Comment by da-x** [comment]
I have a draft implementation [here](https://github.com/da-x/cargo/commits/custom-profiles) if anyone is interested.

**Comment by Boscop** [comment]
I'm also interested in this.. I need 2 `dev` profiles, one with `opt-level = 0` and one with `opt-level = 1`.

**Comment by johnthagen** [comment]
It would be nice to be able to have a fully optimized "release/publish" profile: https://github.com/rust-lang/rust/issues/47745#issuecomment-447530953

```toml
# The publish profile, used for `cargo build --publish`.
[profile.publish]
# (...) everything else the same as profile.release except:
lto = true        # Enable full link-time optimization.
codegen-units = 1 # Use only 1 codegen-unit to enable full optimizations.
```
