### ISSUE TITLE
thread '<main>' has overflowed its stack

### ISSUE THREAD

**Issue by v21** [rust-lang/cargo#2051]
When starting up an empty project with a set of dependencies that looks like:
```toml
[dependencies]
piston = "0.13.0"
piston2d-graphics = "0.10.0"
pistoncore-glutin_window = "0.15.0"
piston2d-opengl_graphics = "0.14.0"
image = "0.3.11"
vecmath = "0.2.0"
piston_window = "0.23.0"
```

I see the following:

```
philippe:test_Cargo_toml v21$ cargo run
    Updating registry `https://github.com/rust-lang/crates.io-index`

thread '<main>' has overflowed its stack
Illegal instruction: 4
```

cargo -V reads: cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)
