### ISSUE TITLE
Can't use optional dependencies in a build script

### ISSUE THREAD

**Issue by gkoz** [rust-lang/cargo#2086]
When an optional dependency is enabled via `--features bar_feat` the build script is built without `--extern bar=...` and can't import the `bar` crate.
```toml
[project]
name = "foo"
version = "0.5.0"
build = "build.rs"

[features]
bar_feat = ["bar"]

[dependencies.bar]
path = "bar"
optional = true
```

[A failing test](https://github.com/gkoz/cargo/commit/33ce0bf90c9a6ba218b5eaad7f6bbe96bc23d33e).

This was supposed to be a workaround for #1581... :frowning:
