### ISSUE TITLE
Cargo does not accept prerelease versions as constraints

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#2145]
E.g. trying to depend on https://crates.io/crates/arrayfire/3.2.0-rc0 via

```toml
[package]
authors = [""]
name = "test"
version = "0.1.0"

[dependencies]
arrayfire = "3.2.0-rc0"
```

Gives an error:

```
failed to parse manifest at `.../Cargo.toml`

Caused by:
  the given version requirement is invalid
```

(Notably, changing it to `3.2.0` works fine.)
