### ISSUE TITLE
`cargo update` infinite recursion.

### ISSUE THREAD

**Issue by DiamondLovesYou** [rust-lang/cargo#2300]
Put these deps into a new crate (created with `cargo new`):
```toml
glium = "0.13.3"
skia = "0.1.0"
```

Then try to build. [Log](https://gist.github.com/DiamondLovesYou/89554ad6cc26f47bd4a8).
