### ISSUE TITLE
add a way to set a default `--target`

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#2332]
For example, if for your project you always cross compile using `cargo build --target=thumbv6m-none-eabi`. This feature would let you add a key value pair to your cargo config file:

``` toml
# .cargo/config
[target]
default = "thumbv6m-none-eabi"
```

That will let you simply call `cargo build` to cross compile your project for `thumbv6m-none-eabi`. This would also extend to `cargo doc`.

Originally reported [here].

[here]: https://users.rust-lang.org/t/default-cargo-target/4467
