### ISSUE TITLE
Unable to update registry on CircleCI

### ISSUE THREAD

**Issue by RoxasShadow** [rust-lang/cargo#2429]
Basically both the setup of the environment and the rust installation work fine, but:
```
cargo build -v

$<2>$<2>    Updating$<2> registry `https://github.com/rust-lang/crates.io-index`
$<2>Unable to update registry https://github.com/rust-lang/crates.io-index
$<2>$<2>
Caused by:
$<2>$<2>  failed to fetch `https://github.com/rust-lang/crates.io-index`
$<2>$<2>
Caused by:
$<2>$<2>  failed to authenticate when downloading repository
$<2>$<2>
Caused by:
$<2>$<2>  [23/-1] error authenticating: no auth sock variable

$<2>cargo build -v returned exit code 101
```

*circle.yml*
```toml
[package]
# ...

[dependencies]
rustc-serialize = "0.3"
chrono          = "0.2"
iron            = "0.2"
router          = "0.1"
logger          = "0.0.3"
params          = "0.0.3"
toml            = "0.1"
lazy_static     = "0.1"
rs-es           = "0.2.2"

[lib]
name = # ...
path = "src/lib.rs"

[[bin]]
name = # ...
path = "src/main.rs"
doc  = false

[target.heroku]
version = "stable"
```

**Comment by alexcrichton** [comment]
I think that this is a dupe of https://github.com/rust-lang/cargo/issues/2078 because Circle CI will use `insteadOf` git configuration to switch to an SSH clone instead of an HTTPS clone. The default keys pointed to by `~/.ssh/config` are unfortunately not ready by Cargo just yet :(

**Comment by RoxasShadow** [comment]
Yes, it is. Thanks!

Anyay, if someone needs a (hopefully) temporary workaround, they can try adding this to the `circle.yml`:

```yml
test:
  override:
    - eval `ssh-agent` && ssh-add /home/ubuntu/.ssh/id_circleci_github && cargo test  -v
```

([Source](https://discuss.circleci.com/t/cargo-build-fails-on-fresh-install/1102/2))
