### ISSUE TITLE
Cargo burns 100% processor forever while updating registry

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/cargo#2447]
I've only been able to reproduce this bug on a single Cargo.toml file.  

Simply make a new directory, put this file in it, and run `cargo update`

**Cargo.toml**

```toml
[package]
name = "trident"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[[bin]]
name = "gui"
path = "./src/gui.rs"


[dependencies]
lux = "0.0.4"
```

Commenting out the dependency on Lux fixes it.  As does replacing the Lux dependency a newer version (0.1.0).
