### ISSUE TITLE
cargo build rebuilds everything after changing a single file

### ISSUE THREAD

**Issue by 31z4** [rust-lang/cargo#2503]
I have the following `Cargo.toml`

```toml
[package]
name = "test"
version = "0.0.1"
authors = ["Elisey Zanko <elisey.zanko@gmail.com>"]

[dependencies]
rs-es = "0.2.5"
walkdir = "0.1.5"
```

And my `main.rs` looks like this

```rust
extern crate walkdir;
extern crate rs_es;

use walkdir::WalkDir;
use rs_es::Client;
use std::env;

fn main() {
    // Some code here
}
```

Every time I run `cargo build` after changing `main.rs` it rebuilds every dependency. However, it doesn't happen to `cargo build --release`.

> rustc 1.7.0 (a5d1e7a59 2016-02-29)
> cargo 0.8.0-nightly (28a0cbb 2016-01-17)
