### ISSUE TITLE
[Feature Request] Support mercurial repositories as dependencies

### ISSUE THREAD

**Issue by troplin** [rust-lang/cargo#2527]
It would be great if I could specify dependencies as mercurial repositories, similar to how git dependencies already work:
```toml
[dependencies]
mydependency = { hg = "https://bitbucket.org/troplin/mydependency" }
```
