### ISSUE TITLE
Overridden dependencies are still checked out

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#258]
``` toml
# Cargo.toml
[package]                                                                              
name    = "test"                                                                       
version = "0.1.0"                                                                      
authors = []                                                                           

[dependencies.splay]                                                                  

git = "git://github.com/alexcrichton/splay-rs"                                        
```

``` toml
# .cargo/config
paths = ["../splay-rs"]
```

```
$ rm -rf ~/.cargo/git
$ cargo build
    Updating git repository `git://github.com/alexcrichton/splay-rs`
       Fresh splay v0.1.0 (file:../splay-rs)
       Fresh test v0.1.0 (file:/home/alex/code/wut)

```
