### ISSUE TITLE
Allow using crate features that only exist in an override

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#2582]
For example:

``` toml
[dependencies]
num-complex = { version = "*", features = ["newfeature"] }
```

This is not allowed by cargo if `newfeature` doesn't exist upstream, even if there is an override that has the new crate feature flag.

However, the feature flag can still be enabled manually `cargo build --features=num-complex/newfeature`.

If this worked as expected (using Cargo.toml), it would make it easier to test the new feature using a whole chain / group of crates that depend on it.
