### ISSUE TITLE
Conditional dependency using `target_feature="neon"` does not work

### ISSUE THREAD

**Issue by mmatyas** [rust-lang/cargo#2628]
I've wanted to use `huonw/simd` in a Cargo.toml like this:

```toml
[target.'cfg(any(target_feature = "sse2", target_feature = "neon"))'.dependencies]
simd = {git = "https://github.com/huonw/simd"}
```

When I cross compile to ARM with the additional `RUSTFLAGS=' -C target-feature=+neon'` environment variable setting, the setting is not detected, and I get the "missing package: simd" kind of errors. Here's the related issue in Servo: servo/servo#10900.

It does work fine during a normal, x86_64 build (where `sse2` is on by default by the way).
