### ISSUE TITLE
Update opt-level parsing

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2655]
The recently added `s` and `z`, optimize for size flags are not recognized by cargo:

```toml
[profile.release]
opt-level = z
````

`error: Invalid arguments.`

 Cargo still knows about just the first three:

`error: optimization level needs to be between 0-3 (instead was `4`)`
