### ISSUE TITLE
Rename the `benches/` directory to `benchmark/` or `benchmarks/`

### ISSUE THREAD

**Issue by postmodern** [rust-lang/cargo#2725]
### Rational
- `benches` is ambiguous and may confuse English-as-Second-Language (ESL) programmers.
- `benches` is only 3 letters shorter than `benchmarks`, so it's not significantly shorter. `benchmark` (singular) is only 2 letters longer than `benches`.

**Comment by sunjay** [comment]
Or at least give us the option to configure it in Cargo.toml! :smile:

**Comment by alexcrichton** [comment]
@sunjay you should be able to list out benchmarks via `[[bench]]` in Cargo.toml, no?

**Comment by sunjay** [comment]
I mean it would be nice if it were possible to specify something like:

```toml
# section and field names are just examples, not necessarily what the actual names would be
[bench]
location = "benchmarks"
```

You're right that you can already do this on a case by case basis, but it would be nice to just be able to modify the search path so all the awesome auto discovery features of cargo still work.
