### ISSUE TITLE
Crate in workspace doesn't rebuild against changed dependency, if said dependency was already built within the workspace

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#2855]
We have the following project:

`Cargo.toml`:
```toml
[workspace]
members = ["myapp", "mylib"]
```
`mylib/Cargo.toml`:
```toml
[package]
name = "mylib"
version = "0.1.0"
```
`mylib/src/lib.rs`:
```rust
pub fn gimme_string() -> &'static str {
    "Hello"
}

#[test]
fn test() {
    assert_eq!(gimme_string(), "Hello");
}

```
`myapp/Cargo.toml`:
```toml
[package]
name = "myapp"
version = "0.1.0"

[dependencies.mylib]
path = "../mylib"

```
`myapp/src/main.rs`:
```rust
extern crate mylib;

fn main() {
    println!("{}", mylib::gimme_string());
}

```

First, let's just run myapp:
```
[myapp]$ cargo run
   Compiling mylib v0.1.0 (file:///tmp/ws/mylib)
   Compiling myapp v0.1.0 (file:///tmp/ws/myapp)
     Running `/tmp/ws/target/debug/myapp`
Hello

```

Now we replace "Hello" with "Hey" in mylib:
```Rust
pub fn gimme_string() -> &'static str {
    "Hey"
}

#[test]
fn test() {
    assert_eq!(gimme_string(), "Hey");
}

```

Let's test the changes:
```
[mylib]$ cargo test
   Compiling mylib v0.1.0 (file:///tmp/ws/mylib)
     Running /tmp/ws/target/debug/mylib-f6404eab34ef39c8

running 1 test
test test ... ok
...
```

Now let's run myapp again:
```
[myapp]$ cargo run
   Compiling myapp v0.1.0 (file:///tmp/ws/myapp)
     Running `/tmp/ws/target/debug/myapp`
Hello

```

Wait, what? I'm pretty sure I changed "Hello" to "Hey".
