### ISSUE TITLE
invalid source layout results in (nearly) silent errors

### ISSUE THREAD

**Issue by dohzya** [rust-lang/cargo#288]
I read the doc too fast and didn't see I had to put my sources in `src/`, so I put them at the root of my dir: it resulted on weird errors.

With nothing else in the directory, this `Cargo.toml` file resuts in a `subcommand failed with signal: 11` error:

``` toml
[package]

name = "test"
```

This one results in a `subcommand failed with signal: 10` error:

``` toml
[package]

name = "test"
version = "0.0.1"
```

For this last tests, I tried to add the `[[bin]]` section and a `main.rs` file, same error (`subcommand failed with signal: 10`):

``` toml
[package]

name = "test"
version = "0.0.1"

[[bin]]
main = "main.rs"
```

Just in case:

``` sh
% sw_vers -productVersion
10.9.4
% cargo --version
cargo-nightly 0.1.0-pre (3e5ba33 2014-07-29 00:14:32 +0000)
% rustc --version
rustc 0.12.0-pre-nightly (b2bd99860 2014-07-28 22:36:39 +0000)
```

ps: it works like a charm since I put `main.rs` into `src/` and removed the `[[bin]]` section :-)
