### ISSUE TITLE
'Peer certificate cannot be authenticated with given CA certificates' after company's proxy

### ISSUE THREAD

**Issue by pffang** [rust-lang/cargo#2953]
As the title, cargo cannot work. 
Curl can work properly.

Ubuntu 14.04 LTS

**Comment by alexcrichton** [comment]
Thanks for the report! The nightly Cargo builds should have an option to configure a custom root CA:

```toml
# in .cargo/config

[http]
cainfo = "path/to/cainfo.crt"
```

If you use that, does it work for you?
