### ISSUE TITLE
Point out _which_ version failed to error

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#2964]
Given this `Cargo.toml`:

``` toml
[package]
name = "foo"
version = "1.2.3"
authors = []

[dependencies]
plugin = "0.2*"
```

You get this error:

``` bash
$ cargo build --verbose
error: failed to parse manifest at `/home/steve/tmp/lol/Cargo.toml`

Caused by:
  you have already provided an operation, such as =, ~, or ^; only use one
```

Now, there's two things that aren't great about this error. First, the text isn't as helpful as it could be, but that's just Cargo passing on the messages `semver` is giving, so that's not Cargo's fault. But what Cargo _could_ do in this instance is say exactly _which_ version failed to parse. 

In this case, the actual Cargo.toml was huge, with a ton of dependencies, and it took a sharp eye to notice that it should have been `0.2.*`. If it had pointed out which version failed, it would have been a lot easier.
