### ISSUE TITLE
Cargo nondeterministically fails to build

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#3216]
Successful build:

https://gist.github.com/ddb95a0dabd1697a9a836698fb97d257

Failing build:

https://gist.github.com/808ad5acb5a239671bb0f05776d4c9d2

The relevant part of my `Cargo.toml` file is:

``` toml
[dependencies]
chrono = { version = "0.2", features = ["serde"] }
collect-mac = "0.1"
decimate = "0.1" # { version = "0.1", features = ["serde"] }
errorplate = { path = "/Users/alex/Software/rust-errorplate" }
flate2 = "0.2"
hyper = "0.9"
json-rpc = { path = "/Users/alex/Software/rust-json-rpc" }
openssl = "0.7"
serde = { version = "0.8", features = ["unstable"] }
serde_derive = "0.8"
serde_json = { version = "0.8", features = ["preserve_order"] }
timer = "0.1"
url = { version = "1.1", features = ["serde"] }
uuid = { version = "0.2", features = ["serde", "v4"] }

[replace]
"chrono:0.2.25" = { path = "../rust-chrono" }
"hyper:0.9.10" = { path = "../hyper" }
"decimate:0.1.0" = { path = "../decimate" }
"serde:0.8.15" = { path = "../serde/serde" }
"serde_derive:0.8.15" = { path = "../serde/serde_derive" }
"serde_test:0.8.15" = { path = "../serde/serde_test" }
"serde_json:0.8.3" = { path = "../serde-json/json" }
"serde_urlencoded:0.2.2" = { path = "../serde_urlencoded" }
```

Sometimes the build works fine, sometimes it doesn't. It seems to always fail after a `cargo clean`, but I'm not 100% positive. What's going on here?
