### ISSUE TITLE
'no matching package' error during publish even though package exists

### ISSUE THREAD

**Issue by Byron** [rust-lang/cargo#3223]
### How to reproduce

Even though you wouldn't be able to publish this crate, it will abort beforehand:

```bash
git clone --depth 1 --single-branch https://github.com/Byron/google-apis-rs
cd google-apis-rs
make publish-cli -j 8
```

The output is as follows:
```
[...]
cd gen/serviceregistryalpha-cli && cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging google-serviceregistryalpha-cli v1.0.0+20160401 (file:///Users/byron/google-apis-rs/gen/serviceregistryalpha-cli)
   Verifying google-serviceregistryalpha-cli v1.0.0+20160401 (file:///Users/byron/google-apis-rs/gen/serviceregistryalpha-cli)
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to verify package tarball

Caused by:
  no matching package named `google-serviceregistryalpha` found (required by `google-serviceregistryalpha-cli`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^1.0.0
versions found: 0.1.15+20160401, 0.1.14+20160401, 0.1.13+20160401, ...
```

However, the required version `1.0.0+20160401` of `google-serviceregistryalpha` is available, both [online](https://crates.io/crates/google-serviceregistryalpha) as well as locally (see `Cargo.toml` files in the _details_ section.

Interestingly, this is the only remaining CLI package that has to be published, all others already worked.

Could this be some sort of inconsistency in the database, or a problem on how cargo handles versions ?

#### Meta

```bash
# nightly
➜  google-apis-rs git:(master) cargo --version && rustc --version
cargo 0.13.0-nightly (9a0801d 2016-10-20)
rustc 1.14.0-nightly (f09420685 2016-10-20)

# OR stable
➜  google-apis-rs git:(master) cargo --version && rustc --version
cargo 0.13.0-nightly (109cb7c 2016-08-19)
rustc 1.12.1 (d4f39402a 2016-10-19)
```

<details>
Here is the `Cargo.toml` of the `google-serviceregistryalpha-cli` crate:
```toml
# DO NOT EDIT !
# This file was generated automatically from 'src/mako/Cargo.toml.mako'
# DO NOT EDIT !
[package]

name = "google-serviceregistryalpha-cli"
version = "1.0.0+20160401"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with Service Registry (protocol alpha)"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/serviceregistryalpha-cli"
homepage = "https://developers.google.com/cloud-serviceregistry/"
documentation = "http://byron.github.io/google-apis-rs/google_serviceregistryalpha_cli"
license = "MIT"
keywords = ["serviceregistry", "google", "cli"]

[[bin]]
name = "serviceregistryalpha"

[dependencies]
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
yup-oauth2 = { version = "^ 1.0", optional = true, default-features = false }
serde_derive = { version = "^ 0.8", optional = true }
strsim = "^0.5"
yup-hyper-mock = "^1.0"
clap = "^2.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive","yup-oauth2/nightly","google-serviceregistryalpha/nightly"]
with-serde-codegen = ["serde_codegen","yup-oauth2/with-serde-codegen","google-serviceregistryalpha/with-serde-codegen"]

[build-dependencies]
serde_codegen = { version = "^ 0.8", optional = true }


[dependencies.google-serviceregistryalpha]
path = "../serviceregistryalpha"
version = "1.0.0"
optional = true
default-features = false
```

And here the `Cargo.toml` of the crate being referred to, `../serviceregistryalpha`:
```toml
# DO NOT EDIT !
# This file was generated automatically from 'src/mako/Cargo.toml.mako'
# DO NOT EDIT !
[package]

name = "google-serviceregistryalpha"
version = "1.0.0+20160401"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with Service Registry (protocol alpha)"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/serviceregistryalpha"
homepage = "https://developers.google.com/cloud-serviceregistry/"
documentation = "http://byron.github.io/google-apis-rs/google_serviceregistryalpha"
license = "MIT"
keywords = ["serviceregistry", "google", "protocol", "web", "api"]
build = "src/build.rs"


[dependencies]
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
yup-oauth2 = { version = "^ 1.0", optional = true, default-features = false }
serde_derive = { version = "^ 0.8", optional = true }
url = "= 0.5"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive","yup-oauth2/nightly"]
with-serde-codegen = ["serde_codegen","yup-oauth2/with-serde-codegen"]

[build-dependencies]
serde_codegen = { version = "^ 0.8", optional = true }
```
