### ISSUE TITLE
Cfg dependencies are still required on excluded platforms

### ISSUE THREAD

**Issue by TheNeikos** [rust-lang/cargo#3233]
A simple use case:

*Cargo.toml*
```toml
[package]
name = "test"
version = "0.1.0"

[target.'cfg(windows)'.dependencies]
does_not_exist = 1
```
and

*main.rs*
```rust
fn main() {}
```

Will fail with this error on my linux machine:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `does_not_exist` found (required by `test`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^1
```

From what I gathered on the [dependencies page](http://doc.crates.io/specifying-dependencies.html#platform-specific-dependencies) is that it should be ignored as I did not run it on a linux machine.

Additional Info:

```
neikos@work ~> rustc -V
rustc 1.14.0-nightly (3caf63cc0 2016-10-24)
neikos@work ~> cargo -V
cargo 0.13.0-nightly (9a0801d 2016-10-20)
```

This was [a question on SO](http://stackoverflow.com/questions/40280507/cargo-toml-os-dependency-for-crate), and it bugged me.
