### ISSUE TITLE
No output library created when using workspaces

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/cargo#3432]
Example Project ([git repo](https://github.com/phil-opp/cargo-issue-3432)):

`Cargo.toml`:

```toml
[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "issue"
version = "0.1.0"

[dependencies.foo]
path = "libs/foo"

[workspace]
```

`libs/foo/Cargo.toml`:

```toml
[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "foo"
version = "0.1.0"
```

`src/lib.rs` and `libs/foo/src/lib.rs` are both empty.

When I run `cargo build`, there is no output `rlib` in `target/debug`. It works if I remove the `workspace` from the `Cargo.toml`.

cargo 0.16.0-nightly (ddb5c32 2016-12-16)
rustc 1.15.0-nightly (8f02c429a 2016-12-15)
