### ISSUE TITLE
Unable to use a feature of an optional dependency from a feature

### ISSUE THREAD

**Issue by EpicatSupercell** [rust-lang/cargo#3494]
For example lets say we use
```
[dependencies.serde]
version = "0.8.*"
optional = true
default-features = false
```
and we want to use the std feature of serde if it is used.
```
[features]
std = ["serde/std"]
```
But now if someone wants to use our std feature serde WILL be imported. If I would want to represent this I would write
```
[features]
std = ["serde", "serde/std"]
```
Right now it's impossible to use a feature of an optional dependency from an own feature without forcing it to be used.

**Comment by alexcrichton** [comment]
Yes it's true that relying on `a/b` will implicitly activate the dependency on `a`, rather than just activating the `b` feature in `a` if `a` is already activated. I don't believe it's possible to express what you're thinking here today with Cargo features.

**Comment by valarauca** [comment]
To chime in.

There is a push in `slog` to move to opaque key value pairs, so that keys can be variable when the same logging function is invoked.

Anyways. Since the new type definition is feature gated by `slog`, any project that imports `slog`, and feature gates this _new_ feature, can't optionally trigger this feature gate in `slog`.

**Comment by kvark** [comment]
Just a friendly heads up from #7259 - this problem is hitting gfx-rs ecosystem quite badly. We want things like `serde` and `winit` to be transparently enabled for the backends that the user selects, not all the things in the universe.

**Comment by RalfJung** [comment]
libstd itself [also hit an annoying instance of this](https://github.com/rust-lang/rust/pull/64444#issuecomment-531463367).

**Comment by xu-cheng** [comment]
Just my 2 cents. Alternatively, this could be solved if the following syntax is supported. The same syntax will also address https://github.com/rust-lang/cargo/issues/1839.

```toml
[features]
default = ["std"]
std = []

[target.'cfg(feature = "std")'.dependencies]
serde = { version = "*", optional = true }

[target.'cfg(not(feature = "std"))'.dependencies]
serde = { version = "*", optional = true, default-features = false }
```
