### ISSUE TITLE
Allow `[target.'cfg(...)']` syntax in .cargo/config

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/cargo#3499]
In `Cargo.toml` there are two ways to specify target-specific dependencies:

* `[target.$triple.dependencies]`
* `[target.'cfg(...)'.dependencies]` (added by #2328)

But in `.cargo/config` there is only one way to specify target-specific rustc flags:

* `[target.$triple] rustflags = [...]` (added by #3153)

It would be useful if `[target.'cfg(...)']` was supported here too, for use cases like:

```toml
[target.'cfg(target_arch = "x86")']
rustflags = ["-C", "target-feature=+ssse3"]
```
