### ISSUE TITLE
Missing libraries during linking of the building script when linker is specified in config

### ISSUE THREAD

**Issue by leviat** [rust-lang/cargo#3503]
I currently adjust a library to make it run on Windows. Therefore I have to make sure that the linker used in the building process is from Visual Studio 12. To this end, I define the VS 12 linker in a local cargo config file. Furthermore I have to run a building-script which accesses the environment. My problem now is that building fails at the linking stage (already of the building script) due to missing libraries. This only happens when I specify the linker explicitly. Weirdly, on a machine where Cargo defaults to VS 12's linker, it will include the libraries properly on default but will fail when the same linker is specified explicitly in the config. Am I missing some library include magic which is omitted when I specify the linker in a config file or is this a bug?

Example project:
Structure:
```
|   build.rs
|   Cargo.toml
|
+---.cargo
|       config
|
\---src
        main.rs
```

./build.rs:

```Rust
use std::env;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    panic!("Building!");
}
```

./Cargo.toml:

```Toml
[package]
name = "some_binary"
version = "0.1.0"
build = "build.rs"
```

.cargo/config:

```Toml
[target.x86_64-pc-windows-msvc]
linker = "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/link.exe"
```

src/main.rs:
```Rust
fn main() {
    println!("Hello, world!");
}
```

Running the project with `cargo run` should produce a linker error with something like 

> LINK : fatal error LNK1181: cannot open input file 'ws2_32.lib'

or 

> LINK : fatal error LNK1181: cannot open input file 'advapi32.lib'

They correspond to libraries from the Windows Kit SDKs.

**Comment by alexcrichton** [comment]
Oh to run linkers like `link.exe` manually you'd also need to set up a bunch of env vars. That typically happens automatically by the compiler, but if you specify `linker` yourself then you'd be responsible for taking care of that. 

In that case I don't think that this is a Cargo bug, but feel free to let me know if there's still trouble getting it working!

**Comment by leviat** [comment]
I'd usually use the build-script to set up things like that but since that's where the linking already fails, I'm a bit at a loss here. 😐 
My second attempt was to hardcode the missing libraries into the Cargo configuration for the target like this:

```Toml
[target.x86_64-pc-windows-msvc]
linker = "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/link.exe"
rustflags  = ["-L C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x64",]
```

However the flag is not included as seen by this error 

> Process didn't exit successfully: `rustc build.rs --crate-name build_script_build --crate-type bin -g --out-dir C:\Users\User\Documents\Rust Projects\some_binary\target\debug\build\some_binary-7fef2f489dde8cdb --emit=dep-info,link -C linker=C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/link.exe -L dependency=C:\Users\User\Documents\Rust Projects\some_binary\target\debug -L dependency=C:\Users\User\Documents\Rust Projects\some_binary\target\debug\deps` (exit code: 101)

I also tried running `cargo rustc --verbose -- -L C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x64` which led to the same result. 😐
