### ISSUE TITLE
[Suggestion] Include dev-dependencies when compiling examples

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/cargo#3543]
I have a package that I don't need for the lib, but is used in an example. Should dev-dependencies be available to examples?

**Comment by alexcrichton** [comment]
They should be indeed! Did you find that they weren't though?

**Comment by carols10cents** [comment]
I was able to create a crate that has `tempdir` as a dev-dependency:

Cargo.toml:

```toml
[package]
name = "dev-dep-test"
version = "0.1.0"
authors = ["Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]

[dependencies]

[dev-dependencies]
tempdir = "0.3"
```

And an example in that crate that uses the dev-dependency:

examples/simple.rs:

```rust
extern crate tempdir;

fn main() {
    tempdir::TempDir::new("my_directory_prefix").unwrap();
    println!("hello world");
}
```

And I am able to compile and run this example with `cargo run --example simple`.

So I think this issue can be closed!
