### ISSUE TITLE
Crate type of examples is not included in read-manifest output

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#3572]
I have this crate:

```
[lib]
crate-type = ["staticlib"]

[[example]]
name = "l"
crate-type = ["staticlib"]
```

This succesfully builds my example into a static library.

However, I this information is not exposed through `cargo read-manifest`:
```
$ cargo read-manifest|json_pp
{
   "dependencies" : [],
   "targets" : [
      {
         "name" : "cttest",
         "src_path" : "src/lib.rs",
         "kind" : [
            "staticlib"
         ]
      },
      {
         "kind" : [
            "example"
         ],
         "src_path" : "examples/l.rs",
         "name" : "l"
      }
   ],
...
```

**Comment by matklad** [comment]
Unrelated note: `read-manifest` is deprecated, it's better to use `cargo metadata` or `cargo metada --no-deps`. 

I think we perhaps don't need `TargetKind::Example` at all? Instead, we can add an `is_example` field to `Target`.

**Comment by alexcrichton** [comment]
@matklad yeah I think you're right, its own kind is likely unwarranted now

**Comment by carols10cents** [comment]
When I have a project with a Cargo.toml like this:

```toml
[package]
name = "dev-dep-test"
version = "0.1.0"
authors = ["Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[[example]]
name = "simple"
crate-type = ["staticlib"]
```

And this example/simple.rs:

```rust
pub fn foo() {}
```

If I run `$ cargo build -q --message-format json --examples`, I see in the output `"kind": ["example"]`:

```json
  "target": {
    "crate_types": [
      "staticlib"
    ],
    "kind": [
      "example"
    ],
    "name": "simple",
    "src_path": "/Users/carolnichols/rust/dev-dep-test/examples/simple.rs"
  }
```

So I think this can be closed. Please reopen if I'm mistaken! Thank you!
