### ISSUE TITLE
Multiple git dependencies with the same tag trigger assertion on checkout.is_fresh()

### ISSUE THREAD

**Issue by quodlibetor** [rust-lang/cargo#3580]
With a Cargo.toml that includes:

```toml
[dependencies]
serde = { git = "https://github.com/serde-rs/serde", rev = "v0.9.0-rc2" }
serde_derive = { git = "https://github.com/serde-rs/serde", rev = "v0.9.0-rc2"}
```

I hit the `thread 'main' panicked at 'assertion failed: checkout.is_fresh()', src/cargo/sources/git/utils.rs:183` bug that was last seen in #2271.

Running with:

```toml
[dependencies]
serde = { git = "https://github.com/serde-rs/serde", rev = "1e05fc21457b838" }
serde_derive = { git = "https://github.com/serde-rs/serde", rev = "1e05fc21457b838"}
```

works fine.

```
$ cargo --version
cargo 0.17.0-nightly (2324c2b 2017-01-21)
```
