### ISSUE TITLE
The `path` field should be documented

### ISSUE THREAD

**Issue by emberian** [rust-lang/cargo#36]
# Updated Description

The `path` field should be documented for `[[lib]]` and `[[bin]]`
# Original Description

**Allow specifying the source file that should be built**

Requiring a given source layout isn't the best, IMO. Rather than:

``` toml
[[lib]]

name = "foo"
```

which would look in `src/foo.rs`, also allow:

``` toml
[[lib]]

src = "src/foo/lib.rs"
```

Which can make sense when a repo is large or complex.
