### ISSUE TITLE
warning: unused manifest key: package.categories

### ISSUE THREAD

**Issue by sunjay** [rust-lang/cargo#3607]
This is my `Cargo.toml` file:

```toml
[package]
name = "brain"
version = "0.0.1"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Compiler for the brain programming language. Compiles brain into optimized brainfuck code. Also includes a brainfuck interpreter."
repository = "https://github.com/sunjay/brain"
readme = "README.md"
keywords = ["brain", "brainfuck", "compiler", "interpreter", "optimizer"]
# crates.io/category_slugs
categories = ["command-line-interface"]
license = "MIT"

[dependencies]
clap = "^2.0"

[dependencies.nom]
version = "^2.0"
features = ["verbose-errors"]

[[bin]]
name = "brain"
doc = false

[[bin]]
name = "brainfuck"
```

Every time I run `cargo run`, I get the following output:

```
$ cargo run --bin brain
warning: unused manifest key: package.categories
   Compiling brain v0.0.1 (file:///~/Documents/projects/brain)
    Finished debug [unoptimized + debuginfo] target(s) in 3.78 secs
     Running `target/debug/brain`
...blah...
```

The warning probably shouldn't be there because package.categories is a valid key as documented in [The Manifest Format](http://doc.crates.io/manifest.html#package-metadata).
