### ISSUE TITLE
feature to env var mapping is not unique

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#3702]
Build scripts receive information about activated features as environment variables `CARGO_FEATURE_$name`, where `$name` is the feature name uppercased and with dashes converted to underscores.

However, feature names are allowed to contain underscores, so this transformation can create collisions. Example:

- Cargo.toml
  ```toml
  [package]
  name = "tester"
  version = "0.1.0"
  
  build = "build.rs"
  
  [features]
  foo-bar = []
  foo_bar = []
  ```
- build.rs
  ```rust
  use std::env;
  
  fn main() {
      for (k, v) in env::vars() {
          if k.starts_with("CARGO_FEATURE") {
              println!("{} => {}", k, v);
          }
      }
      panic!();
  }
  ```
- output
  ```
  --- stdout
  CARGO_FEATURE_FOO_BAR => 1
  
  --- stderr
  thread 'main' panicked at 'explicit panic', build.rs:9
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  ```
