### ISSUE TITLE
`required-features` doesn't work with non-top-level features

### ISSUE THREAD

**Issue by sgrif** [rust-lang/cargo#3727]
When adding the following to `Cargo.toml`

```toml
[[test]]
name = "tests"
path = "tests/test.rs"
required-features = ["diesel/postgres", "diesel/sqlite"]
```

I'd expect that `cargo test --features "diesel/postgres diesel/sqlite"` would run the tests. Instead, it makes it impossible to run them. That command runs the tests (and enables the features) properly when the `required-features` line is removed.

As an aside, the documentation is unclear as to whether `required-features` enables those features for a given target, or whether it skips it when those features aren't enabled.

**Comment by alexcrichton** [comment]
cc @jbendig, mind taking a look?

**Comment by jbendig** [comment]
I'll take a look at this. I should have time later this afternoon.

**Comment by alexcrichton** [comment]
Thanks @jbendig! Lemme know though if it takes up too much time and I can take over

**Comment by jbendig** [comment]
I've been able to reproduce this issue. It's because dependency based features are being resolved before being checked against `required-features`. If you pass `--features "diesel/postgres diesel/sqlite"`, then `required-features` will only see the "diesel" feature as enabled. 

This is easy enough to fix with respect to the `--features` flag but I think there is a deeper problem here. For example, the following should build foo without the `--features` flag because the "bar/a" feature is enabled:
```toml
[dependencies]
bar = { path = "bar", features = ["a"] }

[[bin]]
name = "foo"
required-features = ["bar/a"]
```
I'm still investigating the best way to approach this.

Regarding the documentation, I can see where the text is not clear as it should be. I'll try to change it after this issue is fixed.
