### ISSUE TITLE
Improve error message when attempting to change features when replacing a dependency (may apply to [patch] too)

### ISSUE THREAD

**Issue by debris** [rust-lang/cargo#3740]
My project's `Cargo.toml` file

```toml
[package]
name = "sample"
version = "0.1.1"

[dependencies]
regex = "0.2.1"

[target.'cfg(target_os="android")'.dependencies]
jni = "0.3.1"

[replace]
"error-chain:0.5.0" = { default-features = false }

[lib]
name = "sample"
crate-type = ["staticlib", "cdylib"]
```

When I try to compile it, I get the following warnings:

```
warning: dependency (error-chain) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
```

So, as suggested, I added `version` field to my replace.

```
[replace]
"error-chain:0.5.0" = { version = "0.5", default-features = false }
```

Now, I get an error

```
error: failed to parse manifest at `/Users/marek/projects/sample/cargo/Cargo.toml`

Caused by:
  replacements cannot specify a version requirement, but found one for `https://github.com/rust-lang/crates.io-index#error-chain:0.5.0`
```

-----

So, either the first warning that I got was misleading, cause it suggested to use `version` property (via *"or version to use"*), or replacing version is broken
