### ISSUE TITLE
required-features targets are compiled by cargo test even when such features are not selected

### ISSUE THREAD

**Issue by jbendig** [rust-lang/cargo#3762]
I started dogfooding required-features and I noticed that `cargo test` is compiling targets that require features which are not selected. This is particularly a problem when a bin using require-features has an optional dependency because the optional dependency won't be found and the test will fail to compile.

**To reproduce:**
1. Create a new project with the following Cargo.toml.
```toml
[project]
name = "foo"
version = "0.0.1"
authors = []

[features]
a = []

[[bin]]
name = "foo"
path = "src/bin/foo.rs"
required-features = ["a"]
```
2. Add a src/bin/foo.rs file with the following contents.
```rust
extern crate bar;

fn main() {
}
```
3. Add an empty tests/foo.rs file.
4. Run `cargo test`

**The error is:**
```shell
   Compiling foo v0.0.1 (...)
error[E0463]: can't find crate for `bar`
  --> src/bin/foo.rs:1:1
   |
1  | extern crate bar;
   | ^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `foo`.

error: build failed
```

**Expected outcome:**
The binary should not be compiled with the tests unless the appropriate features are selected.

**Work around:**
Enable the required features when testing: `cargo test --features="a"`

I'm working on a pull request for this issue but it'll be a couple days before I can submit it.
