### ISSUE TITLE
Stack overflow when replacement crate introduces cyclic dependency

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#3831]
I have the following root crate:
```toml
# a/Cargo.toml
[package]
name = "a"
version = "0.1.0"

[dependencies]
spin = "0.4.5"

[replace]
"spin:0.4.5" = { path = "../spin" }
```
And the following dependency:
```toml
# spin/Cargo.toml
[package]
name = "spin"
version = "0.4.5"

[dependencies]
a = { path = "../a" }
```
When I run `cargo build`, I get:
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

The non-replacement case, specifying `dependencies.spin = { version = "0.4.5", path = "../spin" }`, works fine:
```
error: cyclic package dependency: package `a v0.1.0 (file:///tmp/ct/a)` depends on itself
```
(Although it would be nice to print out the cycle)

Strangely enough, apparently depending on the crate name that's being replaced, sometimes there's no stack overflow. For example, I tried effecting the same with the bitflags crate, but that didn't work.
