### ISSUE TITLE
Cargo should support glob syntax in workspace members

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#3911]
Sometimes a project may have quite a large `workspace.members` array and it can be onerous to keep up to date. We've already got glob syntax with `include` and `exclude`, so we should have similar syntax for the `workspace.members` key, such as:

```toml
[workspace]
members = ["crates/*"]
```

(or something like that)
