### ISSUE TITLE
`cargo build` always rebuilds some dependencies unnecessarily

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#4104]
I have a project where, whenever if I execute `cargo build` it rebuilds some dependencies, **even if** I just did `cargo build` (and it succeeded). (And this didn't happen with other projects. )
And even if I change the source code of my project, and then do `cargo build` it still always rebuilds those dependencies. Even though I only changed the code of my project and the deps should be cached.
The deps that always get rebuilt are:
```
   Compiling cpp_demangle v0.2.1
   Compiling backtrace v0.3.1
   Compiling error-chain v0.10.0
   Compiling dotenv v0.10.0
```

Here are the deps from my Cargo.toml:
```toml
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", features = ["handlebars_templates"] }
diesel = { version = "0.12", features = ["chrono"] }
r2d2 = "0.7.1"
r2d2-diesel = "0.12"
bcrypt = "0.1.1"
dotenv = "0.10"
lazy_static = "0.2.1"
envy = "*"
log = "0.3.6"
log4rs = "0.7"
chrono = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
derive-new = "*"
error-chain = "*"
enum_primitive = "*"
rand = "*"
lettre = "0.5.1"

[dependencies.diesel_codegen]
default-features = false
features = ["postgres", "dotenv"]
version = "0.12"
```
