### ISSUE TITLE
Ability to specify version in generic way in doc link

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#4120]
Currently, my Cargo.toml looks mostly like this:

```toml
[package]
version = "0.5.0"
documentation = "https://docs.rs/lewton/0.5.0"
```

This means however that I have to remember to update the documentation link each time I make a release. It would be nice if something like this were supported:

```toml
documentation = "https://docs.rs/lewton/$version"
```
