### ISSUE TITLE
native library is being linked to by more than one package - when using replace in Cargo.toml

### ISSUE THREAD

**Issue by pgkos** [rust-lang/cargo#4186]
I want to test a patch (to `gtk-sys` crate, using a test project dependent on `gtk-rs` crate), so I have added a `[replace]` section to my Cargo.toml with a path to my local patched version of `gtk-sys` crate:

```toml
[package]
name = "gtk-sys-patch-test"
version = "0.1.0"

[replace]
"gtk-sys:0.3.4" = { path = "../gtk-sys-patch/gtk-sys" }

[dependencies.gtk]
version = "0.1.3"
```
But I cannot test the patch because when I add the `[replace]` section I get this error message:
```
native library `gobject` is being linked to by more than one package, and can only be linked to by one package

  gobject-sys v0.3.4
  gobject-sys v0.3.4 (file:///home/pgkos/gtk-sys-patch/gobject-sys)
```

Is this a bug or am I doing something wrong?
