### ISSUE TITLE
Bogus keyword on crates.io

### ISSUE THREAD

**Issue by pyfisch** [rust-lang/cargo#4332]
Hi, I am the owner of the [keyboard-types](https://crates.io/crates/keyboard-types) crate.

The Cargo.toml looks like this:

```toml
[package]
name = "keyboard-types"
version = "0.1.1"
authors = ["Pyfisch <pyfisch@gmail.com>"]
description = "Contains types to define keyboard related events."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/pyfisch/keyboard-types"
documentation = "https://docs.rs/crate/keyboard-types"
keywords = ["keyboard", "input", "event"]

[dependencies]
bitflags = "0.9.1"
serde = { version = "1.0.0", optional = true, features = ["derive"] }

[badges]
travis-ci = { repository = "pyfisch/keyboard-types" }
```
I expect the tree keywords, "keyboard", "input" and "event" to show up on crates.io. 

But the keywords section lists four words:
* Input (capitalized)
 * keyboard
 * event
 * input (again, but lowercase this time)

The two "input"s link to search results which are the same for both because the search engine seems to ignore case.
