### ISSUE TITLE
cargo update silently fails to update dependencies

### ISSUE THREAD

**Issue by debris** [rust-lang/cargo#4420]
cargo 0.20.0 (a60d185c8 2017-07-13)

```toml
# Cargo.toml

[dependencies]
bigint = "4.0"
crunchy = "0.1.3"
```

```toml
# Cargo.lock

[root]
name = "bigint_test"
version = "0.1.0"
dependencies = [
 "bigint 4.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "crunchy 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

# ...
```

bigint 4.1.2 depends on crunchy 0.1.5
bigint 4.1.1 depends on crunchy 0.1.3

---

running

```
cargo update -p bigint
```

results in no updates at all. Only update message is displayed.

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

---

running

```
cargo update
```

results in all creates being updated

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating bigint v4.1.1 -> v4.1.2
    Updating crunchy v0.1.3 -> v0.1.6
```

--- 

How it could be improved?

Running `cargo update -p` should result in warning when new version of crate is available, but the update is not possible

The bug can be reproduced using [this repo](https://github.com/debris/cargo-dependencies-test)
