### ISSUE TITLE
paths override does not work for unpubblished crates

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/cargo#4484]
I have an unpubblished crate named `av-data` and before publishing it I wanted to validate it against another crate I'm writing.

If I express the dependency this way it complains about missing dep
``` toml
[dependencies]
av-data = { version = "0.1.0" }
```
If I do this way
``` toml
[dependencies]
av-data = { version = "0.1.0", path = "non-existent" }
```

It picks the one written in `.cargo/config` in the parent correctly.
