### ISSUE TITLE
Arbitrarily long time spent in resolution

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4488]
```toml
[package]
name = "postgres_chrono_test"
version = "0.1.0"

[dependencies]
postgres = "=0.15.1"
sha2 = "=0.6.0"
```
