### ISSUE TITLE
Allow specification of dependencies on a per-bin basis

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/cargo#4536]
> for example, I want to provide a binary for the "semver" crate, and use clap. but I don't want library users to need clap.

Something like the following (but with correct / easy to recall syntax) would be useful:

```toml
# Cargo.toml

[[bin."binnamehere".dependencies]]
clap = "1.2.3"
```

This would be most useful in codebases with multiple `bin`s that have different dependency requirements.
