### ISSUE TITLE
Cargo doc panicks when two workspace executables have the same name

### ISSUE THREAD

**Issue by debris** [rust-lang/cargo#4539]
`cargo 0.21.0 (5b4b8b2ae 2017-08-12)`

```toml
# Cargo.toml
[workspace]
members = ["foo", "bar"]
```

```toml
# foo/Cargo.toml
[package]
name = "foo"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[[bin]]
name = "foo-cli"
```

```toml
# bar/Cargo.toml
[package]
name = "bar"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[[bin]]
name = "foo-cli"
```

----

```
$ cargo doc --all
```

```
thread 'main' panicked at 'assertion failed: bin_names.insert(target.crate_name())', src/tools/cargo/src/cargo/ops/cargo_doc.rs:42:16
stack backtrace:
   0:        0x1062da033 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h5d6b821bcccc8af3
   1:        0x1062e19ea - std::panicking::default_hook::{{closure}}::haca53f8b96e15b81
   2:        0x1062e16b2 - std::panicking::default_hook::h0029f59c1ec97ffc
   3:        0x1062e3cb2 - std::panicking::rust_panic_with_hook::hb8eae939c3fcaf9c
   4:        0x105e25727 - std::panicking::begin_panic_new::hc3b3a65678d1d60b
   5:        0x105f213c0 - cargo::ops::cargo_doc::doc::h0c7601517fa9dcf3
   6:        0x105dc3e3e - cargo::try_execute_builtin_command::heb45f2a7fd84911c
   7:        0x105dba108 - cargo::execute::h6bdda60fc2babbe7
   8:        0x105d8dc73 - cargo::call_main_without_stdin::h53c8581aeadf23cc
   9:        0x105db8e9f - cargo::main::hb069dc421fa35b9f
  10:        0x1062e4e5c - __rust_maybe_catch_panic
  11:        0x1062e4108 - std::rt::lang_start::heed3cc6f59fb65ca
```
