### ISSUE TITLE
Platform specific dependencies do not support custom features

### ISSUE THREAD

**Issue by 6A** [rust-lang/cargo#4576]
It is unclear whether or not dependencies defined using the `[target.'cfg(...)'.dependencies]` syntax support the `cfg(feature = "...")` specifier. In any case, it is currently impossible, which makes it is either a non-documented constraint, or a bug.

# Example
```toml
# Let us specify a feature that requires either an older version of the package 'a',
# or a new one:
[features]
old_support = []
new_support = []

# In theory, dependencies for both features can be specified using the
# following syntax:
[target.'cfg(feature = "old_support")'.dependencies]
a = "1"

[target.'cfg(feature = "new_support")'.dependencies]
a = "2"
```

However, building the project with `cargo build --features old_support` leads to an error:
```
error[E0463]: can't find crate for `a`
 --> src/lib.rs:2:1
  |
2 | extern crate a;
  | ^^^^^^^^^^^^^^^ can't find crate
```
