### ISSUE TITLE
Git dependencies require the `user.name` setting to be set in Git

### ISSUE THREAD

**Issue by sarahhodne** [rust-lang/cargo#463]
This was reported by a few Travis CI users, and I reproduced it myself. [Here's](https://github.com/henrikhodne-test/travis-test/tree/15b67548deaba6b68e6a1b7a17e24a79ca4a3107) a minimal test repo and [here's](https://travis-ci.org/henrikhodne-test/travis-test/builds/33819770) the corresponding failing build.

In short, if you have a Cargo.toml like this:

``` TOML
[package]

name = "henrikhodne-test"
version = "0.0.0"
authors = ["Henrik Hodne <henrik@hodne.io>"]

[dependencies.url]

git = "https://github.com/servo/rust-url"

[[bin]]

name = "henriktest"
path = "./src/test.rs"
```

Then `cargo build` will fail like this if `user.name` isn't set in your gitconfig:

```
$ cargo build --verbose
    Updating git repository `https://github.com/servo/rust-url`
Unable to update https://github.com/servo/rust-url

Caused by:
  failed to reset to the right revision

Caused by:
  [7] Config value 'user.name' was not found
```
