### ISSUE TITLE
cargo-metadata's resolve doesn't identify the kind of the dependency

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4631]
There's no way (as far as I can tell) to see if the runtime bitflags dependency of this setup is turned on or not via cargo-metadata.

```toml
[package]                                                                                                                                                                                                                                                                          
name = "foo"                                                                                                                                                                                                                                                                       
version = "0.1.0"                                                                                                                                                                                                                                                                  
authors = ["Steven Fackler <sfackler@gmail.com>"]                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                   
[dependencies]                                                                                                                                                                                                                                                                     
bitflags = { version = "0.1", optional = true }                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                   
[build-dependencies]                                                                                                                                                                                                                                                               
bitflags = "0.1"
```
