### ISSUE TITLE
Cargo allows publishing a crate that is missing files for examples

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#4752]
If you make a `Cargo.toml`:

```toml
[package]
…
include = ["Cargo.toml"]

[[example]]
path = "foo/bar.rs"
name = "broken"
```

this will publish without error, but the package will be missing files required by the example (causing unexpected error as in #4751)

https://github.com/pornel/rust-rgb/commit/08d2a21979a1e0af8c157fc6eb010fffb0a247a0
