### ISSUE TITLE
Feature request: Set cargo --features via environment variables

### ISSUE THREAD

**Issue by Centril** [rust-lang/cargo#4829]
Consider a `Cargo.toml` including
```toml
[features]
default = []
unstable = [] # Enables nightly features
```

Simply put, you'd now be able to enable `unstable` by setting `CARGO_SET_FEATURE_UNSTABLE` to "truthy". Alternatively, you'd be able to set  `CARGO_SET_FEATURES` to a comma separated string of the features you wish to enable. This of course works for any number of features by setting more env vars or adding more to the comma separated string.

Having this capability would make `.travis.yml` files capable of enabling features very succinctly without relying on `travis-cargo` or other methods. An example:

```yml
language: rust
sudo: false
dist: trusty
rust:
- 1.22.1
- stable
- beta

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: CARGO_SET_FEATURE_UNSTABLE

cache: cargo
```
