### ISSUE TITLE
Alternative registry name has to match published crates with transitive dependencies

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4848]
Say I have an alternative registry at `https://github.com/sfackler/my-index`. I configure my `.cargo/config` like so:

```toml
[registries.my-registry]
index = "https://github.com/sfackler/my-index"
```

I make a crate that depends on something in that registry, and publish it to the registry:

```toml
[package]
name = "foo"
version = "0.1.0"
authors = []

[dependencies]
bar = { version = "1.0", registry = "my-registry" }
```

Then someone else wants to depend on it. They have their `.cargo/config` configured differently:

```toml
[registries.some-registry]
index = "https://github.com/sfackler/my-index"
```

And a crate:

```toml
[package]
name = "baz"
version = "0.1.0"
authors = []

[dependencies]
foo = { version = "0.1", registry = "some-registry" }
```

This currently fails to build:

```
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/sfackler/.cargo/registry/src/github.com-5257a254d6ff3cf1/foo-0.1.0/Cargo.toml`

Caused by:
  No index found for registry: `my-registry`
```

It seems like the best option would probably be to support URLs in the `dependency.<crate>.registry` and rewrite the canonicalized Cargo.toml file that ends up in the .crate to use the URLs.

cc @alexcrichton @withoutboats
