### ISSUE TITLE
Examples requiring a nonexistent feature should be an error

### ISSUE THREAD

**Issue by whitequark** [rust-lang/cargo#4854]
I.e. this:
```toml
[features]
foo = []

[[example]]
name = "bar"
required-features = ["baz"]
```
currently just silently doesn't compile `bar` unless explicitly forced with `cargo --example bar`.
