### ISSUE TITLE
RFE: support local registry along with crates.io one

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/cargo#4883]
Currently, in Fedora packaging, we have to add
```toml
[source.local-registry]
directory = "/usr/share/cargo/registry"

[source.crates-io]
registry = "https://crates.io"
replace-with = "local-registry"
```

But it completely replaces crates.io registry. It is fine for packaging, but is not user-friendly for those who don't want to do this when developing their own projects.
