### ISSUE TITLE
How to not insert email into Cargo.toml by default when doing `cargo init`?

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#4892]
There should be an option for that.
When I do 
```toml
[cargo-new]
email = ""
```
it writes `authors = ["NAME <>"]` but it shouldn't append the `" <>"`.
