### ISSUE TITLE
`[patch]` does not work from virtual manifest

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/cargo#4934]
`cargo 0.25.0-nightly (a88fbace4 2017-12-29)`

Patching crates.io dependencies to use a Git repo revision does not work from a [virtual manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#virtual-manifest).

E.g. virtual manifest (`./Cargo.toml`):
```toml
[patch.crates-io]
ring = { git = "https://github.com/briansmith/ring", rev = "a0d65dd207fae12255bd3a470bc9983391242c1a", default-features = false, features = ["use_heap"] }
```

Workspace member package manifest (`./package/Cargo.toml`):
```toml
[dependencies]
ring = "*"
```

Building `package` will still pull in the `0.12.1` tag of `ring` according to the build output. This is confirmed by clearing out `~/.cargo/bin/registry/src/`. Building from a clean slate, `github.com-1ecc6299db9ec823/ring-0.12.1/` will be created in there, and `ring-0.12.1/`’s contents indeed do not match those of the specified `ring` revision.

This problem, if confirmed, makes it very hard to manage dependencies in large workspaces with tangled dependencies that have to be built with the `nightly` compiler.
