### ISSUE TITLE
`patch` table fails to rewrite dep to local path if it’s published in Cargo registry

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/cargo#4936]
`cargo 0.25.0-nightly (a88fbace4 2017-12-29)`

Patching crates.io dependencies to use a local path does not work from a [virtual manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#virtual-manifest).

E.g. virtual manifest (`./Cargo.toml`):
```toml
[patch.crates-io]
sitemap = { path = "./in-house-sitemap/" }
```

Workspace member package manifest (`./package/Cargo.toml`):
```toml
[dependencies]
sitemap = "*"
```
This will pull in the `sitemap` crate from crates.io, unlike similarly rewritten dependencies where no crate with the same name is published in the Cargo registry.
