### ISSUE TITLE
Explicit standard library dependencies

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/cargo#5002]
(Split from of https://github.com/rust-lang/rfcs/pull/1133)

The first task is to agree on a syntax for *explicit* stdlib deps. That RFC proposed
```toml
[depedencies]
std = { version = "*", stdlib = true }
```
But, if we are confident we can reserve the name on crates.io of everything that's part of the standard library (or isn't part of the standard library but exists in the sysroot), we don't even need a new syntax!
```toml
[depedencies]
std = "*" # work's just fine!
```

The second task is to decide whether version bounds are permitted in full generality, or restricted. Plausible restrictions would be: 
 - Exactly match the overall crate language version restrictions (however that pans out)
 - Must be unrestricted (`*`), with the intent that the language version restriction will effectively restrict it anyways.

CC @japaric @nrc
