### ISSUE TITLE
Platform specific dependencies documentation unclear

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#5005]
See here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

I depend on two platform specific crates, A and B:

```toml
[target.'cfg(foo)'.dependencies]
crate_a = "0.4.0"

[target.'cfg(bar)'.dependencies]
crate_b = "1.0.1"
```

Crate A has one feature "baz" enabled by default. I want to disable it by default, and then re-export it as my own feature baz.

IIUC I could do this to disable it by default:

```toml
[dependencies.crate_a]
default-features = false
```

- [ ] I am not sure whether this works for platform specific dependencies as well, the docs don't say. Cargo produces this warning:

```shell
warning: dependency (crate_a) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
```

After I disable all default features of crate A, I have no idea how to re-export them. The docs say I should do:

```toml
[features]
baz = [ "crate_a/baz" ] 
```

but what happens when I am on a target that is using crate_b and crate_a does not exist ? Is that still ok? EDIT: with the fix below it seems to "just work" but I am not sure if this is some behavior I can rely on. Like what happens when someone in a platform that uses `crate_b` enables the feature `baz` ?

**Comment by gnzlbg** [comment]
Ok so it seems that I have to do:

```toml
[target.'cfg(foo)'.dependencies.crates_a]
crate_a = "0.4.0"
default-features = false
```

to disable the features of a platform-specific dependency. An example of this in the docs would have helped.
