### ISSUE TITLE
Cargo can't handle remote forced tag updates

### ISSUE THREAD

**Issue by mthebridge** [rust-lang/cargo#5109]
If using a git repo for dependencies, and a tag gets force-updated on the remote repo, cargo can't seem to ever be told to pull down the new version of the tag.

Essentially I had this in my `Cargo.toml`:

```toml
[dependencies]
foo = { git = "ssh://mygit.example.com/foo.git", tag = "1.2.3" }
```

Then tag 1.2.3 got force updated and I couldn't get it to update.

Running `cargo update -p ssh://mygit.example.com/foo.git#foo:1.2.3` just gives:

```
error: There are multiple `foo` packages in your project, and the specification `ssh://mygit.example.com/foo.git#foo:1.2.3` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  ssh://mygit.example.com/foo.git#foo:1.2.3
  ssh://mygit.example.com/foo.git#foo:1.2.3
```
I couldn't find any way of getting cargo to distinguish between them. In the end I just blew away `~/.cargo/git/` and started again.  

I'm aware that force pushing tag updates to git remotes is bad practice.  But it occasionally happens and it would be nice to just have cargo resolve this on `cargo update`.

Using Cargo version: `cargo 0.25.0 (8c93e0895 2018-02-01)`

**Comment by alexcrichton** [comment]
Thanks for the report @mthebridge! This actually I think isn't necessarily related to tags but moreso related to how `cargo update` works. The `-p` flag is supposed to indicate "please update this node in the dependency graph" but it actually doesn't have syntax for differentiating these two dependencies:

```toml
[dependencies]
foo = { git = "ssh://mygit.example.com/foo.git }
bar = { git = "ssh://mygit.example.com/foo.git", tag = "1.2.3" }
```

So sort of what's happening here is that an existing bug is being exposed in Cargo where you aren't able to say "please update just this one node". @mthebridge I wonder though if you intended to use `[patch]` instead though to avoid compiling this repository twice?
