### ISSUE TITLE
.cargo/config [paths] is broken

### ISSUE THREAD

**Issue by snuk182** [rust-lang/cargo#5116]
```
nightly-x86_64-unknown-linux-gnu
rustc 1.26.0-nightly (9cb18a92a 2018-03-02)
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
```

[Cargo docs](https://doc.rust-lang.org/cargo/reference/config.html) say:
```
# An array of paths to local repositories which are to be used as overrides for
# dependencies. For more information see the Specifying Dependencies guide.
paths = ["/path/to/override"]
```
.cargo/config contents:
```toml
[target.x86_64-unknown-linux-gnu]
paths = [
  "/media/workspace/qt_core",
  "/media/workspace/qt_gui",
  "/media/workspace/qt_widgets",
  "/media/workspace/qt_core_custom_events"
]
```
`cargo build` errors with:
`error: expected a table, but found a array for `paths` in /home/snuk182/.cargo/config`

Placing a table instead of array fixes the build error:
```toml
[target.x86_64-unknown-linux-gnu]
paths = {
  qt_core="/media/workspace/qt_core",
  qt_gui="/media/workspace/qt_gui",
  qt_widgets="/media/workspace/qt_widgets",
  qt_core_custom_events="/media/workspace/qt_core_custom_events"
} 
```
but seems to have no effect on the build - the listed libraries are taken from crates.io, not from the listed paths. Neither single nor multiple path overrides work.
