### ISSUE TITLE
Document how to conditionally enable features in dependencies

### ISSUE THREAD

**Issue by aturon** [rust-lang/cargo#5139]
The `/` syntax in the `features` section appears to be undocumented.

**Comment by sharksforarms** [comment]
Any more information on this? I think this is what I want to do.

**Comment by aep** [comment]
for anyone else coming here googling:
```
[dependencies]
othercrate = "1.2.3"

[features]
myfeature = ["othercrate/otherfeature"]
```

**Comment by dwijnand** [comment]
Is it?  The `[features]` section in the manifest reference docs ([link](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section)) has the example:

```toml
# Features can be used to reexport features of other packages. The `session`
# feature of package `awesome` will ensure that the `session` feature of the
# package `cookie` is also enabled.
session = ["cookie/session"]
```

(which has been there since the feature's inception in #712)

Optimistically closing that this was just missed (I think mdbook search wasn't around in March).  If this still needs work we can reopen.

**Comment by hvenev** [comment]
How does this work if `cookie` is optional?

**Comment by mankinskin** [comment]
When `cookie` is a **dev-dependency**, this does not work:
```toml
# cookie/Cargo.toml
[features]
session = []
```
```toml
# awesome/Cargo.toml
[features]
session = ["cookie/session"]

[dev-dependencies.cookie]
path = "../cookie"
```
```toml
# app/Cargo.toml
[dependencies.awesome]
path = "../awesome"
features = ["session"]
```
The error message is this:
```sh
error: failed to select a version for `awesome`.
    ... required by package `app v0.1.0 (/home/$USER/git/app)`
versions that meet the requirements `=0.1.0` are: 0.1.0

the package `app` depends on `awesome`, with features: `cookie` but `awesome` does not have these features.


failed to select a version for `awesome` which could resolve this conflict
```
