### ISSUE TITLE
tries clone/init nonexisting repos into cache

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#5154]
Cargo.toml: 
````toml
[package]
name = "bugtest"
version = "0.1.0"
authors = ["me"]
[dependencies]
bla = { git = "https://github.com/rust-lang/carg" }
````
The repo ````rust-lang/carg```` does not exist, yet when I try to build the project, cargo will create a 
````~CARGO_HOME/git/db/carg-27f1e31d26f0744d```` with some kind of empty bare repo inside it which is weird.
(Also an error message will be show which seems fine)

Can we first validate the url before touching the cache?
