### ISSUE TITLE
dev-dependencies of package are not included when using cargo test -p

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/cargo#5156]
For example, consider a package that has dependency on memchr:
```toml
[dependencies]
memchr = "2.0.1"
```

To validate that dependencies work correctly, I would like to run tests distributed with them. In this case to validate memchr I execute following:
```
$ cargo test -p memchr
Compiling memchr v2.0.1
error[E0463]: can't find crate for `quickcheck`
```

I would expect it to work fine, because it works if I were to run tests directly from within memchr. It fails instead. As far as I can see, declaring something as dev dependency is sufficient to reproduct this issue. In this particular case, the quickcheck is a dev dependency in memchr:
```toml
[dev-dependencies]
quickcheck = { version = "0.6", default-features = false }
```
