### ISSUE TITLE
Renaming dependencies fails with same crate.

### ISSUE THREAD

**Issue by dragostis** [rust-lang/cargo#5413]
The following configuration:

```toml
cargo-features = ["rename-dependency"]

[package]
name = "test"
version = "0.1.0"
authors = []

[dependencies]
foo = "0.1"
bar = { git = "https://github.com/foo/bar", package = "foo" }
```

fails with:

```
Dependency 'foo' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
```

EDIT: minimized example.
