### ISSUE TITLE
Doctests don't work in bin targets

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#5477]
It's surprising that doctests don't work binary targets:

```sh
cargo new foo --bin
```

```rust
/// ```rust
/// assert!(false);
/// ```
fn main() {
    println!("Hello, world!");
}
```

```sh
cargo test --all
```

I'd expect the above to fail, but it looks like the doc-comment code is never ran. Even if I explicitly enable doctests for the binary:

```toml
[[bin]]
name = "foo"
path = "src/main.rs"
doctest = true
```

they still aren't run.
