### ISSUE TITLE
Renamed optional dependency should use the renamed name

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/cargo#5753]
Given a Cargo.toml dependency stated like this:

```toml
[dependencies.dalek]
package = "ed25519-dalek"
version = "0.7.0"
optional = true
```

I expected to be able to turn the dependency on with `cargo build --features dalek`. However, this does not work. `cargo build --features ed25519-dalek` does work.

I think we should be consistent here in treating the dependency name, not the package name, as the name of this optional dependency.
