### ISSUE TITLE
Renamed dependencies don't appear to be available when compiling doc-tests

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#5792]
#### `Cargo.toml`

```toml
cargo-features = ["edition", "rename-dependency"]

[package]
name = "rename-test"
edition = "2018"
version = "0.1.0"

[dependencies]
old_futures = { package = "futures", version = "0.1" }
```

#### `src/lib.rs`

```rust
pub use old_futures::Future;
```

### Error

```
→ cargo +nightly test
   Compiling rename-test v0.1.0 (file:///home/wim/sources/rename-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41s
     Running target/debug/deps/rename_test-4457732684cc54fc

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests rename-test
error[E0463]: can't find crate for `old_futures`
 --> /home/wim/sources/rename-test/src/lib.rs:1:9
  |
1 | pub use old_futures::Future;
  |         ^^^^^^^^^^^ can't find crate

error: test failed, to rerun pass '--doc'
```

### Versions

```
→ cargo +nightly --version
cargo 1.29.0-nightly (506eea76e 2018-07-17)

→ rustc +nightly --version
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
```

(CC #5653)
