### ISSUE TITLE
`cargo package` does not always work if used with 2018 edition

### ISSUE THREAD

**Issue by orium** [rust-lang/cargo#5906]
To reproduce create a project with the following `Cargo.toml`:

```toml
cargo-features = ["edition"]

[package]
name = "example"
version = "0.0.0"
authors = ["Example <example@example.com>"]

edition = "2018"

[package.metadata.docs.rs]
features = ["foobar"]
```
and an empty file as `src/lib.rs`.

When you try to package this will happen:

```text
orium@laptop-orion cargofixbug % cargo package --allow-dirty --verbose
[...]
   Packaging example v0.0.0 (file:///home/orium/tmp/cargofixbug)
   Archiving .codecov.yml
   Archiving .gitignore
   Archiving .rustfmt.toml
   Archiving .travis.yml
   Archiving Cargo.toml
error: failed to prepare local package for uploading

Caused by:
  values must be emitted before tables
```
