### ISSUE TITLE
Allow specifying dependencies per feature

### ISSUE THREAD

**Issue by sdroege** [rust-lang/cargo#5954]
Most feature-dependency correspondences can currently be modeled by making the dependency optional but having the feature depend on this.

This is not possible (from what I see) if "feature-a" and "feature-b" depend on the same crate but in different versions, as each crate can only be specified once.

A syntax like the following would seem consistent for that case (and could also provide another way of specifying feature-dependant dependencies in general).

```toml
[target.'cfg(feature = "feature-a")'.dependencies]
foobar = "0.1"

[target.'cfg(feature = "feature-b")'.dependencies]
foobar = "0.2"
```

**Comment by alexcrichton** [comment]
I think that this may also largely be supported by https://github.com/rust-lang/cargo/issues/5653? May make it a bit easier to specify as well!

**Comment by mmstick** [comment]
Encountered a similar issue where a workspace is split into multiple sub-crates, and each rely on specifying shared features of the main crate dependency. Something like this doesn't seem to work at all:

```toml
[features]
default = [ "fwupd", "system76" ]
fwupd = []
system76 = []

[target.'cfg(all(not(feature = "fwupd"), feature = "system76"))'.dependencies]
firmware-manager = { path = "../", default-features = false, features = [ "system76" ] }

[target.'cfg(all(feature = "fwupd", not(feature = "system76")))'.dependencies]
firmware-manager = { path = "../", default-features = false, features = [ "fwupd" ] }

[target.'cfg(all(feature = "fwupd", feature = "system76"))'.dependencies]
firmware-manager = { path = "../", default-features = false, features = [ "fwupd", "system76" ] }
```

```
cargo build --manifest-path gtk/Cargo.toml --no-default-features --features system76
```

**Comment by andrewdavidmackenzie** [comment]
I was trying to solve a problem similar to this one, and coincidentally found out that (it appears) that "static" cannot be used as a feature name, I get strange errors when using it and changing the feature name fixed it. Is that known/expected or I should submit a bug.

**Comment by sergiimk** [comment]
Hopefully this will save someone an hour of googling.

If you have a library `a` that depends on `b`, and you want to support two or more major versions of `b` that are slightly incompatible:

In `a`'s Cargo.toml:
```toml
[dependencies]
b-5 = { package = "b", version = "^5", optional = true }
b-6 = { package = "b", version = "^6", optional = true }

[features]
default = ["use-b-6"]
use-b-5 = ["b-5"] 
use-b-6 = ["b-6"]
```
Create a `b_shim.rs` in `a`:
```rust
#[cfg(feature = "use-b-5")]
pub use b_5::*;
#[cfg(feature = "use-b-6")]
pub use b_6::*;
```
Instead of `use b::foo` import via `crate::b_shim::foo`.

Application that uses `a` can now chose to use it with older `b` by:
```toml
[dependencies]
b = "^5"
a = { version = "*", default-features = false, features = ["use-b-5"] }
```

This is more work than it should be....

**Comment by epage** [comment]
With package renaming, we've satisfied the main request and there is a great example just above of that.

As for this case
```toml
[features]
default = [ "fwupd", "system76" ]
fwupd = []
system76 = []

[target.'cfg(all(not(feature = "fwupd"), feature = "system76"))'.dependencies]
firmware-manager = { path = "../", default-features = false, features = [ "system76" ] }

[target.'cfg(all(feature = "fwupd", not(feature = "system76")))'.dependencies]
firmware-manager = { path = "../", default-features = false, features = [ "fwupd" ] }

[target.'cfg(all(feature = "fwupd", feature = "system76"))'.dependencies]
firmware-manager = { path = "../", default-features = false, features = [ "fwupd", "system76" ] }
```
that can be done as
```toml
[features]
default = [ "fwupd", "system76" ]
fwupd = ["dep:firmware-manager", "firmware-manager/fwupd"]
system76 = ["dep:firmware-manager", "firmware-manager/system76"]

[dependencies]
firmware-manager = { path = "../", default-features = false, optional = true }
```

As this seems resolved, I'm closing it.  If there is a reason to re-open this, let us know!

**Comment by nathanielsimard** [comment]
I need to use something like that but for a different use case. I need to activate a feature flag on a dependency when that dependency is activated **_and_** the other feature flag is activated as well:

```toml
[features]
flag1 = ["crate1"]
flag2 = ["crate2"]
someflag = []

[target.'cfg(all(feature = "flag1",  feature = "someflag"))'.dependencies]
crate1 = { ..., features = ["someflag"] }

[target.'cfg(all(feature = "flag1",  not(feature = "someflag")))'.dependencies]
crate1 = { ..., features = [] }

[target.'cfg(all(feature = "flag2",  feature = "someflag"))'.dependencies]
crate2 = { ..., features = ["someflag"] }

[target.'cfg(all(feature = "flag2",  not(feature = "someflag")))'.dependencies]
crate2 = { ..., features = ["someflag"] }
```

If I do something like this:

```toml
[features]
flag1 = ["crate1"]
flag2 = ["crate2"]
someflag = ["crate1/someflag", "crate2/someflag"]
```

Then both crates are going to be activated when only the flag `someflag` is activated.

**Comment by epage** [comment]
Is [weak features](https://doc.rust-lang.org/cargo/reference/features.html#dependency-features) what you need?
```toml
someflag = ["crate1?/someflag", "crate2?/someflag"]
```

**Comment by nathanielsimard** [comment]
@epage Yes exactly! I didn't know it even existed, thanks a lot 🙏

**Comment by Sytten** [comment]
There is still a use case that is not covered with the weak feature.

```toml
[features]
default = ["myfeature"]
myfeature = []
simd = []

[target.'cfg(all(feature = "simd",  feature = "myfeature"))'.dependencies]
base64-simd = "0.8.0"

[target.'cfg(all(not(feature = "simd"),  feature = "myfeature"))'.dependencies]
base64 = "0.22.0"
```

I know you can do `myfeature` and `myfeature-simd`, but it really is not that nice especially if you have multiple features that can have a simd variant.
