### ISSUE TITLE
cargo doesn't consider crate renaming for optional dependency

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/cargo#5962]
cargo can't install `futures-util-preview:0.3.0-alpha.4`. That crate uses the `rename-dependency` feature like this:

```toml
cargo-features = ["rename-dependency"]

[features]
compat = ["futures01"]

[dependencies]
futures01 = { package = "futures", version = "0.1", optional = true }
```

I have a Cargo.toml that depends on `futures-util-preview`

```toml
[dependencies]
futures-util-preview = "0.3.0-alpha.4"
```

`cargo update` fails with

```
error: no matching version `^0.3.0-alpha.4` found for package `futures-util-preview`
location searched: registry `https://github.com/rust-lang/crates.io-index`
versions found: 0.2.2
```

With `RUST_LOG=debug` :

```
INFO 2018-09-02T20:33:03Z: cargo::sources::registry::index: failed to parse `futures-util-preview` registry package: Feature `compat` includes `futures01` which is neither a dependency nor another feature
```

This is with latest nightly cargo `cargo 1.29.0-nightly (0ec7281b9 2018-08-20)`.

@Nemo157 suggested

>Seems related to rust-lang/cargo#5753, probably the registry related code wasn’t changed to behave in the same way.

Ref: https://github.com/rust-lang-nursery/futures-rs/issues/1247
