### ISSUE TITLE
--build-plan fails when dev-dependencies are present

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/cargo#6082]
Hi! It looks like there's a problem attempting to grab a build plan from libraries that use `dev-dependencies`.

Toolchain that fails:

```
rustc 1.30.0-nightly (f49f6e73a 2018-09-23)
cargo 1.31.0-nightly (de314a8b2 2018-09-21)
```

Toolchain that succeeds:

```
rustc 1.30.0-nightly (63c75d375 2018-09-21)
cargo 1.30.0-nightly (a5d829494 2018-09-13)
```

If I have a `Cargo.toml` that looks like:

```toml
[package]
name = "build-plan-test"
version = "0.0.0"

[dev-dependencies]
libc = "*"
```

When running `cargo build -Z unstable-options --build-plan --verbose`, I get the following output:

```
     Running `rustc
        --crate-name build_plan_test src/lib.rs
        --color always
        --crate-type lib
        --emit=dep-info,link
        -C debuginfo=2
        -C metadata=2746e0b9ac45f8b8
        -C extra-filename=-2746e0b9ac45f8b8
        --out-dir /Users/user/dev/build-plan-test/target/debug/deps
        -C incremental=/Users/user/dev/build-plan-test/target/debug/incremental
        -L dependency=/Users/user/dev/build-plan-test/target/debug/deps`
error: failed to find libc v0.2.43 
```

**Comment by KodrAus** [comment]
Sorry, I forgot to note that this `Cargo.toml` does output a build plan successfully:

```toml
[package]
name = "build-plan-test"
version = "0.0.0"

[dependencies]
libc = "*"
```

The difference there is that `libc` is declared as a regular `dependency` rather than a `dev-dependency`.
