### ISSUE TITLE
Workspace crates should have an implicit patch for crates in the workspace.

### ISSUE THREAD

**Issue by carllerche** [rust-lang/cargo#6126]
Whenever using workspace crates, I often end up having to add a list of patches in the root `Cargo.toml` for all the sub crates. For example, in `tokio`:

```toml
[patch.crates-io]
tokio = { path = "." }
tokio-async-await  = { path = "./tokio-async-await" }
tokio-codec = { path = "./tokio-codec" }
tokio-current-thread = { path = "./tokio-current-thread" }
tokio-executor = { path = "./tokio-executor" }
tokio-fs = { path = "./tokio-fs" }
tokio-io = { path = "./tokio-io" }
tokio-reactor = { path = "./tokio-reactor" }
tokio-signal = { path = "./tokio-signal" }
tokio-tcp = { path = "./tokio-tcp" }
tokio-threadpool = { path = "./tokio-threadpool" }
tokio-timer = { path = "./tokio-timer" }
tokio-tls = { path = "./tokio-tls" }
tokio-udp = { path = "./tokio-udp" }
tokio-uds = { path = "./tokio-uds" }
```

This is because, when compiling examples and benches (at least), the workspace crates are not, pulling from crates.io.
