### ISSUE TITLE
[patch] section is unused, but causes a dependency to downgrade

### ISSUE THREAD

**Issue by kuviman** [rust-lang/cargo#6204]
**Problem**

[patch] section is unused, but causes a dependency to downgrade.

**Steps**

1. Sample `Cargo.toml`:
```toml
[package]
name = "hello"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[dependencies]
glutin = "0.18.0"
rusttype = { version = "0.7.1", features = [ "gpu_cache" ] } # Without this thing everything works as expected
```
2. Everything works correctly (uses the latest version of `winit` which is going to be patched)
3. Try to apply a patch:
```toml
[patch.crates-io]
winit = { git = "https://github.com/tomaka/winit" }
```
4. `cargo update`:
```
    Updating git repository `https://github.com/tomaka/winit`
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding redox_syscall v0.1.40
      Adding remove_dir_all v0.5.1
    Updating smithay-client-toolkit v0.3.0 -> v0.2.6
      Adding tempfile v3.0.4
    Updating winit v0.17.2 -> v0.17.1
```

5. Further `cargo update`s don't even try to update patch's git repository, the patch itself is shown as unused in `Cargo.lock`:

```toml
[[patch.unused]]
name = "winit"
version = "0.17.2"
source = "git+https://github.com/tomaka/winit#062bb0cef23b82ae31085ca25b79429474adca3e"
```

**Possible Solution(s)**

I think it would be useful to at least be notified that the patch is not being used. I would prefer to have an error here.

**Notes**

Output of `cargo version`:
```
cargo 1.29.0 (524a578d7 2018-08-05)
```

Nightly cargo does the same thing.

So, this was noticed because I was using a patched version of `winit`. Since I added the patch, a new version of the crate was published. When that happened `cargo update` downgraded `winit`, so neither the initial patched version nor the newly published one was used, resulting in the patch being effectively undone.
