### ISSUE TITLE
Unused optional dependencies cause "links" conflicts

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#6231]
```toml
[package]
name = "foo"
version = "0.1.0"

[dependencies]
libz-sys = { version = "1.0.25", optional = true }
cloudflare-zlib-sys = { version = "0.1", optional = true }
```

Both `libz-sys` and `cloudflare-zlib-sys` contain `links = "z"`, because they do link to a (fork of) libz with the same global C symbols.

I would like user of the "foo" crate to be able to enable either one of these crates providing "z", and have a `links` conflict only if both crates accidentally get enabled at the same time.

Unfortunately, it looks like Cargo is resolving `links` for all crates, even unused ones, without observing whether they are optional. 

> error: failed to select a version for `cloudflare-zlib-sys`.
    ... required by package `foo v0.1.0`
> versions that meet the requirements `^0.1` are: 0.1.2, 0.1.1, 0.1.0
>
> the package `cloudflare-zlib-sys` links to the native library `z`, but it conflicts with a previous  package which links to `z` as well:
> package `libz-sys v1.0.25`
>    ... which is depended on by `foo v0.1.0`
