### ISSUE TITLE
Cargo patch is finickier than it needs to be

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#6341]
The current form of the `[patch]` section is that you do something like:

```toml
[patch.crates-io]
foo = { path = "../../foo" }
```

or
