### ISSUE TITLE
Build a crate with specific variables

### ISSUE THREAD

**Issue by yaa110** [rust-lang/cargo#6373]
**Describe the problem you are trying to solve**
During the build of [nginx crate](https://crates.io/crates/nginx), I want to let users specify the version of Nginx when they use this crate as a dependency.

**Describe the solution you'd like**

```rust
// build.rs of crate_a
fn main() {
    let val1 = vars!("key1");
    let val2 = vars!("key2");
}
```

```toml
# Cargo.toml of crate_b
[dependencies]
crate_a = { version = "0.2.0",  vars = ["key1:val1", "key2:val2"] }
```

**Comment by lukaslueg** [comment]
[openssl-rust](https://github.com/sfackler/rust-openssl) may demonstrate a way to do this

**Comment by Eh2406** [comment]
How do `vars` differ from `features`?

**Comment by yaa110** [comment]
`vars` is comma separated strong of key: value pairs. It should be used in `build.rs` file.

**Comment by oliver-giersch** [comment]
The lack of such a feature (or something similar) is a major pain in the rear for me currently.

I'd like to let users of my [hazptr](https://github.com/oliver-giersch/hazptr) crate define some compile time parameters for performance fine tuning. Since this crate would likely only be used by other libraries, setting a global environmental variable upon invocation of cargo (e.g. `env HAZPTR_SCAN_THRESHOLD=1 cargo build`) is not a realistic option.

I've tried to do this through build scripts but failed, since apparently you can not affect environment variables through build scripts across crate boundaries.

**Comment by Perlmint** [comment]
I need this feature too!
In my case, My project is determining the features of the target by a combination of variables. Currently, I worked around this by using environment variables and build script. It works, but environment variables don't affect the build hash, So, even if environment variables are changed, cargo does not rebuild it. To prevent using the wrong build, I'm using different target dirs for each combination, but it wastes too many spaces and time to build the same dependencies.

Also, I'm interested in implementing this. Can I take this?

Here are more details to implement this. If there is any suggestion, comment, please.

- Define available vars & set the default value of it (Optional) in the Cargo.toml.
- Expose each vars as an environment variable to access vars in the build script.
- Update build metadata hash with specified vars.
- Add option setting vars to build command.

**Comment by yaa110** [comment]
@Perlmint

you can use the following in your build.rs main function:

```rust
println!("cargo:rerun-if-env-changed=YOUR_ENV");
```

**Comment by Perlmint** [comment]
@yaa110
Hmm... Before I tried to use `rerun-if-env-changed`, It looks not working on windows. But today, I tried this with the simple reproduction case on OSX. It works. 😂 I'll retry this on the windows later.

**Comment by epage** [comment]
https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618 might be an option for this.

**Comment by wyatt-herkamp** [comment]
So I was thinking about this earlier. Then I saw this issue.   
Now I was thinking of it more of an expanded form of features

```toml
[features]
default = ["tls:rustls"]
[features.tls]  
options = ["native", "rustls"]  
rustls = ["actix-web/rustls-0_21", "dep:rustls", "rustls-pemfile", "lettre/tokio1-rustls-tls"]  
native-tls = ["lettre/tokio1-native-tls", "openssl", "actix-web/openssl"]  
required = true # An Option must be selected
```

It would be seen as more of "features with options"

```console
cargo build --features tls:rustls
```

And to use them in creates

```toml
[dependencies]
my_crate = {version: "0.1.0", features = ["tls:rustls"]}
```
