### ISSUE TITLE
Cargo 1.33.0-nightly (0d1f1bbea 2018-12-19) only pulling the latest version

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang/cargo#6509]
**Problem**
Cargo seems to be ignoring the version asked for in Cargo.toml and is pulling the latest

**Steps**
Create a basic binary project, then add a dependency:
```toml
[dependencies]
cortex-m-rt = "0.6.5" ; Downloads 0.6.7 instead
serde = "1.0.80" ; Downloads 1.0.84 instead
```

Run `cargo build`:

```text
Fauna2:test-cargo me$ cargo build
...
   Compiling serde v1.0.84
   Compiling cortex-m-rt v0.6.7
...
```

**Possible Solution(s)**

**Notes**
I *can* force it by changing Cargo.lock manually, delete the [metadata] section, but doing a `cargo update` brings it back:

```text
    Updating crates.io index
    Updating cortex-m-rt v0.6.5 -> v0.6.7
```

Infos:
* cargo 1.33.0-nightly (0d1f1bbea 2018-12-19)
* macOS 10.14.1
