### ISSUE TITLE
`cargo build --release` ignores `dependencies` in favor of `dev-dependencies` for shared sub-dependency

### ISSUE THREAD

**Issue by flagello** [rust-lang/cargo#6549]
`cargo new package --lib`

`lib.rs`
```rust
#![no_std]
```

`Cargo.toml`
```toml
[package]
name = "package"
version = "0.1.0"
edition = "2018"

[dependencies]
memchr = { version = "2", default-features = false }

[dev-dependencies]
term-table = "1.1"
```

`cargo tree`
```
package v0.1.0                                
└── memchr v2.1.2
    ├── cfg-if v0.1.6
    └── libc v0.2.46
    [build-dependencies]
    └── version_check v0.1.5
[dev-dependencies]
└── term-table v1.1.0
    ├── lazy_static v1.2.0
    ├── regex v1.1.0
    │   ├── aho-corasick v0.6.9
    │   │   └── memchr v2.1.2 (*)
    │   ├── memchr v2.1.2 (*)
    │   ├── regex-syntax v0.6.4
    │   │   └── ucd-util v0.1.3
    │   ├── thread_local v0.3.6
    │   │   └── lazy_static v1.2.0 (*)
    │   └── utf8-ranges v1.0.2
    └── wcwidth v1.0.1
```

`cargo build --release`
```
   Compiling version_check v0.1.5                                               
   Compiling libc v0.2.46                                                       
   Compiling cfg-if v0.1.6                                                      
   Compiling memchr v2.1.2                                                      
   Compiling package v0.1.0
    Finished release [optimized] target(s) in 3.76s
```

`cargo build --release --target thumbv7em-none-eabihf`
```
   Compiling libc v0.2.46
   Compiling version_check v0.1.5
   Compiling cfg-if v0.1.6
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

`rustup show`
```
installed targets for active toolchain
--------------------------------------

thumbv7em-none-eabihf
x86_64-apple-darwin
```

`cargo version`
```
cargo 1.33.0-nightly (34320d212 2019-01-03)
```

**Workaround**

`Cargo.toml`
```toml
[package]
name = "package"
version = "0.1.0"
edition = "2018"

[dependencies]
memchr = { git = "https://github.com/BurntSushi/rust-memchr", tag = "2.1.2", default-features = false }

[dev-dependencies]
term-table = "1.1"
```

`cargo build --release`
```
    Updating git repository `https://github.com/BurntSushi/rust-memchr`
   Compiling version_check v0.1.5
   Compiling cfg-if v0.1.6
   Compiling memchr v2.1.2 (https://github.com/BurntSushi/rust-memchr?tag=2.1.2#437a177a)
   Compiling package v0.1.0
    Finished release [optimized] target(s) in 3.74s
```

`cargo build --release --target thumbv7em-none-eabihf`
```
   Compiling version_check v0.1.5
   Compiling cfg-if v0.1.6
   Compiling memchr v2.1.2 (https://github.com/BurntSushi/rust-memchr?tag=2.1.2#437a177a)
   Compiling package v0.1.0
    Finished release [optimized] target(s) in 2.52s
```

`cargo tree`
```
package v0.1.0
└── memchr v2.1.2 (https://github.com/BurntSushi/rust-memchr?tag=2.1.2#437a177a)
    └── cfg-if v0.1.6
    [build-dependencies]
    └── version_check v0.1.5
[dev-dependencies]
└── term-table v1.1.0
    ├── lazy_static v1.2.0
    ├── regex v1.1.0
    │   ├── aho-corasick v0.6.9
    │   │   └── memchr v2.1.2
    │   │       ├── cfg-if v0.1.6 (*)
    │   │       └── libc v0.2.46
    │   │       [build-dependencies]
    │   │       └── version_check v0.1.5 (*)
    │   ├── memchr v2.1.2 (*)
    │   ├── regex-syntax v0.6.4
    │   │   └── ucd-util v0.1.3
    │   ├── thread_local v0.3.6
    │   │   └── lazy_static v1.2.0 (*)
    │   └── utf8-ranges v1.0.2
    └── wcwidth v1.0.1
```
