### ISSUE TITLE
Extend aliases: allow arbitrary commands

### ISSUE THREAD

**Issue by theduke** [rust-lang/cargo#6575]
The `[alias]` configuration is very useful.

It would be even more useful if there was a way to not only define aliases for `cargo`, but to run arbitrary scripts.

I'm imagining something like how npm works, where you can define arbitrary scripts that can be executed with `npm run NAME`.
This is very widely used in the JS ecosystem and a great convenience utility.

It would allow a unified way to execute project-related convenience scripts, etc.

EG:

```toml
[script]
deploy = "./bin/deploy.sh"
generate-keys = "./bin/generate-keys.sh"
# Conflicting name, see below
publish = "./bin/publish.sh"
...
```

Scripts would have the lowest priority, after built in commands, aliases and external binaries.
Disambiguation could be enabled by the `cargo script` command, eg : `cargo script publish && cargo script deploy`.

**Comment by djmitche** [comment]
Git's approach is
```
    gist = "!/bin/sh -c 'git add --all . && git commit -m x && git push'"
```
I think the special-case is a string beginning with `!`.  We could do the same with aliases.

**Comment by epage** [comment]
The challenge is what syntax do you support.  Bonus points for cross platform.

[deno_task_shell](https://crates.io/crates/deno_task_shell) and [duckscript](https://crates.io/crates/duckscript) would be two options.;

**Comment by rnln** [comment]
I see the integration of an additional scripting language for this functionality as too costly for the benefits provided. Despite the cross-platform bonuses, this solution increases bulkiness, reduces maintainability, and is less flexible and straightforward compared to alternatives. One of the more flexible and simple alternatives is passing values in a `[script]` object as script arguments to `sh`, `cmd.exe`, and other shells.

The cross-platform issue can be addressed by utilizing nested objects combined with shell settings:

```toml
[alias]
# Keeping `alias` and `script` separate avoids the need for less obvious conventions like `!`

[script]
greet = "echo -n 'Hello, ' && echo 'developer!'"

[script.powershell]
# Acts as a fallback for systems where the default shell is not found,
# and when the script was launched in PowerShell
greet = "Write-Host -NoNewline 'Hello, '; if ($?) { Write-Host 'developer!'}"

[shell]
default = "sh"
```
