### ISSUE TITLE
Empty version constraints are allowed and interpreted as wildcards?

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#6597]
This is apparently a valid dependency declaration:

```toml
[dependencies]
serde = ""
```

It seems to behave like `serde = "*"`.

I think this is probably unintended?
