### ISSUE TITLE
"Multiple dependencies listed for the same crate must all have the same name" error doesn't print the name of the crate

### ISSUE THREAD

**Issue by DarkEld3r** [rust-lang/cargo#6601]
**Problem**

"Multiple dependencies listed for the same crate must all have the same name" error message contains the name of the problematic crate, but it doesn't print the name of the crate where this problem occurs. In workspaces with multiple packages it isn't so obvious where the problem is.

The problem can easily occur when giving different names in `dependencies` and `dev-dependencies` sections.

**Steps**

1. Create a new empty project.
2. Add a duplicated dependency, for example:
```toml
[dependencies]
r = { package = "rand", version = "0.6" }
ra = { package = "rand", version = "0.6" }

```
3. Try to build it.

**Notes**

Output of `cargo version`: cargo 1.32.0 (8610973aa 2019-01-02)
