### ISSUE TITLE
adding feature `rerun_if_changed` to Cargo.toml directly

### ISSUE THREAD

**Issue by frehberg** [rust-lang/cargo#6689]
Cargo.toml does not support dependency declarations against local text files, for example lex/pest or IDL-files. Such files may be read by procedural macros, generating Rust code from it, for example crate `test-generator`

If I want that `cargo` is rebuilding the crate if such files have changed, it is necessary to define a build-script `build.rs` that is writing a command to std-out. 
```
### build.rs
println!("cargo:rerun-if-changed=MY-FILE-OR-DIRECTORY");
```
The cargo process is reading the output and checking timestamps of those files, to decide for rerunning the build-process.

The problem is, that such dependencies must be encoded in build.rs, instead it should be declared within `Cargo.toml`  direclty.

I would like to propose a new feature for `Cargo.toml`, simplifying dependency-declaration against external files or changes in directories.

```
[rerun_if_changed]
MY_FILE1
MY_FILE2
CHECK/LOCAL/DIR/FOR/NEW/FILES/
 ```

**Comment by epage** [comment]
Could you give a reproduction case where a file that is needed for the build isn't considered when rebuilding?

**Comment by qknight** [comment]
@frehberg I find this a very good idea!

I've been playing with the **libnix** integration in cargo at https://internals.rust-lang.org/t/cargo-fingerprinting/23834/7 and I'd very much would love such a feature:

```toml
[package]
name = "my-crate"
version = "0.1.0"

[build-script]
out-dir = "/tmp/generated"  # Absolute
rerun-if-changed = [ # Relative to package root
    "src/extra/*.c",
    "include/**/*.h",
    "data/config.json",
]
rerun-if-env-changed = ["MY_BUILD_VAR"]
```

This should replace the explicit println! of cargo::rerun-if-changed=

@epage 

Updated:

The nix builder takes the whole source code as input, resulting in a forced rebuild every time a change happens, even when only adding a "space" to the README.md for that matter. This problem only occurs with iterative builds.

With the cargo legacy approach, it requires the build to be executed, in order to gather the list of input files which 'if changed should trigger the rebuild'. 

So when using the nix-backend for cargo it would be the best if we could parse Cargo.toml from cargo, extract the files+directories and then pass a list of files into the nix file and call the 'nix build' on that. This way we minimize the amount of files exposed to nix build and have no rebuilds triggered by files which are not important for the actual target. I hope this makes sense.
