### ISSUE TITLE
Add a way to define relative paths in rustc-link-search

### ISSUE THREAD

**Issue by oblique** [rust-lang/cargo#6725]
**Describe the problem you are trying to solve**

I'm writing a project that uses `zmq` and `zmq-sys` which need to be cross-compiled for `arm-unknown-linux-gnueabi`.

`zmq-sys` doesn't compile libzmq on its own but we can specify the lib and include directories by using `LIBZMQ_LIB_DIR` and `LIBZMQ_INCLUDE_DIR`. However [`zmq`'s build.rs](https://github.com/erickt/rust-zmq/blob/d489384b09170916c0ae61ff216a8071a7bb925d/Cargo.toml#L164) requires `zmq-sys`, which means I also need a compiled binary for `x86_64-unknown-linux-gnu` target too. So I can not just use the environment variables of `zmq-sys` since `LIBZMQ_LIB_DIR` will point to a wrong directory.

I did the following workaround:

```toml
[target.arm-unknown-linux-gnueabi]
linker = "arm-none-linux-gnueabi-gcc"

[target.arm-unknown-linux-gnueabi.zmq]
rustc-link-search = ["native=/home/user/zmq-example/vendor/libzmq/lib/arm"]
rustc-link-lib = ["static=zmq", "dylib=stdc++"]

[target.x86_64-unknown-linux-gnu.zmq]
rustc-link-search = ["native=/home/user/zmq-example/vendor/libzmq/lib/x86_64"]
rustc-link-lib = ["static=zmq", "dylib=stdc++"]
```

The problem with the above workaround is that all developers need to have the same absolute path to the compiled binaries.

**Describe the solution you'd like**

I would like to have a way to define a relative path in `rustc-link-search`.

Another solution could be a way to define a environment variables per target.
