### ISSUE TITLE
Different default targets for `cargo build` and `cargo test`?

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/cargo#6784]
**Describe the problem you are trying to solve**

Cargo currently provides a `build.target` configuration key that allows to change the default target triple. This changes the default target for all cargo commands, including `cargo build`, `cargo run`, `cargo test` and `cargo bench`. For embedded/OS crates it often makes sense to set that key so that the project is automatically built for the bare-metal target system instead of the host system.

The problem is that one might still want to run the `cargo test` and `cargo bench` commands on the host architecture because they depend on `std` (and thus don't work on the embedded target). Currently the only way to do this is to specify the full host triple on each `cargo test` invocation, which is not portable across different host systems.

**Describe the solution you'd like**

It would be nice if there would be an additional `build.build-target` configuration key that overrides the target only for `cargo build`, `cargo check`, and `cargo run`, but not for `cargo test` and `cargo bench`.

**Notes**

I'm happy to create a PR for this if something like this is desired.

**Comment by fluffysquirrels** [comment]
In case it helps, I personally solved this issue for embedded development with shell scripts or make files for each scenario, so one for running tests on the host, one for flashing the microcontroller, and so on.

**Comment by phil-opp** [comment]
Thanks for the suggestion! I want to avoid Makefiles and external scripts when possible, since they are not really portable across OSs. However, I found a different solution to my problem in the [custom test framework](https://github.com/rust-lang/rust/pull/53410) feature, which allows me to run my tests on the target system.

If nobody else is interested in this issue I will close it in a week.

**Comment by SomeoneToIgnore** [comment]
Not sure if it helps you to find the motivation to submit the actual PR, but I totally agree that this feature is nice to have.
I think at least reopening the issue would be a nice thing to do.

**Comment by phil-opp** [comment]
@SomeoneToIgnore As noted above, I found a better solution to my problem and I don't have the time for implementing a solution to this problem at the moment. However, I already opened a draft PR at https://github.com/rust-lang/cargo/pull/6825, which might be useful if someone wants to implement it (but please consider the review comments in the PR thread).

I'm happy to reopen this issue, though!

**Comment by torkeldanielsson** [comment]
I would very much like this feature! My target is severely memory constrained so running tests on it is not such a nice proposition.

**Comment by josephlr** [comment]
We would also find this useful for https://github.com/cloud-hypervisor/rust-hypervisor-firmware.

We want our firmware to be built with one target, and then for our integration tests to be built for the host target.

**Comment by seanybaggins** [comment]
I am working on this issue. Expect a pull request in the near future.

**Comment by josephlr** [comment]
@seanybaggins one issue that came up in #6825, is that having a `build.build-target` key is a little strange. It might make more sense to have a `build.test-on-host` boolean which will run the `cargo test` stuff with the host target, while running `cargo build` uses `built.target`.

I'm actually not sure which approach is best here, but for both my and @phil-opp's use case, we want to build binaries on the custom target, and then run tests on the host.

**Comment by seanybaggins** [comment]
@josephlr This is way better than what I was going to implement. I was going to have a `[test]` section within the `.cargo/config.toml` file. This led to some issues for getting the context for when to know to use the `[test]` config or the `[build]` config. I will work on just implementing your suggestions.

**Comment by seanybaggins** [comment]
Just want to double check... we want the `.cargo/config.toml` build options to be the following?

```toml
[build]
jobs = 1                  # number of parallel jobs, defaults to # of CPUs
rustc = "rustc"           # the rust compiler tool
rustc-wrapper = "…"       # run this wrapper instead of `rustc`
rustdoc = "rustdoc"       # the doc generator tool

# Still wondering if this should be just `target` or `build-target`
target = "triple"         # build for the target triple (ignored by `cargo install`)

# Build configs to be added
lib-target = "triple"
bin-target = "triple"
test-target = "triple"

target-dir = "target"     # path of where to place all generated artifacts
rustflags = ["…", "…"]    # custom flags to pass to all compiler invocations
rustdocflags = ["…", "…"] # custom flags to pass to rustdoc
incremental = true        # whether or not to enable incremental compilation
dep-info-basedir = "…"    # path for the base directory for targets in depfiles
pipelining = true         # rustc pipelining
```
