### ISSUE TITLE
Allow arbitrary Horn clauses for inter-feature dependencies.

### ISSUE THREAD

**Issue by hvenev** [rust-lang/cargo#6789]
Sometimes it makes sense to enable feature Z if both features Y and feature Z are enabled. Simple example: #6658 

```toml
[dependencies]
krate = { optional = true, version = "1.2.3" }

[features]
foo = []
krate = []
"krate+foo" = [ "krate/bar" ]
```

Another example pops up in native library bindings:
```toml
name = "libB-sys"

[dependencies]
libA-sys = { optional = true, version = "4.5.6" } # libA is used by libB to do featX

[features]
vendored = [] # Build the bundled copy of the library instead of using the system one
featX = []
"vendored+featX" = "libA-sys"
```

It may also make sense to have clauses where resolution fails:
```toml
[features]
"do-it-this-way+do-it-that-way" = false
```

Note that this does not permit requirements of the form "featX or featT must be enabled". The naive algorithm that only enables a feature when all prerequisites are enabled still works (https://www.doc.ic.ac.uk/~rak/papers/kowalski-van_emden.pdf, the "model intersection property")

**Comment by epage** [comment]
> "do-it-this-way+do-it-that-way" = false

This runs afoul of feature unification.  We have #2980 discussing the use cases further with https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618 as a concrete proposal.

**Comment by epage** [comment]
```toml
[dependencies]
krate = { optional = true, version = "1.2.3" }

[features]
bar = []
foo = [ "krate" ]
"foo+bar" = [ "krate/bar" ]
```

I believe this would now be solved by
```toml
[dependencies]
krate = { optional = true, version = "1.2.3" }

[features]
bar = ["krate?/bar"]
foo = [ "krate" ]
```
See https://doc.rust-lang.org/cargo/reference/features.html#dependency-features for more on `?` (weak features)

**Comment by Zefirchiky** [comment]
Just a copy of solutions from [#16695](https://github.com/rust-lang/cargo/issues/16695) 

1. Treat features as dependencies. This will allow things like this:

```toml
[dependencies]
serde = { version = "1.0.0", optional = true }
serde_json = { version = "1.0.0", optional = true }

[features]
json = []  # Enables `Json` file for my library
serde = ["dep:serde", "json?/serde_json"]  # Enable `serde_json` only if `serde` AND `json` are active
# OR
serde = ["dep:serde", "json?/dep:serde_json"] 
```

2. Allow dependencies to be activated IF others are activated, like weak dependency, but for other dependencies. This is a bit of a workaround:

```toml
...
[features]
json = ["_serde_json"]
serde = ["dep:serde"] 
_serde_json = ["serde?/dep:serde_json"]
```

Or with a compact if-else (condition ? true : false):

```toml
...
[features]
json = ["serde?serde_json:other_dep"]  # Where `else` part is optional
serde = ["dep:serde"] 
```
