### ISSUE TITLE
Add a warning when running `cargo test -p` on an optional dependency

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#683]
Example `Cargo.toml`:

``` toml
[package]
name = "test"
version = "0.0.1"
authors = []

[dependencies.sub]
path = "sub"
optional = true
```

Running `cargo test -p sub` leads to `package id specification "sub" matched no packages`.

Removing `optional = true` or adding `[features] default = [ "sub" ]` removes the error.
