### ISSUE TITLE
Enabling target features in .cargo/config does not work for cfg statements in Cargo.toml

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/cargo#6858]
Originally reported in RustCrypto/stream-ciphers#11

Create a project with following files. Cargo.toml:
```toml
[target.'cfg(target_feature="aes")'.dependencies]
either = "*"
```

.cargo/config:
```toml
[target.'cfg(any(windows, unix))']
rustflags = ["-Ctarget-feature=+aes"]
```

src/main.rs:
```rust
#[cfg(target_feature="aes")]
fn main() { println!("aes enabled"); }

#[cfg(not(target_feature="aes"))]
fn main() { println!("aes disabled"); }
```

Running `cargo run` outputs "aes disabled" as expected, but `either` crate does not get downloaded, i.e. `cfg` statement in `Cargo.toml` does not work as expected. And as a consequence adding `#[cfg(target_feature="aes")] extern crate either;` to `main.rs` results in a compilation error. Meanwhile `RUSTFLAGS="-C target-feature=+aes" cargo run` works as expected without any issues.

**Comment by ehuss** [comment]
This is an interesting problem.  There's a circular requirement where to determine the cfg flags it needs to know the cfg flags.  Cargo currently starts with an empty set (see [TargetInfo](https://github.com/rust-lang/cargo/blob/6f399162db3d64dc841b3b7da73708f5b043eae7/src/cargo/core/compiler/build_context/target_info.rs#L67)) and runs `rustc` to determine the starting cfg set.  To handle this situation, it would need to repeatedly call `rustc` to build up the cfg rules until it stabilizes.  My instinct is that is not practical, or at least would be complex or slow.  However, I can't think of any other way around it (other than, as you mention, using the `RUSTFLAGS` env var, and enabling that using some external script or tool).

**Comment by posix4e** [comment]
Any updates?

**Comment by d-e-s-o** [comment]
The same issue seems to affect `cfg(debug_assertions)`. Debugging this kind of stuff can be a huge time sink. At the very least we should be printing a warning, in my opinion.

**Comment by Systemcluster** [comment]
This should be strongly noted in the [documentation](https://doc.rust-lang.org/cargo/reference/config.html#target).

It notes `Do not try to match on debug_assertions or Cargo features like feature="foo"`, but from @ehuss's comment "Cargo currently starts with an empty set" I understand that `cfg` directives in `.cargo/config` don't work at all.

I spend around a day trying to set `-Ctarget-feature` and `-Ctarget-cpu` based on `cfg` targets in `.cargo/config`, and it took me quite a bit to find this issue.

> Running `cargo run` outputs "aes disabled" as expected

I don't think this is expected at all. With a config like

```toml
[target.'cfg(any(windows, unix))']
rustflags = ["-Ctarget-feature=+aes"]
```

I would expect the `aes` feature to be enabled for all windows and unix targets, and as currently documented this is very non-intuitive. In fact, the documentation even lists it as an example, which is very misleading in light of this issue and #10439:

```toml
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "my-arm-wrapper"
rustflags = ["…", "…"]
```
