### ISSUE TITLE
Cargo compiling git/path dependencies unconditionally with all features

### ISSUE THREAD

**Issue by tangmi** [rust-lang/cargo#6870]
**Problem**
Cargo is attempting to build dependencies with features that should not be enabled current the current build configuration. This only seems to happen for git and path dependencies.

Edit: is this intended behavior? Is it related to https://github.com/rust-lang/cargo/issues/4847? If so, is there a way around this? I'm currently developing against a forked version of a published crate while waiting for PRs.

**Steps**
If I have a dependency which is implemented as:

*dep_fail:*
```rust
#[cfg(feature = "fail_to_compile")]
compile_error!("Should only fail when fail_to_compile");
```

And a project that depends on `dep_fail` with a set of features conditional on the `target_os`:

*main's Cargo.toml:*
```toml
[package]
name = "main"
# ...

[target.'cfg(not(target_os = "dummy_target_os"))'.dependencies]
dep_fail = { path = "../dep_fail" }

[target.'cfg(target_os = "dummy_target_os")'.dependencies]
dep_fail = { path = "../dep_fail", features = ["fail_to_compile"] }
```

Then running `cargo build` even when `not(target_os = "dummy_target_os")` shows the compilation error in `dep_fail`.

**Possible Solution(s)**

**Notes**

Output of `cargo version`: `cargo 1.34.0 (6789d8a0a 2019-04-01)`
Rust version: `rustc 1.34.0 (91856ed52 2019-04-10)`
OS: Windows 10, macOS 10.14.2
Release channel: stable, nightly

Thanks for your time!
