### ISSUE TITLE
Provide custom LLVM passes on cargo's profile

### ISSUE THREAD

**Issue by grsouza** [rust-lang/cargo#7001]
Hi everyone, when using rustc, I'm able to provide a list of LLVM passes like this:

```bash
rustc main.rs -C passes="basicaa simplifycfg tailcallelim"
```

I wonder if this is possible using cargo, maybe something like this:

```toml
[profile.release]
passes = ["basicaa", "simplifycfg", "tailcallelim"]
```
I wasn't able find this information in the docs, Is it possible to accomplish this in someway?

Thanks.
