### ISSUE TITLE
Support multiline dependency declaration

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/cargo#7012]
Hello Rust developers,

**Describe the problem you are trying to solve**

Currently Cargo 1.35.0 does not support multiline dependency declaration like this one:

```toml
[dependencies]
some = {
    git="https://here-it-goes-a-very-long-uniform-resource-locator-or-url.com/and-the-path-is-long-too",
    tag = "0.1.0", 
    optional = true
}
```

**Describe the solution you'd like**

As in the example, if the URL is long, I wish that I could break the `{}` down to multiple lines. That would help a lot. Unfortunately, it's impossible for now.

**Notes**

It would be nice if you also add support for last trailing comma (before `}`), like in Rust source code.

Thank you,

**Comment by sfackler** [comment]
This should probably be filed on the TOML specification itself: https://github.com/toml-lang/toml.

**Comment by hkcorac** [comment]
Thank you I understand. I'm closing this issue.

**Comment by ehuss** [comment]
Also, it is common in these situations to use a dotted table name like this:

```toml
[dependencies.some]
git = "https://here-it-goes-a-very-long-uniform-resource-locator-or-url.com/and-the-path-is-long-too"
tag = "0.1.0"
optional = true
```
