### ISSUE TITLE
Support for vendoring on a single platform

### ISSUE THREAD

**Issue by nipunn1313** [rust-lang/cargo#7058]
See https://github.com/alexcrichton/cargo-vendor/issues/70

Would be nice to be able to vendor on linux without pulling in windows-specific dependencies.
This would still be something we would use.

**Comment by kvark** [comment]
@alexcrichton this is actually hurting us a bit with Gecko as well. I'm trying to vendor https://github.com/grovesNL/spirv_cross which has a wasm-specific dependency:
```toml
[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2.33"
js-sys = "0.3.10"
```

The difference with the original issue is that we'd need a set of targets to filter on - the set Gecko needs to be building for.
