### ISSUE TITLE
Feature: configuration aliases

### ISSUE THREAD

**Issue by kvark** [rust-lang/cargo#7260]
**Describe the problem you are trying to solve**

As seen in https://github.com/gfx-rs/wgpu/pull/290#issuecomment-522221886, `cfg` parameters can be quite long:
```toml
[target.'cfg(all(target_os = "windows", not(target_arch = "wasm32")))'.dependencies]
gfx-backend-dx12 = { version = "0.3", optional = true }

[target.'cfg(all(any(target_os = "windows", all(unix, not(any(target_os = "macos", target_os = "ios")))), not(target_arch = "wasm32")))'.dependencies]
gfx-backend-vulkan = { version = "0.3", optional = true }

[target.'cfg(any(all(target_os = "macos", not(target_arch = "wasm32"), all(target_arch = "aarch64", target_os = "ios"))))'.dependencies]
gfx-backend-metal = { version = "0.3", optional = true }
```

If such a dependency is not optional, using it has to be guarded by a similar `cfg` statement in the code:
```rust
#[cfg(any(all(target_os = "macos", not(target_arch = "wasm32"), all(target_arch = "aarch64", target_os = "ios"))))]
gfx_backend_metal::Instance::create("", 1);
```

**Describe the solution you'd like**

It is very inconvenient and error prone. It would be great if instead we could define a set of configurations to be used across Cargo config as well as the code. Something like this:
```toml
[configurations]
"metal" = 'any(all(target_os = "macos", not(target_arch = "wasm32"), all(target_arch = "aarch64", target_os = "ios")))'

[target.cfg("metal").dependencies]
gfx_backend_metal = "0.3"
```
And then in Rust code:
```rust
#[cfg("metal")]
gfx_backend_metal::Instance::create("", 1);
```

**Notes**

Interestingly, configuration aliases are already there, just hard-coded to just "windows" and  "unix": https://doc.rust-lang.org/reference/conditional-compilation.html#unix-and-windows

This issue can be seen as making this more generic.
