### ISSUE TITLE
No way to run #[test]s in benchmarks

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#727]
E.g. 

```rust
// benches/test.rs
#[test]
fn foo() { fail!() }
```

`cargo bench` will (sensibly) always pass `--bench` to the test harness and so does not run that test, and `cargo test` will ignore the file totally, even if the following is added to `Cargo.toml`:
```toml
[[bench]]
name = "test"
test = true
```
