### ISSUE TITLE
Allow non-master branch for alternative registry index to facilitate development and testing

### ISSUE THREAD

**Issue by snawaz** [rust-lang/cargo#7329]
Now that Cargo alternative registries have been stabilized, they are configured as:
```toml
[registries]
my-registry = { index = "https://my-intranet:8080/git/index" }
```
Currently, Cargo uses the `master` branch by default, which makes development & testing difficult as it interferes with the master which is used in the production. So it'd be good if Cargo allows us to use `non-master` branch as well:
```toml
[registries]
my-registry = { index = "https://my-intranet:8080/git/index",  branch = "dev" }
```
where `branch` could be an optional field whose default value is `master` to be backward-compatible.
