### ISSUE TITLE
Wish to use SVN dependency

### ISSUE THREAD

**Issue by k06a** [rust-lang/cargo#7343]
**Describe the problem you are trying to solve**

I wish to include `git` subdirectories, but at least `svn` support will help, sice GitHub supports `svn`: https://help.github.com/en/articles/support-for-subversion-clients

**Describe the solution you'd like**
```
[dependencies]
common-types = { svn = "https://github.com/paritytech/parity-ethereum/trunk/ethcore/types" }
```

**Comment by sfackler** [comment]
Cargo will automatically search through the directories of a git repository to find the crate you requested. This will already work:

```toml
[dependencies]
common-types = { git = "https://github.com/paritytech/parity-ethereum" }
```
