### ISSUE TITLE
Build, but do not link dynamic libraries

### ISSUE THREAD

**Issue by idubrov** [rust-lang/cargo#7517]
**Describe the problem you are trying to solve**

I have a `main` binary and set of `cdylib` plugins. I want `cdylib` plugins to be built every time (as necessary, after doing all up-to-date checks) I run `main` binary, but without doing any linking.

**Describe the solution you'd like**

Basically, I want to have a dependency like:

```toml
[???-dependencies]
my-nice-plugin = { path = "../plugin" }
```

So every time I do `cargo run --package main`, `cargo` will also implicitly do `cargo build --package my-nice-plugin` to produce a loadable library.
