### ISSUE TITLE
Reexporting features implicitly enables optional dependency

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/cargo#7521]
**Problem**

`cargo check --features foo` implicitly enables optional dependency `bar` given this manifest:

```toml
[features]
foo = ["bar/foo"]

[dependencies]
bar = { version = "0.1", path = "bar", optional = true }
```

The behaviour I would expect is `bar` not being enabled unless it's also specified in the `--features`.

If feature `foo` did in fact depend on `bar`, that could be specified like `foo = ["bar", "bar/foo"]`.

**Notes**

Output of `cargo version`:

cargo 1.40.0-nightly (a429e8cc4 2019-10-04)
