### ISSUE TITLE
Hook for any successful build

### ISSUE THREAD

**Issue by vhbit** [rust-lang/cargo#756]
It would be great to have a way to invoke an external command on successful build of crate or any dependency with at least the following info:
- target
- crate name 
- source dir
- dest dir
- lib file (if not `lib.rs`)

For example, if I have the following manifest:

``` toml
[package]
name = "foo"
on_build_success = "update_src_indexes.sh"

[dependencies.bar]
git="https://github.com/foo/bar"

[dependencies.baz]
git="https://github.com/foo/baz" 
```

On the first build when everything builds, that external tool will be called with:
- target=`x86_64-apple-darwin`, name=`bar`, source=`~/.cargo/path_to_bar`, dest=`./target/path_to_bar_lib`
- target=`x86_64-apple-darwin`, name=`baz`, source=`~/.cargo/path_to_baz`, dest=`./target/path_to_baz_lib`
- target=`x86_64-apple-darwin`, name=`foo`, source=`.`, dest=`./target/path_to_baz_lib`

The idea is that after any rebuild to be able to do some external processing like indexing sources.
