### ISSUE TITLE
infinite recursion when a package depends on itself

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#77]
``` toml
[package]

name = "test"
version = "0.0.0"
authors = []

[dependencies.test]

path = "."

[[lib]]

name = "test"
```

with `src/test.rs`:

```
task '<main>' has overflowed its stack
```

(This fails with a nonrelative path too.)
