### ISSUE TITLE
 multi-package dependency management

### ISSUE THREAD

**Issue by silence-code** [rust-lang/cargo#7805]
cargo should support multi-package dependency management, just like the <dependencyManagement> tag provided by maven

**Comment by silence-code** [comment]
cargo should support multi-package dependency management, just like the 'dependencyManagement'  tag provided by maven

**Comment by ehuss** [comment]
Unfortunately I'm not too familiar with Maven.  From what I understand, `dependencyManagement` provides a way to force a version when a transitive dependency does not specify a version, is that correct?  Can you include more information about your use case, and what it would do?

Generally using `*` versions in Cargo is to be avoided (crates.io doesn't allow publishing with it).  Also, there are mechanisms like `[patch]` to change the versions selected.  There's also #5471 which would provide a way to set some default dependencies in a workspace, which is kinda similar.

**Comment by ehuss** [comment]
Without more information, I'm going to close this.  If you have a more detailed proposal, feel free to leave a comment.

**Comment by mknet** [comment]
The idea of the `dependencyManagement` in Maven is do define a specific version of a dependency at a central place of a multi package/module project. An idea could be to provide the versions of the dependency in the Cargo.toml / [Virtual Manifest](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-manifest) and just add the name of the crate to the sub Cargo.toml.

For instance:

**Cargo.toml**
```toml
[workspace]

members = [
    "a",
    "b"
]

[dependencies.diesel]
version = "1.4.4"
```

**a/Cargo.toml**
```toml
[package]
name = "a"

[dependencies]
diesel = "something to mark that we want to use the version defined in the super Cargo.toml"
```
