### ISSUE TITLE
Cargo fails to build/run build script when `package.metadata.docs.rs` manifest field is present

### ISSUE THREAD

**Issue by joshlf** [rust-lang/cargo#7868]
**Problem**
When building the [Mundane](https://github.com/google/mundane) library, the build script seems not to be built or run, which causes linking to fail since it expects symbols provided by object files that are produced by the build script.

**Steps**
1. Check out [this commit](https://github.com/google/mundane/commit/75e11d547f10a5ba1e952cc2a586c8a66177e6bb)
2. Run `cargo test -v`, observing that the build script is never built

By contrast, if we remove the following lines from the `Cargo.toml` file and try the steps above, they succeed:

```toml
[package.metadata.docs.rs]
features = ["bytes","insecure","kdf","rsa-pkcs1v15"]
```

**Notes**

Output of `cargo version`: `cargo 1.42.0-nightly (9d32b7b01 2020-01-26)`
Platform: macOS

**Comment by ehuss** [comment]
There is an issue with the way the `Cargo.toml` is written.

```toml
[package.metadata.docs.rs]
features = ["bytes","insecure","kdf","rsa-pkcs1v15"]

# Exclude these test files in order to get under the minimum crates.io crate
# file size.
exclude = [
    "boringssl/boringssl/fuzz/*",
    "boringssl/boringssl/third_party/wycheproof_testvectors/*",
    "boringssl/boringssl/crypto/fipsmodule/*/*_tests.txt",
    "boringssl/boringssl/crypto/cipher_extra/test/*"
]

build = "build/main.rs"
```

The `build` and `exclude` fields are part of the `package.metadata.docs.rs` table, which is ignored by Cargo.  You want to move those two keys above the metadata table so they are part of the `[package]` table.

**Comment by joshlf** [comment]
Ah, perfect, thanks! Would it also be valid to do the following?

```toml
[package]
# ... 
metadata.docs.rs.features = ["bytes","insecure","kdf","rsa-pkcs1v15"]
```
