### ISSUE TITLE
What speed gain am I changing if I optimize for size instead of speed?

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/cargo#8031]
I read https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level.

What I don't understand is which speed gain I'm changing if I use:

```toml
[profile.release]
opt-level = "z"
```

instead of:

```toml
[profile.release]
opt-level = 3
```

- Is it right that today `opt-level = 3` is the best setting (for `opt-level` section) for runtime speed?

- If I instead use `opt-level = "z"` I'm decreasing runtime performance, right?

I'm not interested in building/compiling speed.
