### ISSUE TITLE
Allow cfg's in workspaces

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/cargo#8045]
**Describe the problem you are trying to solve**
Cargo should allow wider support for `cfg`s in the Cargo.toml
For example, I have a workspace member `b` which I only want to compile for the windows platform, and my intuition tells me that this should work
```toml
[target.'cfg(windows)'.workspace]
exclude = ["crates/b"]
```
However, cargo ignores the cfg in this position, forcing me to manually comment out the `exclude` in order to compile for other platforms
