### ISSUE TITLE
cargo-tree: Panic with `-Zfeatures` and "all" targets

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#8109]
A manifest with:

```toml
[target.'cfg(windows)'.dependencies]
log = {version="*", features=["serde"]}
```

Running `cargo tree --target=all -Zfeatures=all` panics with:

```
thread 'main' panicked at 'features did not find PackageId { name: "log", version: "0.4.8", source: "registry `https://github.com/rust-lang/crates.io-index`" } false', src/cargo/core/resolver/features.rs:231:17
```

The problem is that the `FeatureResolver` needs to be taught what "all" means.
