### ISSUE TITLE
-l flag should not be passed while compiling examples

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#814]
If you have for example this:

``` toml
[package]
# ...
build = "build.rs"

[[example]]
path = "example.rs"

[lib]
path = "lib.rs"
```

If `build.rs` prints `-l foo:static`, the `-l` flag is being passed when compiling both the library and the example.
Since the example also links to the library, you get "multiple definition" errors for the symbols in `libfoo`.
