### ISSUE TITLE
Cargo publish fails to find build.rs in custom path

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/cargo#8280]
**Problem**

`cargo publish` fails to find a build.rs in the custom path even when other commands like `cargo build` succeeds.

**Steps**

1. `git clone https://github.com/rust-lang/rustfmt && cd rustfmt`
2. `cargo make build` succeeds
3. `cargo make publish` fails (this step requires a publish permission for rustfmt, so it is unlikely to be 
 reproducible)

I have tried to create a minimal working example for this issue, though it hasn't been reproducible outside of the rustfmt repository.

**Notes**

rustfmt uses a weird project structure as it needs to be registered as a submodule of the rustc repository. That may be the problem.

Output of `cargo version`: `cargo 1.45.0-nightly (500b2bd01 2020-05-18)`

Content of Cargo.toml:
```toml
[package]

name = "rustfmt-nightly"
version = "2.0.0-rc.2"
authors = ["Nicholas Cameron <ncameron@mozilla.com>", "The Rustfmt developers"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/rust-lang/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "rustfmt-core/rustfmt-bin/build.rs"
categories = ["development-tools"]
edition = "2018"

[[bin]]
name = "rustfmt"
path = "rustfmt-core/rustfmt-bin/src/bin/main.rs"
test = false

[[bin]]
name = "cargo-fmt"
path = "rustfmt-core/rustfmt-bin/src/cargo-fmt/main.rs"
test = false

[[bin]]
name = "rustfmt-format-diff"
path = "rustfmt-core/rustfmt-bin/src/format-diff/main.rs"
test = false

[[bin]]
name = "git-rustfmt"
path = "rustfmt-core/rustfmt-bin/src/git-rustfmt/main.rs"
test = false

[features]
default = ["cargo-fmt", "rustfmt-format-diff"]
cargo-fmt = ["cargo_metadata"]
rustfmt-format-diff = ["regex", "serde", "serde_json"]
generic-simd = ["rustfmt_lib/generic-simd"]

[dependencies]
anyhow = "1.0"
dunce = "1.0"
env_logger = "0.7"
log = "0.4"
structopt = "0.3"
term = "0.6"
thiserror = "1.0"

cargo_metadata = { version = "0.9", optional = true }
regex = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

rustfmt_lib = { path = "rustfmt-core/rustfmt-lib", version = "2.0.0-rc.2" }

[dev-dependencies]
lazy_static = "1.0"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"
```
