### ISSUE TITLE
Build script failure hidden by dependency build failure 

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#835]
``` toml
# a/Cargo.toml
[package]

name = "a"
version = "0.0.1"
authors = []
build = "build.rs"

[dependencies.b]
path = "../b"
```

``` rust
// a/build.rs
fn main() { std::os::set_exit_status(1) }
```

``` toml
# b/Cargo.toml
[package]

name = "b"
version = "0.0.1"
authors = []
```

``` rust
// b/src/lib.rs
invalid
```

Then in `a`:

```
cargo clean && cargo build 
   Compiling a v0.0.1 (file:///home/huon/projects/test-rust/tmp/a)
   Compiling b v0.0.1 (file:///home/huon/projects/test-rust/tmp/a)
/home/huon/projects/test-rust/tmp/b/src/lib.rs:1:1: 1:8 error: expected item, found `invalid`
/home/huon/projects/test-rust/tmp/b/src/lib.rs:1 invalid
                                                 ^~~~~~~
Build failed, waiting for other jobs to finish...
Could not compile `b`.
```

The user is probably certainly more interested in the build script failing to build/run than the dependency. @alexcrichton's suggested resolution of https://github.com/rust-lang/cargo/issues/832 would possibly resolve this automatically too.
