### ISSUE TITLE
Add `--deny-warnings` functionality for all commands.

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/cargo#8424]
**Describe the problem you are trying to solve**

I often automate `cargo` and I typically want any automation to halt when `cargo` emits warnings. AFAICT the only way to do this is to try to parse the output for the way warnings are typically produced.

(Related issue: there are two categories of warnings which is confusing and needs clarification, which I filed as #8423 .)

**Describe the solution you'd like**

Add a commandline flag called `--deny-warnings` and if set, if a warning is encountered, this ensures the process will exit with a non-zero status *and* that no "non-dry-run" operations proceed. For example, with `cargo publish --deny-warnings` any of the early local packaging-style lint warnings will cause `cargo publish` to avoid making any requests to
crates.io.

**Notes**

I'm not sure about the option name `--deny-warnings` which I took from the `#![deny(warnings)]` rust compilation attribute, but I can't think of anything clearer and concise. `--treat-warnings-like-errors`, `--exit-with-error-when-encountering-warnings`, `--don't-just-warn-me-stop-me!`, and `--please-save-me-from-myself` all are too cumbersome.

**Related Tickets**

This is related to #3591 because in some way these are opposites (disabling warnings versus escalating them to errors). There *might* be some common CLI magic that addresses both issues and is clear enough to users.

Even if they use separate cli and/or config specification, if both implemented, they might lead to nonsensical / confusing combinations which a good UX would complain-and-exit about, for example: `cargo do-stuff --hide-warnings --deny-warnings` or something similar should probably say "I can't tell what you meant to do."

**Comment by jrvanwhy** [comment]
Commenting to support this feature request.

The project I work on has `-D warnings` in its `.cargo/config`:

```toml
[target.'cfg(all())']
rustflags = ["-D", "warnings"]
```

This works great for CI, where it prevents us from merging code that has warnings. However, it is painful for local development. I frequently add a few lines, run `cargo check`, and get errors related to unused variables. I prepend `_` to variable names and remove it *extremely* frequently, which is a waste of time.

Adding a `--deny-warnings` flag to cargo would allow us to use `--deny-warnings` in our CI infrastructure to block on warnings but still allow iterative code development to proceed without the unnecessary toil caused by `-D warnings`.

**Comment by CPerezz** [comment]
You can already do this in your CI. It's just about setting your ENV variable `RUSTFLAGS= -D warnings` and run cargo. 

Cargo will fetch the ENV variables and pass them to `rustc` so that the warnings get denied without needing to add any extra stuff. 

This would be an example using [actions-rs](https://github.com/actions-rs/cargo)
```yml
on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
```

If you want to treat warnings as errors, or do any fancy stuff, check the docs about lint levels for `rustc`: https://doc.rust-lang.org/rustc/lints/levels.html

I think this issue can be closed considering that `--deny-warnings` is already something that can be achieved setting up rustflags.
