### ISSUE TITLE
perhaps two different versions of crate? how to use private git repository in cargo ? 

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/cargo#8536]
In my project,I just define some common struct in `hula_common` git private repository.
* `A` project use this repository like this in cargo dependencies:

```bash
hula_common  = { package = "hula_common", git   = "ssh://git@git.baoyachi.com/hula/hula_common.git" , tag = "0.1.5" }
```
* `B` project use this repository like this in cargo dependencies:

```bash
hula_common  = { package = "hula_common", git   = "ssh://git@git.baoyachi.com/hula/hula_common.git" , tag = "0.1.4" }
```

* `A`,`B`project use difference tag, then compile `A`,`B` and `hula_common` ,then complie error. 

```bash
error[E0308]: mismatched types
   --> src/common/query.rs:196:23
    |
196 |         let items = self.query(pos, key)?;
    |                                ^^^^^ expected struct `hula_common::query::Container`, found struct `hula_common::query::Container`
    |
    = note: expected reference `&hula_common::query::Container`
               found reference `&hula_common::query::Container`
    = note: perhaps two different versions of crate `hula_common` are being used?
```

I just update `hula_common` tag with `0.1.5`  that `A` repository needed. But `B`repository not need `0.1.5` feature code.
I think B repository keep `hula_common` version with `0.1.4`. 

why complie error with `note: perhaps two different versions of crate `hula_common` are being used?`

I don't why complie error? **Am I using it wrong** ?

**Comment by baoyachi** [comment]
but when I use go.mod ,A,B project use different tag ,also compile success.

The same question, Why does Rust compile error.

 What's difference ?

**Comment by Eh2406** [comment]
Cargo has no way of knowing that two different tags point to compatible projects.  If you want a shared dependency on a git project it has to be the same commit to be compatible. Cargo will happily build both tags into the same project, but it will not treat types from one as the same as types from the other.

**Comment by baoyachi** [comment]
but I update `hula_common` project just with `A`project used. B project not need latest code . why does `B` project force update?

If `hula_common` project be used other 10 module project .When I update `hula_common` new version, other 10 module project must force update?

It's too difficult

**Comment by baoyachi** [comment]
When our use [https://crates.io/](https://crates.io/) `crates` repository。 The problems described above may not occured.

But,in the company, the use of a large number of private repository be used with cargo dependencies, this problem often occurs, It's very headache.

**Comment by baoyachi** [comment]
The Cargo.toml profile like this:
```toml
...
[dependencies]
serde_derive = "1.0.111"
serde = "1.0.111"
serde_json = "1.0.53"
...

hula_common = { package = "hula_common", git = "ssh://git@git.baoyachi.com/hula/hula_common.git" , tag = "0.1.5" }
B = { package = "B", git = "ssh://git@git.baoyachi.com/hula/B.git" , tag = "0.3.2" }
A = { package = "A", git = "ssh://git@git.baoyachi.com/hula/A.git" , tag = "0.5.7" }
...


```
