### ISSUE TITLE
Feature request, Get all features with Cargo.toml

### ISSUE THREAD

**Issue by flipchan** [rust-lang/cargo#8676]
**Describe the problem you are trying to solve**
So when defining what features you want in Cargo.toml, you define features, example:

```toml
[dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
serde_json = "*"

```

**Describe the solution you'd like**
It would be nice if there would be some enumerate function, that lists all the avaliable functions so that a user 
can request all the features with a syntax like features = ["all"] or features = ["*"]  or something similar

**Notes**
Maybe there already is some kind of feature for this?? if so let me know

Thanks!
