### ISSUE TITLE
Support different environment variables for different target architectures in cargo configuration

### ISSUE THREAD

**Issue by capnfabs** [rust-lang/cargo#8801]
**Describe the problem you are trying to solve**

Cross-compiling code with dependencies on native libraries is often complex because:

- it's not always possible / desirable to install the required `.so`s and header files using the same system that the host architecture uses, because dependency packages and build tools aren't always capable of supporting multiple architectures. A common solution on Linux is to install target packages under a different root, e.g. create a `/target-sysroot/` with parts of a distribution underneath, installed with something like [debootstrap](https://wiki.debian.org/Debootstrap).
- Many native build tools (e.g. `gcc`, `pkg-config`) are used by `build.rs` scripts, and configured by environment variable, which works well when they're only used in the context of building for a single platform, but doesn't when they can only be set once for multiple targets. It's not uncommon for e.g. `gcc` to be invoked both for the host and target architecture as part of the build for a single large application.
- It's currently possible to resolve this manually using [`links` build script config overrides](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinks), but this is often significantly more work than simply configuring environment variables and running `cargo build`.

**Describe the solution you'd like**

I'm wondering if it'd be worth adding configuration cargo for configuring environment variables on a per-architecture basis?

It's currently possible to do this in `.cargo/config.toml` to specify `rustc` args for other platforms:

```toml
[target.armv7-unknown-linux-gnueabihf]
rustflags=["arm", "specific", "flags"]
```

I'd love to be able to add an additional mapping of environment variables that are applied to subcommands issued by build scripts for these architectures. e.g., for my specific configuration with a target system mounted under `/target-sysroot/`, this would look like:

```toml
[target.armv7-unknown-linux-gnueabihf]
rustflags=["arm", "specific", "flags"]
buildenv={C_INCLUDE_DIR="/target-sysroot/usr/include/arm-linux-gnueabihf", PKG_CONFIG_LIBDIR="/target-sysroot/usr/lib/arm-linux-gnueabihf/pkgconfig", PKG_CONFIG_SYSROOT_DIR="/target-sysroot/"}
```

or alternatively, without inlining the `buildenv` variable:

```toml
[target.armv7-unknown-linux-gnueabihf]
rustflags=["arm", "specific", "flags"]
[target.armv7-unknown-linux-gnueabihf.buildenv]
C_INCLUDE_DIR="/target-sysroot/usr/include/arm-linux-gnueabihf"
PKG_CONFIG_LIBDIR="/target-sysroot/usr/lib/arm-linux-gnueabihf/pkgconfig"
PKG_CONFIG_SYSROOT_DIR="/target-sysroot/"
```

This mirrors the syntax for `[target.<triple>.<links>.rustc-env]` as per the [cargo reference](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinks).

**Notes**

This is a problem I ran into concretely when attempting to cross-compile [spotifyd](https://github.com/Spotifyd/spotifyd) for the Raspberry Pi 3. The Host OS in this case was [this image from the rust-embedded team](https://github.com/rust-embedded/cross/blob/master/docker/Dockerfile.armv7-unknown-linux-gnueabihf), and the target OS was a subset of Raspbian Buster installed using [Multistrap](https://wiki.debian.org/Multistrap).

I'm not _super_ experienced with linux build systems in general, and so I'm not sure if this is the "right" way to solve the problem! But it felt relatively expedient and clean to me. Definitely open to feedback and ideas :)
