### ISSUE TITLE
dep-features can't reference dev-dependencies features

### ISSUE THREAD

**Issue by mankinskin** [rust-lang/cargo#9060]
Say we have:
- app depends on awesome
- awesome dev-depends on cookie

activating a feature in the dev-dependency through a feature in awesome does not work:
```toml
# cookie/Cargo.toml
[features]
session = []
```
```toml
# awesome/Cargo.toml
[features]
session = ["cookie/session"]

[dev-dependencies.cookie]
path = "../cookie"
```
```toml
# app/Cargo.toml
[dependencies.awesome]
path = "../awesome"
features = ["session"]
```
The error message is this:
```sh
error: failed to select a version for `awesome`.
    ... required by package `app v0.1.0 (/home/$USER/git/app)`
versions that meet the requirements `=0.1.0` are: 0.1.0

the package `app` depends on `awesome`, with features: `cookie` but `awesome` does not have these features.


failed to select a version for `awesome` which could resolve this conflict
```

**Notes**

Output of `cargo version`: `cargo 1.49.0-nightly (2af662e22 2020-11-12)`

**Comment by mankinskin** [comment]
#5139

**Comment by hvenev** [comment]
dev-dependencies only exist when building the crate that defines them, right? When building `app` the `awesome` crate does not have any dependency named `cookie`, not even an optional one.

**Comment by mankinskin** [comment]
Oh, that explains this. But then I can't use features of crates which conditionally enable features in their dev-dependencies, right? In this case, `awesome` might want to run different tests using `cookie/session` when the feature `session` is enabled. But when `awesome/session` is set by a downstream crate, `cookie` is not a dependency and `cookie/session` can't be set, resulting in this error.

I don't know if this approach should be encouraged, maybe it would be better if `cargo test` would just test all features somehow. Maybe something like `dev-features` need a story? The purpose of this is obviously to test the `session` feature, which depends on a feature in a dev-dependency.

I think we should either
- ignore dev-dependencies in features when the crate itself is a dependency (or dev-dependency), allowing authors to configure dev-dependencies with features
- provide an alternative approach to testing different features and disallow dev-dependency features in the "exported" `features` section

**Comment by mankinskin** [comment]
Maybe the problem becomes more clear when `awesome/session` does actually change something for downstream crates aswell:
```toml
# cookie/Cargo.toml
[features]
session = []
```
```toml
# awesome/Cargo.toml
[features]
session = ["cookie/session", "tide"]

[dependencies.tide]
path = "../tide"

[dev-dependencies.cookie]
path = "../cookie"
```
```toml
# app/Cargo.toml
[dependencies.awesome]
path = "../awesome"
features = ["session"]
```
Now `awesome` behaves differently when `session` is enabled, and `cookie/session` is needed in the dev-dependencies to test this feature.

**Comment by Eh2406** [comment]
One workaround is for `awesome` to have two features `session = ["tide"]` for users to use, and `session-testing = ["cookie/session", "tide"]` for developers of `awesome` to use while testing.

**Comment by mankinskin** [comment]
This bug is now blocking me, because I need to enable a feature of a dependency which depends on my crate itself. This means I can only use dev-dependencies, because otherwise it would be a dependency cycle. But the features don't work correctly for dev-dependencies.

```toml
# riker
[features]
default = []
tokio_executor = ["riker-macros/tokio_executor"]

[dependencies]
riker-macros = { path = "riker-macros" }
```
# riker/riker-macros
[features]
default = []
tokio_executor = ["riker/tokio_executor"]

[dev-dependencies]
riker = { path = ".." }
```
