### ISSUE TITLE
[target.'cfg(...)'.dependencies] is turning on features in configurations that don't match the cfg

### ISSUE THREAD

**Issue by willcrichton** [rust-lang/cargo#9143]
**Problem**

I have the following dependency tree. C3 depends on C2 and C1, and C2 depends on C1.

```
c3 v0.1.0 (/Users/will/Code/tmp/cargobug/c3)
├── c1 v0.1.0 (/Users/will/Code/tmp/cargobug/c1)
│   └── libz-sys v1.1.2
└── c2 v0.1.0 (/Users/will/Code/tmp/cargobug/c2)
    └── c1 v0.1.0 (/Users/will/Code/tmp/cargobug/c1) (*)
```

C1 has an optional feature to depend on `libz-sys`. From `c1/Cargo.toml`:

```toml
[features]
include_dep = ["libz-sys"]

[dependencies]
libz-sys = { version = "*", optional = true }
```

And C2 conditionally includes C1 as a dependency with this feature activated when not on the wasm32 arch. From `c2/Cargo.toml`:

```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
c1 = { path = "../c1", features = ["libz-sys"] }
```

The issue is that the `libz-sys` feature for C1 is turned on when building C3 for the wasm32 arch, even though it should be turned off:

```
$ cd c3
$ cargo build --target wasm32-unknown-unknown
   Compiling cc v1.0.66
   Compiling pkg-config v0.3.19
   Compiling libc v0.2.85
   Compiling c2 v0.1.0 (/Users/will/Code/tmp/cargobug/c2)
   Compiling libz-sys v1.1.2
The following warnings were emitted during compilation:

warning: error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
warning: 1 error generated.

error: failed to run custom build command for `libz-sys v1.1.2`
```

By contrast, both `c1` and `c2` individually build successfully on the wasm32 arch.

**Steps**

The context described above is contained in this zip:
[cargobug.zip](https://github.com/rust-lang/cargo/files/5934438/cargobug.zip)

You should be able to unzip it, then reproduce by running:

```
cd c3
cargo build --target wasm32-unknown-unknown
```

**Notes**

I'm running latest stable, cargo 1.49 on OS X.
