### ISSUE TITLE
Features are being enabled for the wrong target

### ISSUE THREAD

**Issue by xobs** [rust-lang/cargo#9147]
**Problem**
I have a package that depends on `log`. This package may be built in a `no_std` environment, or for a desktop environment. When conditionally including a dependency based on the target, Cargo appears to traverse the tree and enable all possible features even if intermediate packages are never used.

**Steps**

`Cargo.toml`:
```toml
[package]
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
name = "minifb-build-test"
version = "0.1.0"

[dependencies]
log = "0.4"

[target.'cfg(any(windows,unix))'.dependencies]
minifb = "0.19"
```

`src/main.rs`:
```rust
#![cfg_attr(target_os = "none", no_std)]
#![cfg_attr(target_os = "none", no_main)]

#[cfg(target_os = "none")]
use core::panic::PanicInfo;

#[cfg(target_os = "none")]
#[panic_handler]
fn handle_panic(_arg: &PanicInfo) -> ! {
    loop {}
}

#[cfg(target_os = "none")]
pub fn some_main() -> ! {
    loop {}
}

#[cfg(not(target_os = "none"))]
fn main() {
    println!("ALT: {:?}", minifb::MENU_KEY_ALT);
    loop {}
}
```

2. Compile natively: `cargo build`
3. Compile for embedded: `cargo build --target riscv32imac-unknown-none-elf`
4. Observe that removing the `minifb = "0.19"` line fixes things, even though it shouldn't be included for a non-Windows/Unix build
5. Observe that also removing `log = "0.4"` line fixes things, indicating that `minifb` isn't actually included.

**Notes**

I believe some package deep in the heirarchy is adding `features = ["std"]` to the `log` crate somewhere, but I can't actually tell because it doesn't show up in `Cargo.lock`, nor does it show up if I do `cargo tree --target riscv32imac-unknown-none-elf`.

Output of `cargo version`:

```
[11:01:55 PM] D:/Code/Xous/minifb-build-test> cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
[11:02:13 PM] D:/Code/Xous/minifb-build-test> cargo +nightly --version
cargo 1.51.0-nightly (c3abcfe8a 2021-01-25)
[11:02:17 PM] D:/Code/Xous/minifb-build-test>
```

**Comment by ehuss** [comment]
You may want to try the [new feature resolver](https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2) which will hit stable in 1.51.

**Comment by xobs** [comment]
Switching to `cargo 1.51.0-nightly (c3abcfe8a 2021-01-25)` and adding the following to my `Cargo.toml` does not solve the issue:

```toml
[target.'cfg(any(windows,unix))'.dependencies]
minifb = {version = "0.19", resolver = "2"}
```

Is this a bug in cargo, or is it a misunderstanding on my part of how dependencies work?
