### ISSUE TITLE
Target configuration for binaries

### ISSUE THREAD

**Issue by MichaelMcDonnell** [rust-lang/cargo#9208]
I would like to be able to specify different main files depending on the
operating system. I ran into this problem in `servo` where it was solved using
the `include_bytes` macro. Using the `include_bytes` macro is not great because
it breaks my IDE. I am not able to easily jump to the code. I also suspect
using macros adds a small compile time overhead.

Another use case could be something like BusyBox but where certain system
binaries are only needed on specific platforms. For example, something that
queries Linux settings would only be compiled for Linux.

The `Cargo.toml` file shows how I would like the feature to work:

```toml
[package]
name = "target-cfg-bin-example"
version = "0.1.0"
authors = ["Michael Mc Donnell <michael@mcdonnell.dk>"]
edition = "2018"
autobins = false

# Use the standard `main.rs` for all operating systems except Android.
[[target.'cfg(not(android))'.bin]]
name = "target-cfg-bin-example"
path = "src/main.rs"

# Use the `main_android.rs` main file on Android
[[target.'cfg(android)'.bin]]
name = "target-cfg-bin-example"
path = "src/main_android.rs"

[dependencies]
```

It currently results in the following error message:

```
error: failed to parse manifest at `/home/michael/src/target-cfg-bin-example/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

You can clone the example from MichaelMcDonnell/target-cfg-bin-example

**Comment by ehuss** [comment]
I think the usual solution here is to place the `cfg` expressions in `main.rs`.  For example:

```rust
cfg_if! {
    if #[cfg(target_os = "android")] {
        mod impl_android;
        use impl_android::*;
    } else {
        mod impl_default;
        use impl_default::*;
    }
}
```

Or some variant of that.  I'm not sure I follow the comment about using `include_bytes`, maybe you could explain that more or show an example?

I would maybe lean more towards having some kind of requirements specification for the binary definition instead of using something like the `[[target]]` array.  Cargo targets already have `required-features`, so maybe something more extensible could help.  I thought there was already an issue or RFC about this, but I can't find it.

Also, unfortunately the word `target` is overloaded and means two completely different things in this context.

**Comment by MichaelMcDonnell** [comment]
Thanks for the help @ehuss! I've updated the issue description. I will try to create an example to show what using the `cfg_if` macro in Servo would look like. I'm also working on the implementation itself.

I also tried searching for an existing issue but didn't find any. Do you know of anybody who might know how to find the issue or RFC?

**Comment by ithinuel** [comment]
Hi, I was looking for a solution to that with a slightly different use case.

Building a library targetting embedded devices. An example demonstrates the features using [linux-embedded-hal](https://crates.io/crates/linux-embedded-hal). This example cannot build for windows or macos so `cfg_if` the whole example to have an empty main as an alternative doesn't seem great. 

I was hoping that I could "disable" the example using something along:  
```toml
[[example]]
name = "demo"
required-features = ["use_std"]
target = 'cfg(target_os = "linux")'
```

Although If I ever come to add support for windows or mac, I don't necessarily need the name to be the same.
