### ISSUE TITLE
vendor only certain crates or only crates from certain sources

### ISSUE THREAD

**Issue by horacimacias** [rust-lang/cargo#9234]
**Describe the problem you are trying to solve**
I'm trying to use `cargo vendor` to easily share files/projects and be able to perform remote builds.
Some of my project dependencies are private (hosted in private git repos) while others are in public repositories, e.g. crates.io
Running `cargo vendor` downloads everything into `vendor` folder by default and produces something like the following config.toml
```toml
[source.crates-io]
replace-with = "vendored-sources"

[source."https://bitbucket.private_repo_name.git"]
git = "https://bitbucket.private_repo_name.git"
tag = "v0.0.205"
replace-with = "vendored-sources"

[source."https://bitbucket.private_repo_name2.git"]
git = "https://bitbucket.private_repo_name2.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```

From a working perspective this approach works, but is not great as the vendor folder becomes slower to synchronise and the remote server I'm sending files to can already access crates.io (but not https://bitbucket.private_repo_name.git or https://bitbucket.private_repo_name2.git which is why I'm vendoring)

**Describe the solution you'd like**
It would be great to tell `cargo vendor` what to vendor and ignore everything else, or tell it what not to vendor and vendor everything else.
The `vendor` directory would only contain specific crates (private in my case), and the config.toml would only have "source." entries for those vendores crates

**Notes**
I'd be happy to contribute if this feature sounds relevant and generic enough.
