### ISSUE TITLE
Conditional feature activation based on profiles does not work for cyclical dependency

### ISSUE THREAD

**Issue by DesmondWillowbrook** [rust-lang/cargo#9245]
**Problem**

```toml
[package]
name = "test-features"

[features]
add_two = []

[dev-dependencies]
test-features = { path = ".", features = ["add_two"] }
```
Does not behave as expected, as running the binary with `-no-default-features` and `--release` _still_ activates the feature. To be fair, as far as I know, there is no expected behavior (See: #3921).

**Steps**

1. Clone [this repository](https://github.com/DesmondWillowbrook/cargo-optional-features-for-testing-and-examples) containing a sample rust project 
2. `cargo run --no-default-features --release` prints both lines, even though the feature `two` is not supposed to be active.

**Possible Solution(s)**

- This was discussed and found in: #2911
- Has something to do with: #3921

**Notes**

Output of `cargo version`:
`cargo 1.50.0 (f04e7fab7 2021-02-04)`
