### ISSUE TITLE
Cargo fails to build in `release` mode when using a `cdylib` dependency in the build script

### ISSUE THREAD

**Issue by abizjak** [rust-lang/cargo#9261]
**Problem**

I have two minimal crates
```
tree
.
├── a
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
└── b
    ├── build.rs
    ├── Cargo.toml
    └── src
        └── lib.rs
```
Crate `b` depends on crate `a` both as a normal dependency and as a build dependency

```toml
# b/Cargo.toml
[package]
name = "b"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]

[dependencies.a]
path = "../a"

[build-dependencies.a]
path = "../a"
version = "0"

[lib]
name = "b"
crate-type = ["rlib"]
```
Crate `a` has `crate-type = ["rlib", "staticlib", "cdylib"]`.

Building crate `b` in `release` mode first gives warnings
```
The lib target `a` in package `a v0.1.0 (/w/a)` has the same output filename as the lib target `a` in package `a v0.1.0 (/w/a)`.
Colliding filename is: ./w/b/target/release/deps/liba.rlib
...
The lib target `a` in package `a v0.1.0 (/w/a)` has the same output filename as the lib target `a` in package `a v0.1.0 (/w/a)`.
Colliding filename is: /w/b/target/release/deps/liba.so
```
and ultimately fails with
```
   Compiling b v0.1.0 (/w/b)
error: failed to remove /w/b/target/release/deps/a.a.4sfnxvt0-cgu.0.rcgu.o: No such file or directory (os error 2)

error: failed to remove /w/b/target/release/deps/a.3tyntkk2asiebm6o.rcgu.o: No such file or directory (os error 2)
```
The failure does not happen when building in `dev` profile.

It doesn't matter what `src.rs` files are, and the `build.rs` file is minimal

```rust
// b/build.rs
fn main() {
    
}
```

```toml
#  a/Cargo.toml
[package]
name = "a"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]

[lib]
name = "a"
crate-type = ["rlib", "cdylib"]
```
I would expect
- the warnings to make sense. Currently it states "the lib target in `a` has the same name as the lib target in `a` which should not be controversial.
- the build to succeed. The `cdylib` should not affect whether the build succeeds or not.

**Steps**
1. Create a crate `a` with `crate-type` that includes `cdylib`
2. Create a crate `b` which depends on `a`, and which has a build script that depends on `a` as well.
3. Try to build `b` in release mode `cargo build --release`. This always leads to a warning, but sometimes it does not lead to an error, although most of the time it does.

**Possible Solution(s)**
I discovered that adding
```toml
[profile.release.build-override]
opt-level = 3
```
to `b`'s `Cargo.toml` fixes the issue. There are no more warnings nor build errors.

I don't know in detail how the build works, so I don't know whether that could be a general solution.

**Notes**

Output of `cargo version`:
```
cargo 1.48.0 (65cbdd2dc 2020-10-14)
```
The same failure happens with 1.47, but 1.46 works (all are stable versions).

With the latest nightly I tried `cargo 1.52.0-nightly (bf5a5d5e5 2021-02-18)` I always get warnings, but I do not get errors.

My OS is Ubuntu 20.04.
