### ISSUE TITLE
Lockfiles generated by nightly cause hard error on stable

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#9286]
The error is:

> [dependency] is specified twice in the lockfile

I believe this change is somewhat expected, which is why I haven't included more information (but can do if this is unexpected).

This is not really a big deal, but it would be nice if stable cargo understood enough to say why this happened / be able to convert the lockfile back to the old format, before making this the default behaviour on nightly.

**Comment by Eh2406** [comment]
This does seam unfortunate. We did not discuss a change knowing that it would have this bad an error message. I would appreciate tracking down witch change triggered this. If there is an easy way to reproduce, that would be helpful.

**Comment by Diggsey** [comment]
In my case it happened with the following crate graph:

- current crate
  - dependency: A
    - build dependency: C (via git with no branch)
  - dependency: B
    - build dependency: C (via git with branch=master)

On stable, there's a single entry in the lockfile for C.
On nightly, there are two entries for C with and without the `?branch=master` parameter.

**Comment by alexcrichton** [comment]
Are there any build warnings on stable? This was a known "breakage" but it is presumed that stable has been emitting warnings for a few months now, so projects without warnings should be able to transition.

**Comment by Diggsey** [comment]
I have seen this warning for other cases, but the warning did not show up for this specific case, possibly because they are build dependencies, or because they are not a direct dependency of the crate being compiled.

**Comment by alexcrichton** [comment]
Ok sounds like there was at least one bug in the warning emission code in that case. Are you able to fix your project to work on stable and nightly and the same time?

**Comment by Diggsey** [comment]
Yep, feel free to close this issue if there's no action :)

**Comment by alexcrichton** [comment]
Good to know! I mostly want to understand the impact of this insofar as how it may affect others too. It's good to know that your use case can still work, but we did not want to have breakage from rolling out this change so this is unfortunate either way.

Our options here at this point I think are:

* Carry on, hope that the breakage is minimal especially because projects can move to the updated lockfile on both stable and nightly
* Revert the new-lockfile-by-default changes, fix the bug about detection via build-dependencies (or wherever the bug might be), and wait another few months for that to percolate before trying to enable this again.

Personally I'd lean towards the former, but it's a function of how much breakage and surprise we see in the wild. One issue isn't enough to convince me personally, but that doesn't mean I can't be convinced! In any case I think this is good to leave open for awhile in case anyone else runs into the same error they can comment here as well.

**Comment by ehuss** [comment]
We discussed this a bit, and figured it would probably be good to issue a warning in this scenario, since it can be a bit surprising.

----

@Diggsey I was wondering if you could create a sample project or workspace that demonstrates where stable cargo doesn't issue a warning that this will break?  I tried versions 1.47 through 1.51, but wasn't able to find a way to make it not issue a warning.

I tried:
```toml
# foo/Cargo.toml
# …
[dependencies]
a = {path="a"}
b = {path="b"}
```

```toml
# a/Cargo.toml
# …
[build-dependencies]
bitflags = {git="https://github.com/bitflags/bitflags.git"}
```

```toml
# b/Cargo.toml
# …
[build-dependencies]
bitflags = {git="https://github.com/bitflags/bitflags.git", branch="master"}
```

and got the expected warning:

> warning: two git dependencies found for `https://github.com/bitflags/bitflags.git` where one uses `branch = "master"` and the other doesn't; this will break in a future version of Cargo, so please ensure the dependency forms are consistent

If not, that's OK, I don't think we'll make any changes here, but it would be good to know how the warning detection didn't fire.

**Comment by Diggsey** [comment]
Cool, it was a little tricky to reproduce as the issue originally occurred with quite a mess of private dependencies, but I've got it now:

```toml
# a/Cargo.toml
[dependencies]
b = { path = "../b" }

[build-dependencies]
bitflags = { git = "https://github.com/bitflags/bitflags.git", branch = "master" }
```

```toml
# b/Cargo.toml

[build-dependencies]
bitflags = { git = "https://github.com/bitflags/bitflags.git" }
```

```
> cd a

> cargo +nightly check
    Updating git repository `https://github.com/bitflags/bitflags.git`
    Checking b v0.1.0 (C:\Users\diggs\Projects\cargo-bug-repro\b)
    Checking a v0.1.0 (C:\Users\diggs\Projects\cargo-bug-repro\a)
    Finished dev [unoptimized + debuginfo] target(s) in 0.81s

> cargo +stable check
error: failed to parse lock file at: C:\Users\diggs\Projects\cargo-bug-repro\a\Cargo.lock

Caused by:
  package `bitflags` is specified twice in the lockfile
```
