### ISSUE TITLE
Duplicate `links` attribute check should not count unused optional dependencies

### ISSUE THREAD

**Issue by toyboot4e** [rust-lang/cargo#9324]
# Problem

`cargo build` fails if `Cargo.toml` has two different sys crates that link to the same C library:

```toml
[dependencies]
# they both link to `OurLibrary`
sys-crate-A = { version = "..", optional = true }
sys-crate-B = { version = "..", optional = true }
```

..even if one (or none) of them are used.

`cargo build` says as this:

```
the package `sys-crate-B` links to the native library `OurLibrary`, but it conflicts with a previous package which links to `sys-crate-A` as well:
```

# Possible Solution(s)

Unused optional crates should be excluded from the duplicate `links` attribute check. I guess.

# Notes

This [repository](https://github.com/toyboot4e/links-attr-test) contains concreate example and full error message. Thank you.
