### ISSUE TITLE
Precedence issue with `build-override` and `package."*"`

### ISSUE THREAD

**Issue by CryZe** [rust-lang/cargo#9351]
**Problem**
One of the most common situations where you may want to use `build-override` and `package."*"` is for when you write code that needs to both compile fast, but is too slow at runtime, such as a game. In those cases it makes sense to compile the dependencies with a higher optimization level and keeping the optimization of the game at `opt-level = 0`. You'd do this like so:

```toml
[dependencies]
serde = { version = "1.0.125", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 3

[profile.dev.build-override]
opt-level = 0
```

At least that's what everyone seems to be doing. Except when you actually try to compile this and examine the rustc invokations, you notice that `syn` gets compiled with `-C opt-level=3`, which not even a normal release build does by default. So in my case, the debug build currently takes quite a bit longer to build than the actual release build.

I don't think the current behavior makes any sense.

**Possible Solution(s)**
Swap the precedence such that `build-override` does not itself get overridden by `package."*"`.

**Notes**

Output of `cargo version`:

cargo 1.51.0 (43b129a20 2021-03-16)
