### ISSUE TITLE
cargo build --examples skips examples defined in Cargo.toml with required-features

### ISSUE THREAD

**Issue by chipsenkbeil** [rust-lang/cargo#9389]
**Problem**

I have a singular example located in `examples/user.rs` of the crate, which is part of a collective defined by a workspace list. I can verify that the example builds by using `cargo build --example user`; however, if I run `cargo build --examples` the example does not get built. I can verify this by adding nonsense to the singular example file - causing a compilation error - and have `cargo build --examples` pass while `cargo build --example user` fails.

Example repo: https://github.com/chipsenkbeil/cargo-examples-bug

**Steps**

Here's a minimal example of a Cargo.toml:

```toml
[package]
name = "cargo-examples-bug"
version = "0.1.0"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"
publish = false

[features]
my-feature = ["serde_json"]

[[example]]
name = "user"
required-features = ["my-feature", "serde/derive", "serde/rc"]

[dependencies]
serde = "1.0.117"
serde_json = { version = "1.0.61", optional = true }
```

And the associated example file in `examples/user.rs`:

```rust
fn main() {
    println!("Hello, world!");
}
```

1. Build the example with specific features via `cargo build --example user --features="my-feature serde/derive serde/rc"`
2. Attempt to build with examples and there is no complaint about providing features: `cargo build --examples`
3. Add something that will fail compilation in the `examples/user.rs` file
4. Verify that the build fails with `cargo build --example user --features="my-feature serde/derive serde/rc"`
5. Verify that the build does not fail (it never happens) with `cargo build --examples`

**Possible Solution(s)**

I'm not sure if this is expected, nor how you would handle passing different sets of required features to individual examples defined via `cargo build --examples`. This may be expected behavior, but I wasn't aware of this when building out a CI config around checking if examples build.

**Notes**

Platform: MacBook Air (M1, 2020)
Operating System: Mac 11.2.3

Output of `cargo version`: `cargo 1.51.0 (43b129a20 2021-03-16)`
Output of `rustc --version`: `rustc 1.51.0 (2fd73fabe 2021-03-23)`
Output of `rustup toolchain list`:

```
stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin
```

**Related**

Maybe https://github.com/rust-lang/cargo/issues/4663
