### ISSUE TITLE
Specify version of dependency once and platform specific features later

### ISSUE THREAD

**Issue by MarnixKuijs** [rust-lang/cargo#9510]
**Describe the problem you are trying to solve**

The new feature resolver is great for multi-platform work. The one small problem I'm currently facing is that you have to keep specifying dependency of the crate when you want to add some platform specific features:
```toml

[target.'cfg(target_os = "windows")'.dependencies]
foo = { version = "0.1", features = ["windows"] }

[target.'cfg(target_os = "unix")'.dependencies]
foo = { version = "0.1", features = ["unix"] }
```
Now with every version bump of the dependency I have to make sure all of the versions are bumped. Its not a difficult error to spot, because if there is a version mismatch you will get a compile error (even when not compiling for that specific platform). But it would nice if I could just specify the version once.

**Describe the solution you'd like**

A solution that might work is that cargo would understand the following, which as far as I understand, with the new feature resolver should be possible.

```toml

[dependencies.foo]
version = "0.1"

[target.'cfg(target_os = "windows")'.dependencies.foo]
features = ["windows"]

[target.'cfg(target_os = "unix")'.dependencies.foo]
features = ["unix"]

```

**Comment by weihanglo** [comment]
It is not possible in a Cargo package, but you can use [workspace inheritance](https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#the-dependencies-table) to achieve a similar result in a workspace.

```toml
[workspace.dependencies.foo]
version = "0.1"

[target.'cfg(target_os = "windows")'.dependencies.foo]
features = ["windows"]

[target.'cfg(target_os = "unix")'.dependencies.foo]
features = ["unix"]
```
