### ISSUE TITLE
`cargo tree -d` with `--target` can be confusing

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#9519]
**Problem**
`cargo tree -d` can show duplicates when used with the `--target` flag that, although the packages will be built twice, it is unavoidable when cross-compiling. This can be confusing because the output shows the same package twice with the same version, but no other explanation of why they are shown.

**Steps**
Create a manifest where a dependency shows up as both a normal dependency and a build-dependency (or proc-macro). Example:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.40"

[build-dependencies]
anyhow = "1.0.40"
```

Running `cargo tree -d --target x86_64-unknown-linux-gnu` will show:

```
anyhow v1.0.40
[build-dependencies]
└── foo v0.1.0 (/Users/eric/Temp/foo)

anyhow v1.0.40
└── foo v0.1.0 (/Users/eric/Temp/foo)
```

**Possible Solution(s)**
I can think of two possible solutions:

1. Don't treat host/target duplicates as duplicates.  In essence, behave the same as without `--target` (but still filtering for the given target).
2. Display some additional information (like host/target on each line).

**Notes**

Output of `cargo version`:
cargo 1.54.0-nightly (070e459c2 2021-05-11)
