### ISSUE TITLE
Document directories for caching in CI

### ISSUE THREAD

**Issue by xenoterracide** [rust-lang/cargo#9581]
I was reading the CI documentation https://doc.rust-lang.org/cargo/guide/continuous-integration.html

and I was unable to find what directories I should be able to cache, specifically I was interested in the ones that contain dependencies. I've come up with this, and am using github CI, but I don't need documentation for every CI system out there, just documentation for what directories to/can be safely cached.

```yml
on:
  push:
    paths:
    - '**.rs'
    - '**.toml'
    - Cargo.lock
    - .github/**
name: build
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      id: rust-toolchain
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          target/debug/deps
          target/debug/build
        key: ${{ steps.rust-toolchain.outputs.rustc_hash }}-${{hashFiles('Cargo.lock')}}
    - run: cargo fmt --all -- --check
    - run: cargo check --all
    - run: cargo clippy --all
    - run: cargo build --all
    - run: cargo test --all
```
