### ISSUE TITLE
Misclassification of dev-dependencies on crates.io

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/cargo#962]
Hello,

When one declares a dev dependency as

``` toml
[dev-dependencies]
foo = "0.0.1"
```

and publishes the package on crates.io, the dependency ends up in the section “Dependencies” on the corresponding page on crates.io; however, it presumably should lend under “Dev-Dependencies.”

Thank you.

Regards,
Ivan
