### ISSUE TITLE
Patch git dependency in a workspace or sub-directory

### ISSUE THREAD

**Issue by ratijas** [rust-lang/cargo#9624]
**Describe the problem you are trying to solve**

Patch syntax allows replacing a dependency's git URL, but it doesn't seem allow to specify a directory in that repository. At least, it is not documented at https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html. Essentially, it is useless when patched crate is a part of a cargo workspace.

**Describe the solution you'd like**

Two solutions:

More integrated with cargo/rust: specify workspace member's package name, so that cargo will parse manifest and resolve to the required directory automatically.

More general: manually specify sub-directory of a git repository, so that cargo would look for a crate's `Cargo.toml` manifest in that dir.

**Notes**

I think, both proposed solutions are fine and can be implemented concurrently and without interfering each other.

Related: #6126

**Comment by ratijas** [comment]
Because of this lack of functionality, I am currently forced to download the whole repo, store it somewhere, and override each dependency of a workspace in a patch section like this:

```toml
[patch.crates-io]
cpp        = { path = "../../rust-cpp/cpp" }
cpp_common = { path = "../../rust-cpp/cpp_common" }
cpp_macros = { path = "../../rust-cpp/cpp_macros" }
cpp_build  = { path = "../../rust-cpp/cpp_build" }
```

Instead, I'd like to be able to write something like this:

```toml
[patch.crates-io]
cpp        = { git = "https://github.com/mystor/rust-cpp", member = "cpp" }
cpp_common = { git = "https://github.com/mystor/rust-cpp", member = "cpp_common" }
cpp_macros = { git = "https://github.com/mystor/rust-cpp", member = "cpp_macros" }
cpp_build  = { git = "https://github.com/mystor/rust-cpp", member = "cpp_build" }
```

**Comment by ehuss** [comment]
Cargo should automatically find the package based on the name. That is, you should be able to write:

```toml
[patch.crates-io]
cpp        = { git = "https://github.com/mystor/rust-cpp" }
cpp_common = { git = "https://github.com/mystor/rust-cpp" }
cpp_macros = { git = "https://github.com/mystor/rust-cpp" }
cpp_build  = { git = "https://github.com/mystor/rust-cpp" }
```

Does that work for you?

**Comment by ratijas** [comment]
Works on Linux now. How strange. I'm almost sure I tried exactly that, and it didn't work yesterday on Windows. I'll check Windows again soon.

**Comment by ratijas** [comment]
Nevermind my stupidity.  git patches work with workspaces on Windows too. Anyway, it probably worth mentioning in the documentation that workspaces are explicitly supported.

**Comment by ratijas** [comment]
However, `path` variant does not support workspaces. It requires a full path to the final directory with a specific crate.

No good:

```toml
qttypes          = { path = "../../qmetaobject-rs" }
qmetaobject      = { path = "../../qmetaobject-rs" }
qmetaobject_impl = { path = "../../qmetaobject-rs" }
```

Good:

```toml
qttypes          = { path = "../../qmetaobject-rs/qttypes" }
qmetaobject      = { path = "../../qmetaobject-rs/qmetaobject" }
qmetaobject_impl = { path = "../../qmetaobject-rs/qmetaobject_impl" }
```
