### ISSUE TITLE
`[patch.crates-io]` ignores all features

### ISSUE THREAD

**Issue by qiujiangkun** [rust-lang/cargo#9629]
**Problem**
I was trying to patch some of my deps, with additional features enabled in my workspace. However, features specified in `[patch.crates-io]` are all ignored.

**Steps**
```toml
[path.crates-io]
async-tungstenite = { git = "https://github.com/qiujiangkun/async-tungstenite", rev="1a544fb13fe46b22aa6df94e49277f49f8ffa8ca", features=["there-is-no-such-feature-whatsoever", "no-verbose-logging"] }
```
The features are ignored, no error is given(there-is-no-such-feature-whatsoever), and no feature is actually enabled(no-verbose-logging)

**Possible Solution(s)**
I think we can simply fix it, gives a hard error saying this is not supported, or gives a warning saying features are currently ignored

Output of `cargo version`:
```rust
cargo 1.54.0-nightly (44456677b 2021-06-12)
```
