### ISSUE TITLE
Doc-tests no longer receive dev-dependencies

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#9637]
**Problem**

Similar to https://github.com/rust-lang/cargo/issues/1474, I'm seeing a situation where doc-tests do not observe a specified dev-dependency. 

**Steps**

```rust
#[cfg(feature = "libc")]
pub struct Exists;

/// ```
/// use banana::Exists;
/// ```
pub struct Another;
```

```toml
[package]
name = "banana"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = { version = "0.2", optional = true }

[dev-dependencies]
libc = "0.2"
```

and then `cargo test`.

**Possible Solution(s)**

~~:shrug: This works correctly for regular tests.~~ No, that doesn't work either :( Not sure why I thought this is a regression, or a difference in behaviour.

**Notes**

Output of `cargo version`: 1.52.0
