### ISSUE TITLE
Suggest typo corrections in Cargo.toml

### ISSUE THREAD

**Issue by opeik** [rust-lang/cargo#9731]
**Describe the problem you are trying to solve**
Rust does an excellent job at catching and providing suggestions for typos in Rust code, but I feel the same is lacking in Cargo. 

Given the following `Cargo.toml`:
```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2018"
[dependencies]
serde = { version = "1.0.126", feature = ["derive"] }
```
Running `cargo build` only hints that there is an issue:
```
❯ cargo build
warning: unused manifest key: dependencies.serde.feature
```

**Describe the solution you'd like**
A suggestion similar to the Rust compiler:

```
error[E12345]: unknown dependency attribute `feature`
 --> Cargo.toml:6:32
  |
6 |     serde = { version = "1.0.126", feature = ["derive"] }
  |                                    ^^^ help: did you mean `features`?
```
