### ISSUE TITLE
Dependency name override makes cargo think it should be looking for the overriden name on crates.io

### ISSUE THREAD

**Issue by pm065** [rust-lang/cargo#9947]
If I have a dependency like this:
```toml
[dependencies]
serde_json = {version = "1.0.68", package = "json"}
```
and I try to build:
```
error: failed to select a version for the requirement `json = "^1.0.68"`
candidate versions found which didn't match: 0.12.4, 0.12.2, 0.12.1...
location searched: crates.io index
```
Presumably, `cargo` thinks it should be getting [the `json` crate](https://lib.rs/json) instead of [the `serde_json` crate](https://lib.rs/serde_json) because of the override.

OS: Debian GNU/Linux Bullseye
toolchain: 1.55 stable
`cargo` version: 1.55.0
